@echo off
@echo appendImages ...
..\..\VisualMagick\bin\appendImages
@echo attributes ...
..\..\VisualMagick\bin\attributes
@echo averageImages ...
..\..\VisualMagick\bin\averageImages
@echo coalesceImages ...
..\..\VisualMagick\bin\coalesceImages
@echo color ...
..\..\VisualMagick\bin\color
@echo montageImages ...
..\..\VisualMagick\bin\montageImages
@echo morphImages ...
..\..\VisualMagick\bin\morphImages
@echo readWriteBlob ...
..\..\VisualMagick\bin\readWriteBlob
@echo readWriteImages ...
..\..\VisualMagick\bin\readWriteImages

