#!/bin/sh
#
# Execute this script to update the build environment if the version of
# Automake or Autoconf is changed.
#

libtoolize --verbose --copy --force
# echo 'm4_include([ltdl/m4/lt~obsolete.m4])' >> aclocal.m4
aclocal -I ltdl/m4 -I m4
autoheader
autoconf
automake --verbose --add-missing --copy --force-missing

