.TH animate 1 "Date: 2002/02/15 01:00:00" "ImageMagick"
.SH NAME
animate - animate a sequence of images
.SH SYNOPSIS

\fBanimate\fP \fB[\fP \fIoptions\fP \fB...]\fP \fIfile\fP [ [
\fIoptions\fP ...] \fIfile\fP ...]

.SH DESCRIPTION

\fBAnimate\fP displays a sequence of images on any workstation display
running an X server. \fBanimate\fP first determines the hardware capabilities
of the workstation. If the number of unique colors in an image is less
than or equal to the number the workstation can support, the image is displayed
in an X window. Otherwise the number of colors in the image is first reduced
to match the color resolution of the workstation before it is displayed.

This means that a continuous-tone 24 bits-per-pixel image can display on
a 8 bit pseudo-color device or monochrome device. In most instances the
reduced color image closely resembles the original. Alternatively, a monochrome
or pseudo-color image sequence can display on a continuous-tone 24 bits-per-pixel
device.

To help prevent color flashing on X server visuals that have colormaps,
\fBanimate\fP
creates a single colormap from the image sequence. This can be rather time
consuming. You can speed this operation up by reducing the colors in the
image before you "animate" them. Use \fBmogrify\fP to color reduce the
images to a single colormap. See \fBmogrify(1)\fP for details. Alternatively,
you can use a Standard Colormap; or a static, direct, or true color visual.
You can define a Standard Colormap with \fIxstdcmap\fP. See \fBxstdcmap(1)\fP
for details. This method is recommended for colormapped X server because
it eliminates the need to compute a global colormap.
.SH EXAMPLES

To animate a set of images of a cockatoo, use:


    animate cockatoo.*

To animate a cockatoo image sequence while using the Standard Colormap
\fIbest\fP, use:


    xstdcmap -best
    animate -map best cockatoo.*

To animate an image of a cockatoo without a border centered on a backdrop,
use:


    animate +borderwidth -backdrop cockatoo.*
.SH OPTIONS

For a more detailed description of each option, see
\fIImageMagick(1)\fP.

.TP
.B "-backdrop \fI<color>"\fP
\fRdisplay the image centered on a backdrop.
.TP
.B "-background \fI<color>"\fP
\fRthe background color
.TP
.B "-bordercolor \fI<color>"\fP
\fRthe border color
.TP
.B "-borderwidth \fI<geometry>"\fP
\fRthe border width
.TP
.B "-cache \fI<threshold>"\fP
\fRmegabytes of memory available to the pixel cache
.TP
.B "-chop \fI<width>x<height>{+-}<x>{+-}<y>{%}"\fP
\fRremove pixels from the interior of an image
.TP
.B "-colormap \fI<type>"\fP
\fRdefine the colormap type
.TP
.B "-colors \fI<value>"\fP
\fRpreferred number of colors in the image
.TP
.B "-colorspace \fI<value>"\fP
\fRthe type of colorspace
.TP
.B "-crop \fI<width>x<height>{+-}<x>{+-}<y>{%}"\fP
\fRpreferred size and location of the cropped image
.TP
.B "-debug"
\fRenable debug printout
.TP
.B "-delay \fI<1/100ths of a second>"\fP
\fRdisplay the next image after pausing
.TP
.B "-density \fI<width>x<height>"\fP
\fRvertical and horizontal resolution in pixels of the image
.TP
.B "-depth \fI<value>"\fP
\fRdepth of the image
.TP
.B "-display \fI<host:display[.screen]>"\fP
\fRspecifies the X server to contact
.TP
.B "-dispose \fI<method>"\fP
\fRGIF disposal method
.TP
.B "-dither"
\fRapply Floyd/Steinberg error diffusion to the image
.TP
.B "-font \fI<name>"\fP
\fRuse this font when annotating the image with text
.TP
.B "-foreground \fI<color>"\fP
\fRdefine the foreground color
.TP
.B "-gamma \fI<value>"\fP
\fRlevel of gamma correction
.TP
.B "-geometry \fI<width>x<height>{+-}<x>{+-}<y>{%}{@} {!}{<}{>}"\fP
\fRpreferred size and location of the Image window.
.TP
.B "-help"
\fRprint usage instructions
.TP
.B "-iconGeometry \fI<geometry>"\fP
\fRspecify the icon geometry
.TP
.B "-iconic"
\fRiconic animation
.TP
.B "-interlace \fI<type>"\fP
\fRthe type of interlacing scheme
.TP
.B "-map \fI<type>"\fP
\fR
display image using this type.
.TP
.B "-matte"
\fRstore matte channel if the image has one
.TP
.B "-mattecolor \fI<color>"\fP
\fRspecify the matte color
.TP
.B "-monochrome"
\fRtransform the image to black and white
.TP
.B "-name"
\fRname an image
.TP
.B "-noop"
\fRNOOP (no option)
.TP
.B "-pause \fI<seconds>"\fP
\fRpause between animation loops [animate]
.TP
.B "-remote"
\fRperform a remote operation
.TP
.B "-rotate \fI<degrees{<}{>}>"\fP
\fRapply Paeth image rotation to the image
.TP
.B "-scenes \fI<value-value>"\fP
\fRrange of image scene numbers to read
.TP
.B "-shared_memory"
\fRuse shared memory
.TP
.B "-size \fI<width>x<height>{+offset}"\fP
\fRwidth and height of the image
.TP
.B "-text_font \fI<name>"\fP
\fRfont for writing fixed-width text
.TP
.B "-title \fI<string>"\fP
\fRassign a title to the displayed image
.TP
.B "-treedepth \fI<value>"\fP
\fRtree depth for the color reduction algorithm
.TP
.B "-trim"
\fRtrim an image
.TP
.B "-verbose"
\fRprint detailed information about the image
.TP
.B "-visual \fI<type>"\fP
\fRanimate images using this X visual type
.TP
.B "-window \fI<id>"\fP
\fRmake image the background of a window

Any option you specify on the command line remains in effect for the group
of images following it, until the group is terminated by the appearance of
any option or \fB-noop\fP.  For example, to animate three images, the first
with 32 colors, the second with an unlimited number of colors, and the
third with only 16 colors, use:


     animate -colors 32 cockatoo.1 -noop cockatoo.2
             -colors 16 cockatoo.3

\fBAnimate\fP options can appear on the command line or in your X resources
file. See \fIX(1)\fP. Options on the command line supersede values specified
in your X resources file.
Image filenames may appear in any order on the command line if the image
format is \fIMIFF\fP (refer to \fBmiff(5)\fP and the
\fBscene\fP keyword
is specified in the image. Otherwise the images will display in the order
they appear on the command line.
.SH MOUSE BUTTONS

Press any button to map or unmap the Command widget. See the next section
for more information about the Command widget.
.SH COMMAND WIDGET

The Command widget lists a number of sub-menus and commands. They are

    \fBAnimate\fP

        Open
        Play
        Step
        Repeat
        Auto Reverse

    \fBSpeed\fP

        Faster
        Slower

    \fBDirection\fP

        Forward
        Reverse

    \fBImage Info\fP
    \fBHelp\fP
    \fBQuit\fP


Menu items with a indented triangle have a sub-menu. They are represented
above as the indented items. To access a sub-menu item, move the pointer
to the appropriate menu and press a button and drag. When you find the
desired sub-menu item, release the button and the command is executed.
Move the pointer away from the sub-menu if you decide not to execute a
particular command.
.SH KEYBOARD ACCELERATORS
.in 15

.in 15
.B "\fBCtl+O\fP"
.in 20
 \fR
.in 20
Press to load an image from a file.
.in 15
.in 15
.B "\fBspace\fP"
.in 20
 \fR
.in 20
Press to display the next image in the sequence.
.in 15
.in 15
.B "\fB<\fP"
.in 20
 \fR
.in 20
Press to speed-up the display of the images.  Refer to
\fB-delay\fP for more information.
.in 15
.in 15
.B "\fB>\fP"
.in 20
 \fR
.in 20
Press to slow the display of the images.  Refer to
\fB-delay\fP for more information.
.in 15
.in 15
.B "\fB?\fP"
.in 20
 \fR
.in 20
Press to display information about the image.  Press
any key or button to erase the information.
.in 15
.in 20
This information is printed: image name;  image size;
and the total number of unique colors in the image.
.in 15
.in 15
.B "\fBF1\fP"
.in 20
 \fR
.in 20
Press to display helpful information about \fBanimate(1)\fP.
.in 15
.in 15
.B "\fBCtl-q\fP"
.in 20
 \fR
.in 20
Press to discard all images and exit program.
.in 15

.SH X RESOURCES

\fBAnimate\fP options can appear on the command line or in your X resource
file. Options on the command line supersede values specified in your X
resource file. See \fBX(1)\fP for more information on X resources.

All \fBanimate\fP options have a corresponding X resource. In addition,
the \fBanimate\fP program uses the following X resources:
.in 15

.in 15
.B "\fBbackground\fP \fB(\fP\fIclass\fP \fBBackground)\fP"
.in 20
 \fR
.in 20

Specifies the preferred color to use for the Image window background. The
default is #ccc.
.in 15
.in 15
.B "\fBborderColor\fP \fB(\fP\fIclass\fP \fBBorderColor)\fP"
.in 20
 \fR
.in 20

Specifies the preferred color to use for the Image window border. The default
is #ccc.
.in 15
.in 15
.B "\fBborderWidth\fP \fB(\fP\fIclass\fP \fBBorderWidth)\fP"
.in 20
 \fR
.in 20

Specifies the width in pixels of the Image window border. The default is
2.
.in 15
.in 15
.B "\fBfont\fP \fB(\fP\fIclass\fP \fBFont\fP \fBor\fP \fBFontList)\fP"
.in 20
 \fR
.in 20

Specifies the name of the preferred font to use in normal formatted text.
The default is 14 point \fIHelvetica\fP.
.in 15
.in 15
.B "\fBforeground\fP \fB(\fP\fIclass\fP \fBForeground)\fP"
.in 20
 \fR
.in 20

Specifies the preferred color to use for text within the Image window.
The default is black.
.in 15
.in 15
.B "\fBgeometry\fP \fB(\fP\fIclass\fP \fBgeometry)\fP"
.in 20
 \fR
.in 20

Specifies the preferred size and position of the image window. It is not
necessarily obeyed by all window managers.
Offsets, if present, are handled in \fIX(1)\fP style.  A negative x offset is
measured from the right edge of the screen to the right edge of the icon,
and a negative y offset is measured from the bottom edge of the screen
to the bottom edge of the icon.
.in 15
.in 15
.B "\fBiconGeometry\fP \fB(\fP\fIclass\fP \fBIconGeometry)\fP"
.in 20
 \fR
.in 20

Specifies the preferred size and position of the application when iconified.
It is not necessarily obeyed by all window managers.
Offsets, if present, are handled in the same manner as in class Geometry.
.in 15
.in 15
.B "\fBiconic\fP \fB(\fP\fIclass\fP \fBIconic)\fP"
.in 20
 \fR
.in 20

This resource indicates that you would prefer that the application's windows
initially not be visible as if the windows had be immediately iconified
by you. Window managers may choose not to honor the application's request.
.in 15
.in 15
.B "\fBmatteColor\fP \fB(\fP\fIclass\fP \fBMatteColor)\fP"
.in 20
 \fR
.in 20

Specify the color of windows. It is used for the backgrounds of windows,
menus, and notices. A 3D effect is achieved by using highlight and shadow
colors derived from this color. Default value: #ddd.
.in 15
.in 15
.B "\fBname\fP \fB(\fP\fIclass\fP \fBName)\fP"
.in 20
 \fR
.in 20

This resource specifies the name under which resources for the application
should be found. This resource is useful in shell aliases to distinguish
between invocations of an application, without resorting to creating links
to alter the executable file name. The default is the application name.
.in 15
.in 15
.B "\fBsharedMemory\fP \fB(\fP\fIclass\fP \fBSharedMemory)\fP"
.in 20
 \fR
.in 20

This resource specifies whether animate should attempt use shared memory
for pixmaps. ImageMagick must be compiled with shared memory support, and
the display must support the MIT-SHM extension. Otherwise, this resource
is ignored. The default is True.
.in 15
.in 15
.B "\fBtext_font\fP \fB(\fP\fIclass\fP \fBtextFont)\fP"
.in 20
 \fR
.in 20

Specifies the name of the preferred font to use in fixed (typewriter style)
formatted text. The default is 14 point \fICourier\fP.
.in 15
.in 15
.B "\fBtitle\fP \fB(\fP\fIclass\fP \fBTitle)\fP"
.in 20
 \fR
.in 20

This resource specifies the title to be used for the Image window. This
information is sometimes used by a window manager to provide some sort
of header identifying the window. The default is the image file name.
.in 15

.SH ENVIRONMENT
.TP
.B "DISPLAY"
\fRTo get the default host, display number, and screen.
.SH ACKNOWLEDGEMENTS
.in 15

.in 15
.in 20
.B ""
.in 20
 \fR
The \fBMIT X Consortium\fP for making network transparent graphics a
reality.
.in 15
.in 15
.in 20
.B ""
.in 20
 \fR
\fIMichael Halle\fP, \fBSpatial Imaging Group at MIT\fP, for the initial
implementation of Alan Paeth's image rotation algorithm.
.in 15
.in 15
.in 20
.B ""
.in 20
 \fR
\fIDavid Pensak\fP, \fBduPont\fP, for providing a computing
environment that made this program possible.
.in 15
.in 15
.in 20
.B ""\fIPaul Raveling\fP, \fBUSC Information Sciences Institute\fP.
.in 20
 \fR
The spatial subdivision color reduction algorithm is based on his Img
software.
.in 15

.SH SEE ALSO

display(1), composite(1), conjure(1), convert(1), identify(1),
import(1), mogrify(1), montage(1)

.SH COPYRIGHT

\fBCopyright (C) 2002 ImageMagick Studio\fP

\fBPermission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the ImageMagick
is furnished to do so, subject to the following conditions:\fP

\fBThe above copyright notice and this permission notice shall be included
in all copies or substantial portions of ImageMagick.\fP

\fBThe software is provided "as is", without warranty of any kind, express
or implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out
of or in connection with ImageMagick or the use or other dealings in
ImageMagick.\fP

\fBExcept as contained in this notice, the name of the
ImageMagick Studio LLC shall not be used in advertising or otherwise to
promote the sale, use or other dealings in ImageMagick without prior written
authorization from the ImageMagick Studio.\fP
.SH AUTHORS

\fIJohn Cristy, ImageMagick Studio LLC\fP.

