.TH composite 1 "Date: 2002/02/15 01:00:00" "ImageMagick"
.SH NAME
composite - composite images together.
.SH SYNOPSIS

\fBcomposite\fP \fB[\fP \fIoptions\fP \fB... ]\fP \fIimage composite\fP
\fB[\fP \fImask\fP \fB]\fP \fIcomposited\fP

.SH DESCRIPTION

\fBcomposite\fP composite images to create new images.

The optional \fBmask\fP can be used to provide matte information for
\fBcomposite\fP
when it has none or if you want a different mask. A mask image is typically
grayscale and the same size as \fBcomposite\fP. If the image is not grayscale,
it is converted to grayscale and the resulting intensities are used as
matte information.

If \fIcomposited\fP already exists, you will be prompted as to whether it
should be overwritten.
.SH EXAMPLES

To composite an image of a cockatoo with a perch, use:

    composite cockatoo.miff perch.ras composite.miff

To compute the difference between images in a series, use:

    composite -compose difference series.1 series.2
              difference.miff

To composite an image of a cockatoo with a perch starting at location (100,150),
use:

    composite -geometry +100+150 cockatoo.miff
              perch.ras composite.miff

To tile a logo across your image of a cockatoo, use

    convert +shade 30x60 cockatoo.miff mask.miff
    composite -compose bumpmap -tile logo.png
              cockatoo.miff mask.miff composite.miff

To composite a red, green, and blue color plane into a single composite image,
try

    composite -compose CopyGreen red.png green.png
              red-green.png
    composite -compose CopyBlue red-green.png blue.png
              composite.png
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect only for the image that follows.  All
options are reset to their default values after each image is read.

For a more detailed description of each option, see
\fIImageMagick(1)\fP.

.TP
.B "-background \fI<color>"\fP
\fRthe background color
.TP
.B "-cache \fI<threshold>"\fP
\fRmegabytes of memory available to the pixel cache
.TP
.B "-colors \fI<value>"\fP
\fRpreferred number of colors in the image
.TP
.B "-colorspace \fI<value>"\fP
\fRthe type of colorspace
.TP
.B "-comment \fI<string>"\fP
\fRannotate an image with a comment
.TP
.B "-compose \fI<operator>"\fP
\fRthe type of image composition
.TP
.B "-compress \fI<type>"\fP
\fRthe type of image compression
.TP
.B "-debug"
\fRenable debug printout
.TP
.B "-density \fI<width>x<height>"\fP
\fRvertical and horizontal resolution in pixels of the image
.TP
.B "-depth \fI<value>"\fP
\fRdepth of the image
.TP
.B "-displace \fI<horizontal scale>x<vertical scale>"\fP
\fRshift image pixels as defined by a displacement map
.TP
.B "-display \fI<host:display[.screen]>"\fP
\fRspecifies the X server to contact
.TP
.B "-dispose \fI<method>"\fP
\fRGIF disposal method
.TP
.B "-dissolve \fI<percent>"\fP
\fRdissolve an image into another by the given percent
.TP
.B "-dither"
\fRapply Floyd/Steinberg error diffusion to the image
.TP
.B "-endian \fI<type>"\fP
\fRspecify endianness (MSB or LSB) of output image
.TP
.B "-filter \fI<type>"\fP
\fRuse this type of filter when resizing an image
.TP
.B "-font \fI<name>"\fP
\fRuse this font when annotating the image with text
.TP
.B "-geometry \fI<width>x<height>{+-}<x>{+-}<y>{%}{@} {!}{<}{>}"\fP
\fRpreferred size and location of the Image window.
.TP
.B "-gravity \fI<type>"\fP
\fRdirection primitive  gravitates to when annotating the image.
.TP
.B "-help"
\fRprint usage instructions
.TP
.B "-interlace \fI<type>"\fP
\fRthe type of interlacing scheme
.TP
.B "-label \fI<name>"\fP
\fRassign a label to an image
.TP
.B "-matte"
\fRstore matte channel if the image has one
.TP
.B "-monochrome"
\fRtransform the image to black and white
.TP
.B "-negate"
\fRreplace every pixel with its complementary color
.TP
.B "-page \fI<width>x<height>{+-}<x>{+-}<y>{%}{!}{<}{>}"\fP
\fRsize and location of an image canvas
.TP
.B "-profile \fI<filename>"\fP
\fRadd ICM, IPTC, or generic profile  to image
.TP
.B "-quality \fI<value>"\fP
\fRJPEG/MIFF/PNG compression level
.TP
.B "-resize \fI<width>x<height>{+-}<x>{+-}<y>{%}{@}{!}{<}{>}"\fP
\fRresize and locate an image
.TP
.B "-rotate \fI<degrees>{<}{>}"\fP
\fRapply Paeth image rotation to the image
.TP
.B "-scene \fI<value>"\fP
\fRset scene number
.TP
.B "-sharpen \fI<radius>x<sigma>"\fP
\fRsharpen the image
.TP
.B "-size \fI<width>x<height>{+offset}"\fP
\fRwidth and height of the image
.TP
.B "-stegano \fI<offset>"\fP
\fRhide watermark within an image
.TP
.B "-stereo"
\fRcomposite two images to create a stereo anaglyph
.TP
.B "-treedepth \fI<value>"\fP
\fRtree depth for the color reduction algorithm
.TP
.B "-trim"
\fRtrim an image
.TP
.B "-type \fI<type>"\fP
\fRthe image type
.TP
.B "-units \fI<type>"\fP
\fRthe type of image resolution
.TP
.B "-unsharp \fI<radius>x<sigma>"\fP
\fRsharpen the image with an unsharp mask operator
.TP
.B "-verbose"
\fRprint detailed information about the image
.TP
.B "-watermark \fI<brightness>x<saturation>"\fP
\fRpercent brightness and saturation of a watermark
.TP
.B "-write \fI<filename>"\fP
\fRwrite  an image sequence [\fIconvert, composite\fP]
.SH ENVIRONMENT
.TP
.B "DISPLAY"
\fRTo get the default host, display number, and screen.
.SH SEE ALSO

animate(1), display(1), conjure(1), convert(1), identify(1),
import(1), mogrify(1), montage(1)

.SH COPYRIGHT

\fBCopyright (C) 2002 ImageMagick Studio\fP

\fBPermission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the ImageMagick
is furnished to do so, subject to the following conditions:\fP

\fBThe above copyright notice and this permission notice shall be included
in all copies or substantial portions of ImageMagick.\fP

\fBThe software is provided "as is", without warranty of any kind, express
or implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out
of or in connection with ImageMagick or the use or other dealings in
ImageMagick.\fP

\fBExcept as contained in this notice, the name of the
ImageMagick Studio LLC shall not be used in advertising or otherwise to
promote the sale, use or other dealings in ImageMagick without prior written
authorization from the ImageMagick Studio.\fP
.SH AUTHORS

\fIJohn Cristy, ImageMagick Studio LLC,\fP
\fIGlenn Randers-Pehrson, ImageMagick Studio LLC.\fP

