.SH NAME
conjure - process a Magick Scripting Language (MSL) script

\fBWARNING: Conjure and MSL are in very early development and the
syntax is subject to change!\fP


.SH SYNOPSIS

\fBconjure\fP [ options ] script_file.msl

.SH DESCRIPTION

The Magick scripting language (MSL) will primarily
benefit those that want to accomplish custom image processing tasks but
do not wish to program, or those that do not have access to a Perl
interpreter or a compiler.  The interpreter is called conjure and here
is an example script:

    <?xml version="1.0" encoding="UTF-8"?>
    <image size="400x400" >
      <read filename="image.gif" />
      <get width="base-width" height="base-height" />
      <resize geometry="%[dimensions]" />
      <get width="width" height="height" />
      <print output=
        "Image sized from %[base-width]x%[base-height]
         to %[width]x%[height].\\n" />
      <write filename="image.png" />
    </image>

invoked with

    conjure -dimensions 400x400 incantation.msl

All operations will closely follow the key/value pairs defined in
PerlMagick, unless otherwise noted.


\fBConjure\fP is in the early stages of development as of
December 2001.


This early announcement is to allow ImageMagick users to contribute ideas 
early in the process so when the scripting language is released it will
be useful/stable from the get-go!  If you want to contribute suggestions
about the Magick scripting langauge (MSL), post them to
magick-developers@imagemagick.org.

.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect until it is explicitly changed by specifying
the option again with a different effect, or if it is changed by a statement
in the scripting language.


You can define your own keyword/value pairs on the command line.
The script can then use this information when setting values by including
%[keyword] in the string.  For example, if you included
"-dimensions 400x400" on the command line, as illustrated above,
then any string
containing "%[dimensions]" would have 400x400 substituted.
This can be either an entire string, such as
geometry="%[dimensions]" or part of a string such as
filename="%[basename].png".

.SH MAGICK SCRIPTING LANGUAGE

The Magick Scripting Language (MSL) presently defines the following
elements and their attributes:


.TP
.B "<image>"
Define a new image object.
\fB</image>\fP destroys it. Because of this, if you wish
to reference multiple "subimages" (aka pages or layers),
you can embed one \fBimage\fP element inside of
another. For example:


    <image>
    <read filename="input.png" />
    <get width="base-width" height="base-height" />
    <image height="base-height" width="base-width">
    <label>this is a simple label<label/>
    <image />
    <write filename="output.mng" />
    </image>


    <image size="400x400" />

.TP
.B "<group>"
Define a new group of image objects.
By default, images are only valid for the life of
their \fB<image>\fP element.


    <image>   -- create the image
    .....     -- do stuff with it
    </image>  -- dispose of the image


However, in a group, all images in that group will stay 
around for the life of the group:


    <group>                   -- start a group
        <image>               -- create an image
        ....                  -- do stuff
        </image>              -- NOOP
        <image>               -- create another image
        ....                  -- do more stuff
        </image>              -- NOOP
        <write filename
             ="image.mng" />  -- output
    </group>                  -- dispose of both images

.TP
.B "<read>"
Read a new image from a disk file.


    <read filename="image.gif" />

To read two images use


    <read filename="image.gif" />
    <read filename="image.png" />


.TP
.B "<write>"
Write the image(s) to disk, either as
a single multiple-image file or multiple ones if necessary.


     <write filename=image.tiff" />

.TP
.B "<set>"
opacity (can handle percentage values, e.g., 50%, but
UNFORTUNATELY, you have to do %%!), background,
bordercolor, mattecolor, clip-mask, colorspace (RGB, CMYK, Gray),
density, magick
.TP
.B "<get>"
Gets any attribute recognized by
PerlMagick's GetAttribute() and stores it as an image attribute for later
use. Currently only \fIwidth\fP and \fIheight\fP are supported.


    <get width="base-width" height="base-height" />
    <print output=
      "Image size: %[base-width]x%[base-height].\\n" />

.TP
.B "<border>"
    fill, geometry, height, width
.TP
.B "<blur>"
    radius, sigma
.TP
.B "<charcoal>"
    radius, sigma
.TP
.B "<chop>"
    geometry, height, width, x, y
.TP
.B "<composite>"
    compose, gravity
.TP
.B "<crop>"
    geometry, height, width, x, y
.TP
.B "<despeckle>"
.TP
.B "<edge>"
    radius
.TP
.B "<emboss>"
    radius, sigma
.TP
.B "<enhance>"
.TP
.B "<equalize>"
.TP
.B "<flatten>"
.TP
.B "<flip>"
.TP
.B "<flop>"
.TP
.B "<frame>"
    fill, geometry, height, width, x, y, inner, outer
.TP
.B "<gamma>"
    red, green, blue
.TP
.B "<get>"
.TP
.B "<image>"
.TP
.B "<implode>"
    amount
.TP
.B "<magnify>"
.TP
.B "<medianfilter>"
    radius
.TP
.B "<minify>"
.TP
.B "<normalize>"
.TP
.B "<oilpaint>"
    radius
.TP
.B "<print>"
    output
.TP
.B "<read>"
.TP
.B "<reducenoise>"
    radius
.TP
.B "<resize>"
    blur, filter, height, width
.TP
.B "<roll>"
    geometry, x, y
.TP
.B "<rotate>"
    degrees
.TP
.B "<sample>"
    geometry, height, width
.TP
.B "<scale>"
    geometry, height, width
.TP
.B "<sharpen>"
    radius, sigma
.TP
.B "<shave>"
    geometry, height, width
.TP
.B "<shear>"
    x, y
.TP
.B "<solarize>"
    threshold
.TP
.B "<spread>"
    radius
.TP
.B "<stegano>"
    image
.TP
.B "<stereo>"
    image
.TP
.B "<swirl>"
    degrees
.TP
.B "texture>"
    image
.TP
.B "<threshold>"
    threshold
.TP
.B "<transparent>"
    color
.TP
.B "<trim>"

.SH COPYRIGHT
Copyright (C) 2002 ImageMagick Studio, a non-profit organization dedicated
to making software imaging solutions freely available.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the
ImageMagick is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of ImageMagick.

The software is provided "as is", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.  In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out of
or in connection with ImageMagick or the use or other dealings in
ImageMagick.

Except as contained in this notice, the name of the ImageMagick Studio
shall not be used in advertising or otherwise to promote the sale, use or
other dealings in ImageMagick without prior written authorization from the
ImageMagick Studio.
.SH AUTHORS
John Cristy, ImageMagick Studio LLC
.br
Leonard Rosenthol, ImageMagick Studio LLC
