.TH convert 1 "Date: 2002/01/01 01:00:00" "ImageMagick"
.TP
.in 15
.in 15
.in 20
.SH NAME

convert - convert an image or sequence of images

.SH SYNOPSIS

\fBconvert\fP \fB[\fP \fIoptions\fP \fB... ]\fP \fIinput_file output_file\fP

.SH DESCRIPTION

\fBConvert\fP converts an input file using one image format to an output
file with a differing image format. In addition, various types of image
processing can be performed on the converted image during the conversion
process. \fBConvert\fP recognizes the following image formats:

.in 15

.in 5
o \fBAVS\fP - AVS X image file.
.in 0
.in 5
o \fBBIE+\fP - Joint Bi-level Image experts Group file interchange
format.
.in 0
.in 5
o \fBBMP+\fP - Microsoft Windows bitmap image file.
.in 0
.in 5
o \fBBMP24+\fP - Microsoft Windows 24-bit bitmap image file.
.in 0
.in 5
o \fBCGM\fP - Computer Graphics Metafile.
.in 0
.in 5
o \fBCMYK\fP - Raw cyan, magenta, yellow, and black samples
(8 or 16 bits, depending on the setting of the -depth option).
.in 0
.in 5
o \fBDCX+\fP - ZSoft IBM PC multi-page Paintbrush file.
.in 0
.in 5
o \fBDIB\fP - Microsoft Windows bitmap image file.
.in 0
.in 5
o \fBDICOM\fP - Medical image file.
.in 0
.in 5
o \fBEPDF\fP - Encapsulated Portable Document Format.
.in 0
.in 5
o \fBEPI\fP - Adobe Encapsulated PostScript Interchange format.
.in 0
.in 5
o \fBEPS\fP - Adobe Encapsulated PostScript file.
.in 0
.in 5
o \fBEPS2\fP - Adobe Level II Encapsulated PostScript file.
.in 0
.in 5
o \fBEPSF\fP - Adobe Encapsulated PostScript file.
.in 0
.in 5
o \fBEPSI\fP - Adobe Encapsulated PostScript Interchange format.
.in 0
.in 5
o \fBEPT\fP - Adobe Encapsulated PostScript Interchange format with
TIFF preview.
.in 0
.in 5
o \fBFAX+\fP - Group 3.
.in 0
.in 5
o \fBFIG\fP - TransFig image format.
.in 0
.in 5
o \fBFITS\fP - Flexible Image Transport System.
.in 0
.in 5
o \fBFPX\fP - FlashPix Format.
.in 0
.in 5
o \fBGIF\fP - CompuServe graphics interchange format; 8-bit color.
.in 0
.in 5
o \fBGIF87\fP - CompuServe graphics interchange format; 8-bit color
(version 87a).
.in 0
.in 5
o \fBGRAY\fP - Raw gray samples (8 or 16 bits, depending on the
setting of the -depth option).
.in 0
.in 5
o \fBGRADIENT\fP- gradual passing from one shade to another. Specify
the desired shading with the filename (e.g. gradient:red-blue).
.in 0
.in 5
o \fBGRANITE\fP - granite texture.
.in 0
.in 5
o \fBHDF+\fP - Hierarchical Data Format.
.in 0
.in 5
o \fBHISTOGRAM\fP
.in 0
.in 5
o \fBHPGL\fP - HP-GL plotter language.
.in 0
.in 5
o \fBHTML\fP - Hypertext Markup Language
a with client-side image map.
.in 0
.in 5
o \fBJBIG+\fP - Joint Bi-level Image experts Group file interchange
format.
.in 0
.in 5
o \fBJPEG\fP - Joint Photographic Experts Group JFIF format;
compressed 24-bit color.
.in 0
.in 5
o \fBICO\fP - Microsoft icon.
.in 0
.in 5
o \fBLABEL\fP - text image.
.in 0
.in 5
o \fBMAP\fP - colormap intensities
(8 or 16 bits, depending on the setting of the -depth option) and indices
(8 or 16 bits, depending on whether colors > 256).
.in 0
.in 5
o \fBMIFF+\fP - Magick image file format.
.in 0
.in 5
o \fBMNG+\fP - Multiple-image Network Graphics.
.in 0
.in 5
o \fBMONO\fP - Bi-level bitmap in least-significant-byte (LSB) first
order.
.in 0
.in 5
o \fBMPEG+\fP - Motion Picture Experts Group file interchange
format.
.in 0
.in 5
o \fBMTV+\fP -
.in 0
.in 5
o \fBMVG\fP - Magick Vector Graphics.
.in 0
.in 5
o \fBM2V+\fP - Motion Picture Experts Group file interchange
format (version 2).
.in 0
.in 5
o \fBNETSCAPE\fP - Netscape 216 color cube.
.in 0
.in 5
o \fBNULL\fP - NULL image.
.in 0
.in 5
o \fBPBM+\fP - Portable bitmap format (black and white).
.in 0
.in 5
o \fBPCD\fP - Photo CD. The maximum resolution written is 512x768
pixels.
.in 0
.in 5
o \fBPCDS\fP - Photo CD. Decode with the sRGB color table.
.in 0
.in 5
o \fBPCL\fP - Page Control Language.
.in 0
.in 5
o \fBPCX\fP - ZSoft IBM PC Paintbrush file.
.in 0
.in 5
o \fBPDF+\fP - Portable Document Format.
.in 0
.in 5
o \fBPGM+\fP - Portable graymap format (gray scale).
.in 0
.in 5
o \fBPICT\fP - Apple Macintosh QuickDraw/PICT file.
.in 0
.in 5
o \fBPIX\fP - Alias/Wavefront RLE image format.
.in 0
.in 5
o \fBPLASMA \fP- plasma fractal image. Specify the base color as
the filename (e.g. plasma:gray). Use fractal to
initialize to a random value (e.g. plasma:fractal).
.in 0
.in 5
o \fBPNG\fP - Portable Network Graphics.
.in 0
.in 5
o \fBPNM+\fP - Portable anymap.
.in 0
.in 5
o \fBPPM+\fP - Portable pixmap format (color).
.in 0
.in 5
o \fBPS+\fP - Adobe PostScript file.
.in 0
.in 5
o \fBPSD\fP - Adobe PhotoShop bitmap file.
.in 0
.in 5
o \fBPS2+\fP - Adobe Level II PostScript file.
.in 0
.in 5
o \fBRAD\fP - Radiance image file.
.in 0
.in 5
o \fBRGB\fP - Raw red, green, and blue samples (8 or 16 bits,
depending on the setting of the -depth option).
.in 0
.in 5
o \fBRGBA\fP - Raw red, green, blue, and matte samples (8 or 16 bits,
depending on the setting of the -depth option).
.in 0
.in 5
o \fBRLA\fP - Alias/Wavefront image file; read only.
.in 0
.in 5
o \fBRLE\fP - Utah Run length encoded image file; read only.
.in 0
.in 5
o \fBSGI+\fP - Irix RGB image file.
.in 0
.in 5
o \fBSHTML\fP - Hypertext Markup Language a with client-side
image map.
.in 0
.in 5
o \fBSUN+\fP - SUN Rasterfile.
.in 0
.in 5
o \fBSVG+\fP - Scalable Vector Graphics.
.in 0
.in 5
o \fBTEXT\fP - raw text file; read only.
.in 0
.in 5
o \fBTGA+\fP - Truevision Targa image file.
.in 0
.in 5
o \fBTIFF+\fP - Tagged Image File Format.
.in 0
.in 5
o \fBTIFF24+\fP - 24-bit Tagged Image File Format.
.in 0
.in 5
o \fBTILE\fP - tile image with a texture.
.in 0
.in 5
o \fBTIM\fP - PSX TIM file.
.in 0
.in 5
o \fBTTF\fP - TrueType font file.
.in 0
.in 5
o \fBUIL\fP - X-Motif UIL table.
.in 0
.in 5
o \fBUYVY\fP - Interleaved YUV.
.in 0
.in 5
o \fBVICAR\fP - read only.
.in 0
.in 5
o \fBVID\fP - Visual Image Directory.
.in 0
.in 5
o \fBVIFF+\fP - Khoros Visualization image file.
.in 0
.in 5
o \fBWIN\fP - select image from or display image to your
computer screen.
.in 0
.in 5
o \fBX\fP - select image from or display image to your X server
screen.
.in 0
.in 5
o \fBXC\fP - constant image of X server color. Specify the image
color as the filename (e.g. xc:yellow).
.in 0
.in 5
o \fBXBM\fP - X Windows system bitmap, black and white only.
.in 0
.in 5
o \fBXPM\fP - X Windows system pixmap file (color).
.in 0
.in 5
o \fBXWD\fP - X Windows system window dump file (color).
.in 0
.in 5
o \fBYUV+\fP - CCIR 601 4:1:1 file.
.in 0


\fISupport for some of these formats require additional programs or libraries.
README
tells where to find this software\fP.

Note, a format delineated with + means that if more than one
image is specified, it is composited into a single multi-image file. Use
\fB+adjoin\fP
if you want a single image produced for each frame.

Raw images are expected to have one byte per pixel unless \fBImageMagick\fP
is compiled in 16-bit mode. Here, the raw data is expected to be stored
two bytes per pixel in most-significant-byte-first order.
You can tell if \fBImageMagick\fP was compiled in 16-bit mode by typing
"convert" without any options, and looking for "Q:16" in the first line of
output.
.SH EXAMPLES

To convert a \fIMIFF\fP image of a cockatoo to a SUN raster image, use:

    convert cockatoo.miff sun:cockatoo.ras

To convert a multi-page \fIPostScript\fP document to individual FAX pages,
use:

    convert -monochrome document.ps fax:page

To convert a TIFF image to a \fIPostScript\fP A4 page with the image in
the lower left-hand corner, use:

    convert -page A4+0+0 image.tiff document.ps

To convert a raw Gray image with a 128 byte header to a portable graymap,
use:

    convert -depth 8 -size 768x512+128   \\
            gray:raw image.pgm

To convert a Photo CD image to a TIFF image, use:

    convert -size 1536x1024 img0009.pcd  \\
            image.tiff
    convert img0009.pcd[4] image.tiff

To create a visual image directory of all your JPEG images, use:

    convert 'vid:*.jpg' directory.miff

To annotate an image with blue text using font 12x24 at position (100,100),
use:

    convert -font helvetica -fill blue    \\
            -draw "text 100,100 Cockatoo" \\
            bird.jpg bird.miff

To tile a 640x480 image with a JPEG texture with bumps use:

    convert -size 640x480 tile:bumps.jpg  \\
            tiled.png

To surround an icon with an ornamental border to use with Mosaic(1), use:

    convert -mattecolor "#697B8F" -frame  \\
            6x6 bird.jpg icon.png

To create a MNG animation from a DNA molecule sequence, use:

    convert -delay 20 dna.* dna.mng
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect until it is explicitly changed by specifying
the option again with a different effect.
.SH PROCESSING ORDER

Options are processed in command line order.  Any option you
specify on the command line remains in effect until it is
explicitly changed by specifying the option again with a
different effect.  Some options only affect the decoding of
images and others only the encoding.
.SH FILES AND FORMATS

By default, the image format is determined by its magic number. To specify
a particular image format, precede the filename with an image format name
and a colon (\fIi.e.\fP\fBps:image\fP) or specify the image type as the
filename suffix

When you specify \fBX\fP as your image type, the filename has special
meaning. It specifies an X window by \fBid, name\fP, or
\fBroot\fP. If
no filename is specified, the window is selected by clicking the mouse
in the desired window.

Specify \fIinput_file\fP as - for standard input,
\fIoutput_file\fP
as - for standard output. If \fIinput_file\fP has the extension
\fB.Z\fP or
\fB.gz\fP, the file is uncompressed with \fBuncompress\fP or \fBgunzip\fP
respectively. If \fIoutput_file\fP has the extension \fB.Z\fP or
\fB.gz\fP,
the file size is compressed using with \fBcompress\fP or \fBgzip\fP
respectively.  Finally, precede the image file name with | to pipe to or
from a system command.

Use an optional index enclosed in brackets after a file name to specify
a desired subimage of a multi-resolution image format like Photo CD (e.g.
img0001.pcd[4]) or a range for MPEG images (e.g. video.mpg[50-75]). A subimage
specification can be disjoint (e.g. image.tiff[2,7,4]). For raw images,
specify a subimage with a geometry (e.g. -size 640x512 image.rgb[320x256+50+50]).
Single images are written with the filename you specify. However, multi-part
images (i.e. a multi-page PostScript document with \fB+adjoin\fP specified)
are written with the filename followed by a period (\fB.\fP) and the scene
number. You can change this behavior by embedding a \fBprintf\fP format
specification in the file name. For example,

    image%02d.miff

converts files image00.miff, image01.miff, etc.

Prepend an at sign @ to a filename to read a list of image
filenames from that file. This is convenient in the event you have too
many image filenames to fit on the command line.
.SH SEGMENTATION

Use \fB-segment\fP to segment an image by analyzing the histograms of
the color components and identifying units that are homogeneous with the
fuzzy c-means technique. The scale-space filter analyzes the histograms
of the three color components of the image and identifies a set of classes.
The extents of each class is used to coarsely segment the image with thresholding.
The color associated with each class is determined by the mean color of
all pixels within the extents of a particular class. Finally, any unclassified
pixels are assigned to the closest class with the fuzzy c-means technique.

The fuzzy c-Means algorithm can be summarized as follows:

    
Build a histogram, one for each color component of the image.
    
For each histogram, successively apply the scale- space filter and build
an interval tree of zero crossings in the second derivative at each scale.
Analyze this scale-space ``fingerprint'' to determine which peaks or valleys
in the histogram are most predominant.
    
The fingerprint defines intervals on the axis of the histogram. Each interval
contains either a minima or a maxima in the original signal. If each color
component lies within the maxima interval, that pixel is considered ``classified''
and is assigned an unique class number.
    
Any pixel that fails to be classified in the above thresholding pass is
classified using the fuzzy c-Means technique. It is assigned to one of
the classes discovered in the histogram analysis phase.


The fuzzy c-Means technique attempts to cluster a pixel by finding the
local minima of the generalized within group sum of squared error objective
function. A pixel is assigned to the closest class of which the fuzzy membership
has a maximum value.

For additional information see:
<bq>\fIYoung Won Lim, Sang Uk Lee\fP, "\fBOn The Color Image Segmentation
Algorithm Based on the Thresholding and the Fuzzy c-Means Techniques\fP",
Pattern Recognition, Volume 23, Number 9, pages 935-952, 1990.</bq>

.SH ENVIRONMENT
.TP
.B "DISPLAY"
\fRTo get the default host, display number, and screen.
.SH SEE ALSO

display(1), animate(1), identify(1), montage(1), mogrify(1),
composite(1)

