.SH NAME

display - display an image on any workstation running X

.SH SYNOPSIS

\fBdisplay\fP \fB[\fP \fIoptions\fP \fB...]\fP \fIfile\fP
\fB[\fP\fIoptions\fP\fB...]\fP\fIfile\fP
.SH DESCRIPTION

Display is a machine architecture independent
image processing and display program. It can display an image on any workstation
screen running an X server. \fBDisplay\fP can read and write
\fBmany\fP
of the more popular image formats (e.g. \fBJPEG\fP,
\fBTIFF\fP,
\fBPNM\fP,
\fBPhoto
CD\fP, etc.).

With \fBdisplay\fP, you can perform these functions on an image:
.in 15

.in 5
o load an image from a file
.in 0
.in 5
o display the next image
.in 0
.in 5
o display the former image
.in 0
.in 5
o display a sequence of images as a slide show
.in 0
.in 5
o write the image to a file
.in 0
.in 5
o print the image to a \fIPostScript\fP printer
.in 0
.in 5
o delete the image file
.in 0
.in 5
o create a Visual Image Directory
.in 0
.in 5
o select the image to display by its thumbnail rather than name
.in 0
.in 5
o undo last image transformation
.in 0
.in 5
o copy a region of the image
.in 0
.in 5
o paste a region to the image
.in 0
.in 5
o restore the image to its original size
.in 0
.in 5
o refresh the image
.in 0
.in 5
o half the image size
.in 0
.in 5
o double the image size
.in 0
.in 5
o resize the image
.in 0
.in 5
o crop the image
.in 0
.in 5
o cut the image
.in 0
.in 5
o flop image in the horizontal direction
.in 0
.in 5
o flip image in the vertical direction
.in 0
.in 5
o rotate the image 90 degrees clockwise
.in 0
.in 5
o rotate the image 90 degrees counter-clockwise
.in 0
.in 5
o rotate the image
.in 0
.in 5
o shear the image
.in 0
.in 5
o roll the image
.in 0
.in 5
o trim the image edges
.in 0
.in 5
o invert the colors of the image
.in 0
.in 5
o vary the color brightness
.in 0
.in 5
o vary the color saturation
.in 0
.in 5
o vary the image hue
.in 0
.in 5
o gamma correct the image
.in 0
.in 5
o sharpen the image contrast
.in 0
.in 5
o dull the image contrast
.in 0
.in 5
o perform histogram equalization on the image
.in 0
.in 5
o perform histogram normalization on the image
.in 0
.in 5
o negate the image colors
.in 0
.in 5
o convert the image to grayscale
.in 0
.in 5
o set the maximum number of unique colors in the image
.in 0
.in 5
o reduce the speckles within an image
.in 0
.in 5
o eliminate peak noise from an image
.in 0
.in 5
o detect edges within the image
.in 0
.in 5
o emboss an image
.in 0
.in 5
o segment the image by color
.in 0
.in 5
o simulate an oil painting
.in 0
.in 5
o simulate a charcoal drawing
.in 0
.in 5
o annotate the image with text
.in 0
.in 5
o draw on the image
.in 0
.in 5
o edit an image pixel color
.in 0
.in 5
o edit the image matte information
.in 0
.in 5
o composite an image with another
.in 0
.in 5
o aball a border to the image
.in 15
.in 5
o aball a border to the image
.in 15
.in 5
o surround image with an ornamental border
.in 0
.in 5
o apply image processing techniques to a region of interest
.in 0
.in 5
o display information about the image
.in 0
.in 5
o zoom a portion of the image
.in 0
.in 5
o show a histogram of the image
.in 0
.in 5
o display image to background of a window
.in 0
.in 5
o set user preferences
.in 0
.in 5
o display information about this program
.in 0
.in 5
o discard all images and exit program
.in 0
.in 5
o change the level of magnification
.in 0
.in 5
o display images specified by a World
Wide Web (WWW) uniform resource locator (URL)
.in 0

.SH EXAMPLES

To scale an image of a cockatoo to exactly 640 pixels in width and 480
pixels in height and position the window at location (200,200), use:

    display -geometry 640x480+200+200! cockatoo.miff

To display an image of a cockatoo without a border centered on a backdrop,
use:

    display +borderwidth -backdrop cockatoo.miff

To tile a slate texture onto the root window, use:

    display -size 1280x1024 -window root slate.png

To display a visual image directory of all your JPEG images, use:

    display 'vid:*.jpg'

To display a MAP image that is 640 pixels in width and 480 pixels in height
with 256 colors, use:

    display -size 640x480+256 cockatoo.map

To display an image of a cockatoo specified with a \fBWorld Wide Web (WWW)\fP
uniform resource locator \fB(URL)\fP, use:

    display ftp://wizards.dupont.com/images/cockatoo.jpg

To display histogram of an image, use:

    convert file.jpg HISTOGRAM:- | display -
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect until it is explicitly changed by specifying
the option again with a different effect. For example to display two images,
the first with 32 colors, and the second with only 16 colors, use:

      display -colors 32 cockatoo.miff -colors 16 macaw.miff

\fBDisplay\fP options can appear on the command line or in your X resources
file. See \fIX(1)\fP. Options on the command line supersede values specified
in your X resources file.
.TP
.B "-backdrop \fIcolor\fP
\fRdisplay the image centered on a backdrop.

This backdrop covers the entire workstation screen and is useful for hiding
other X window activity while viewing the image. The color of the backdrop
is specified as the background color. Refer to X Resources
for details.

.TP
.B "-background \fIcolor\fP
\fRthe background color
.TP
.B "-border \fI<width>x<height>\fP
\fRsurround the image with a border of color

See \fIX(1)\fP for details
about the geometry specification.

.TP
.B "-bordercolor \fIcolor\fP
\fRthe border color
.TP
.B "-borderwidth \fIcolor\fP
\fRthe border width
.TP
.B "-cache \fIthreshold\fP
\fRmegabytes of memory available to the pixel cache

Image pixels are stored in memory until 80 megabytes of memory have been
consumed. Subsequent pixel operations are cached on disk. Operations to
memory are significantly faster but if your computer does not have a sufficient
amount of free memory you may want to adjust this threshold value.

.TP
.B "-colormap \fItype\fP
\fRdefine the colormap type

Choose between \fBshared\fP or \fBprivate\fP.


This option only applies when the default X server visual is \fIPseudoColor\fP
or \fIGRAYScale\fP. Refer to \fB-visual\fP for more details. By default,
a shared colormap is allocated. The image shares colors with other X clients.
Some image colors could be approximated, therefore your image may look
very different than intended. Choose \fBPrivate\fP and the image colors
appear exactly as they are defined. However, other clients may
go \fItechnicolor\fP when the image colormap is installed.
.TP
.B "-colors \fIvalue\fP
\fRpreferred number of colors in the image

The actual number of colors in the image may be less than your request,
but never more. Note, this is a color reduction option. Images with less
unique colors than specified with this option will have any duplicate or
unused colors removed. Refer to quantize for
more details.


Note, options \fB-dither\fP, \fB-colorspace\fP, and \fB-treedepth\fP
affect the color reduction algorithm.

.TP
.B "-colorspace \fIvalue\fP
\fRthe type of colorspace

Choices are: \fBGRAY\fP, \fBOHTA\fP, \fBRGB\fP,
\fBTransparent\fP,
\fBXYZ\fP,
\fBYCbCr\fP, \fBYIQ\fP, \fBYPbPr\fP,
\fBYUV\fP, or \fBCMYK\fP.


Color reduction, by default, takes place in the RGB color space. Empirical
evidence suggests that distances in color spaces such as YUV or YIQ correspond
to perceptual color differences more closely than do distances in RGB space.
These color spaces may give better results when color reducing an image.
Refer to quantize for more details.


The \fBTransparent\fP color space behaves uniquely in that it preserves
the matte channel of the image if it exists.


The \fB-colors\fP or \fB-monochrome\fP option is required for this
option to take effect.

.TP
.B "-comment \fIstring\fP
\fRannotate an image with a comment

Use this option to assign a specific comment to the image. You can include the
image filename, type, width, height, or other image attribute by embedding
special format characters:


     %b   file size
     %c   comment
     %d   directory
     %e   filename extention
     %f   filename
     %h   height
     %i   input filename
     %k   number of unique colors
     %l   label
     %m   magick
     %n   number of scenes
     %o   output filename
     %p   page number
     %q   quantum depth
     %s   scene number
     %t   top of filename
     %u   unique temporary filename
     %w   width
     %x   x resolution
     %y   y resolution
     \\n   newline
     \\r   carriage return

For example,


     -comment "%m:%f %wx%h"

produces an image comment of \fBMIFF:bird.miff 512x480\fP for an image
titled \fBbird.miff\fP and whose width is 512 and height is 480.


If the first character of \fIstring\fP is \fI@\fP, the image comment
is read from a file titled by the remaining characters in the string.

.TP
.B "-compress \fItype\fP
\fRthe type of image compression

Choices are: \fINone\fP, \fIBZip\fP, \fIFax\fP,
\fIGroup4\fP,
\fIJPEG\fP,
\fILZW\fP, \fIRLE\fP or \fIZip\fP.


Specify \fB+compress\fP to store the binary image in an uncompressed format.
The default is the compression type of the specified image file.

.TP
.B "-contrast"
\fRenhance or reduce the image contrast

This option enhances the intensity differences between the lighter and
darker elements of the image. Use \fB-contrast\fP to enhance
the image
or \fB+contrast\fP to reduce the image contrast.

.TP
.B "-crop \fI<width>x<height>{+-}<x offset>{+-}<y offset>{%}\fP
\fRpreferred size and location of the cropped image

See \fIX(1)\fP for details
about the geometry specification.


The width and height give the size of the image that remains after cropping,
and the offsets give the location of the top left corner of the cropped
image with respect to the original image.  To specify the amount to be
removed, use \fB-shave\fP instead.


To specify a percentage width or height to be removed instead, append
\fB%\fP. For example
to crop the image by ten percent (five percent on each side of the image),
use \fB-crop 10%\fP.


Use cropping to apply image processing options to, or display, a particular
area of an image.


Omit the x and y offset to generate one or more subimages of a uniform
size.


Use cropping to crop a particular area of an image. Use \fB-crop 0x0\fP
to trim edges that are the background color. Add an x and y offset to leave
a portion of the trimmed edges with the image.

.TP
.B "-debug"
\fRenable debug printout
.TP
.B "-delay \fI<1/100ths of a second>\fP
\fRdisplay the next image after pausing

This option is useful for regulating the animation of GIF images
within Netscape. \fIDelay/100\fP seconds must expire
before the display
of the next image. The default is no delay between each showing of the
image sequence. The maximum delay is 65535.


You can specify a delay range (e.g. \fI-delay 10-500\fP) which sets the
minimum and maximum delay.

.TP
.B "-density \fI<width>x<height>\fP
\fRvertical and horizontal resolution in pixels of the image

This option specifies an image density when decoding a \fIPostScript\fP
or Portable Document page. The default is 72 dots per inch in the horizontal
and vertical direction. This option is used in concert with \fB-page\fP.

.TP
.B "-depth \fIvalue\fP
\fRdepth of the image

This is the number of bits in a pixel. The only acceptable
values are 8 or 16.  Use this option to specify the depth of raw images whose
depth is unknown such as GRAY, RGB, or CMYK, or to change the depth of any
image after it has been read.

.TP
.B "-despeckle"
\fRreduce the speckles within an image
.TP
.B "-display \fIhost:display[.screen]\fP
\fRspecifies the X server to contact
.TP
.B "-dispose \fImethod\fP
\fRGIF disposal method

Here are the valid methods:


     0     No disposal specified.
     1     Do not dispose between frames.      
     2     Overwrite frame with background color from header.
     3     Overwrite with previous frame.
.TP
.B "-dither"
\fRapply Floyd/Steinberg error diffusion to the image

The basic strategy of dithering is to trade intensity resolution for spatial
resolution by averaging the intensities of several neighboring pixels.
Images which suffer from severe contouring when reducing colors can be
improved with this option.


The \fB-colors\fP or \fB-monochrome\fP option is required for this option
to take effect.


Use \fB+dither\fP to render Postscript without text or graphic aliasing.

.TP
.B "-edge \fIorder\fP
\fRdetect edges within an image

Good order values are odd numbers from 3 to 31.

.TP
.B "-enhance"
\fRapply a digital filter to enhance a noisy image
.TP
.B "-filter \fItype\fP
\fRuse this type of filter when resizing an image

Use this option to affect the resizing operation of an image (see
\fB-geometry\fP).
Choose from these filters:


     Point
     Box
     Triangle
     Hermite
     Hanning
     Hamming
     Blackman
     Gaussian
     Quadratic
     Cubic
     Catrom
     Mitchell
     Lanczos
     Bessel
     Sinc

The default filter is \fBLanczos\fP

.TP
.B "-flip"
\fRcreate a "mirror image"

reflect the scanlines in the vertical direction.

.TP
.B "-flop"
\fRcreate a "mirror image"

reflect the scanlines in the horizontal direction.

.TP
.B "-font \fIname\fP
\fRuse this font when annotating the image with text

You can tag a font to specify whether it is a Postscript, Truetype, or OPTION1
font.  For example, Arial.ttf is a Truetype font, ps:helvetica
is Postscript, and x:fixed is OPTION1. 

.TP
.B "-foreground \fIcolor\fP
\fRdefine the foreground color
.TP
.B "-frame
<width>x<height>+<outer bevel width>+<inner bevel width>"
\fRsurround the image with an ornamental border

See \fIX(1)\fP for details
about the geometry specification.


The color of the border is specified with the
\fB-mattecolor\fP command
line option.

.TP
.B "-gamma \fIvalue\fP
\fRlevel of gamma correction

The same color image displayed on two different workstations may look different
due to differences in the display monitor. Use gamma correction to adjust
for this color difference. Reasonable values extend from \fB0.8\fP to
\fB2.3\fP.


You can apply separate gamma values to the red, green, and blue channels
of the image with a gamma value list delineated with slashes
(i.e. \fB1.7\fP/\fB2.3\fP/\fB1.2\fP).


Use \fB+gamma\fP \fIvalue\fP
to set the image gamma level without actually adjusting
the image pixels. This option is useful if the image is of a known gamma
but not set as an image attribute (e.g. PNG images).

.TP
.B "-geometry \fI<width>x<height>{+-}<x offset>{+-}<y offset>{%}{@}{!}{<}{>}\fP
\fRpreferred size and location of the Image window.

See \fIX(1)\fP for details
about the geometry specification. By default, the window size is the image
size and the location is chosen by you when it is mapped.


By default, the width and height are maximum values. That is, the image
is expanded or contracted to fit the width and height value while maintaining
the aspect ratio of the image. \fIAppend an exclamation point to the geometry
to force the image size to exactly the size you specify\fP. For example,
if you specify \fB640x480!\fP the image width is set to 640 pixels and
height to 480. If only one factor is specified, both the width and height
assume the value.


To specify a percentage width or height instead, append %. The image size
is multiplied by the width and height percentages to obtain the final image
dimensions. To increase the size of an image, use a value greater than
100 (e.g. 125%). To decrease an image's size, use a percentage less than
100.


Use \fB@\fP to specify the maximum area in pixels of an image.


Use \fB>\fP to change the dimensions of the image \fIonly\fP if
its size exceeds the geometry specification. \fB<\fP resizes the image
\fIonly\fP
if its dimensions is less than the geometry specification. For example,
if you specify \fB'640x480>'\fP and the image size is 512x512, the image
size does not change. However, if the image is 1024x1024, it is resized
to 640x480.


Use \fB<\fP to change the dimensions of the image \fIonly\fP if
its size exceeds the geometry specification. \fB>\fP resizes the image
\fIonly\fP
if its dimensions is less than the geometry specification. For example,
if you specify \fB640x480>\fP and the image size is 512x512, the image
size does not change. However, if the image is 1024x1024, it is resized
to 640x480.


There are 72 pixels per inch in PostScript coordinates.

.TP
.B "-help"
\fRprint usage instructions
.TP
.B "-iconGeometry \fIgeometry\fP
\fRspecify the icon geometry
.TP
.B "-iconic"
\fRiconic animation
.TP
.B "-immutable"
\fRmake image immutable
.TP
.B "-interlace \fItype\fP
\fRthe type of interlacing scheme

Choices are: \fBNone, Line, Plane,\fP
or \fBPartition\fP. The default is \fBNone\fP.


This option is used to specify the type of interlacing scheme for raw image
formats such as \fBRGB\fP or \fBYUV\fP. \fBNone\fP means do not interlace
(RGBRGBRGBRGBRGBRGB...), \fBLine\fP uses scanline interlacing
(RRR...GGG...BBB...RRR...GGG...BBB...),
and \fBPlane\fP uses plane interlacing (RRRRRR...GGGGGG...BBBBBB...).
\fBPartition\fP
is like plane except the different planes are saved to individual files
(e.g. image.R, image.G, and image.B).


Use \fBLine\fP, or \fBPlane\fP to create an
\fBinterlaced PNG\fP or \fB GIF\fP or
\fBprogressive JPEG\fP image.

.TP
.B "-label \fIname\fP
\fRassign a label to an image

Use this option to assign a specific label to the image. Optionally you
can include the image filename, type, width, height, or other image attribute
by embedding special format character. See \fB-comment\fP for details.


For example,


     -label "%m:%f %wx%h"

produces an image label of \fBMIFF:bird.miff 512x480\fP for an image titled
\fBbird.miff\fP
and whose width is 512 and height is 480.


If the first character of \fIstring\fP is \fI@\fP, the image label is
read from a file titled by the remaining characters in the string.


When converting to \fIPostScript\fP, use this option to specify a header
string to print above the image. Specify the label font with
\fB-font\fP.

.TP
.B "-magnify \fIfactor\fP
\fRmagnify the image
.TP
.B "-map \fItype\fP
\fR
display image using this type.
[animate or display]

Choose from these \fIStandard Colormap\fP types:

     best
     default
     gray
     red
     green
     blue

The \fIX server\fP must support the \fIStandard Colormap\fP you choose,
otherwise an error occurs. Use \fBlist\fP as the type and \fBdisplay\fP
searches the list of colormap types in \fBtop-to-bottom\fP order until
one is located. See \fIxstdcmap(1)\fP for one way of creating Standard
Colormaps.
.TP
.B "-matte"
\fRstore matte channel if the image has one

If the image does not have a matte channel, create an opaque one.

.TP
.B "-mattecolor \fIcolor\fP
\fRspecify the matte color
.TP
.B "-monochrome"
\fRtransform the image to black and white
.TP
.B "-name"
\fRname an image
.TP
.B "-negate"
\fRreplace every pixel with its complementary color

The red, green, and blue intensities of an image are negated.
White becomes black,
yellow becomes blue, etc.
Use \fB+negate\fP
to only negate the grayscale pixels of the image.

.TP
.B "-page \fI<width>x<height>{+-}<x offset>{+-}<y offset>{%}{!}{<}{>}\fP
\fRsize and location of an image canvas

Use this option to specify the dimensions of the
\fIPostScript\fP page
in dots per inch or a TEXT page in pixels. The choices for a Postscript
page are:


     11x17         792  1224 
     Ledger       1224   792    
     Legal         612  1008
     Letter        612   792
     LetterSmall   612   792
     ArchE        2592  3456
     ArchD        1728  2592
     ArchC        1296  1728
     ArchB         864  1296
     ArchA         648   864
     A0           2380  3368
     A1           1684  2380
     A2           1190  1684
     A3            842  1190
     A4            595   842
     A4Small       595   842
     A5            421   595
     A6            297   421
     A7            210   297
     A8            148   210
     A9            105   148
     A10            74   105
     B0           2836  4008
     B1           2004  2836
     B2           1418  2004
     B3           1002  1418
     B4            709  1002
     B5            501   709
     C0           2600  3677
     C1           1837  2600
     C2           1298  1837
     C3            918  1298
     C4            649   918
     C5            459   649
     C6            323   459
     Flsa          612   936 
     Flse          612   936
     HalfLetter    396   612

For convenience you can specify the page size by media (e.g. A4, Ledger,
etc.). Otherwise, \fB-page\fP behaves much like
\fB-geometry\fP (e.g.
-page
letter+43+43>).


To position a GIF image, use \fB-page\fP\fI{+-}<x offset>{+-}<y
offset>\fP (e.g. -page +100+200).


For a Postscript page, the image is sized as in \fB-geometry\fP and positioned
relative to the lower left hand corner of the page by
{+-}<\fBx\fP\fIoffset\fP>{+-}<\fBy\fP
\fIoffset>\fP. Use
-page 612x792>, for example, to center the
image within the page. If the image size exceeds the Postscript page, it
is reduced to fit the page.


The default page dimensions for a TEXT image is 612x792.


This option is used in concert with \fB-density\fP.

.TP
.B "-quality \fIvalue\fP
\fRJPEG/MIFF/PNG compression level

For the JPEG image format, quality is 0 (worst) to 100 (best). The default
quality is 75.


Quality for the MIFF and PNG image format sets the amount of image compression
(quality / 10) and filter-type (quality % 10). Compression quality values
range from 0 (worst) to 100 (best). If filter-type is 4 or less, the specified
filter-type is used for all scanlines:


     0: none
     1: sub
     2: up
     3: average
     4: Paeth

If filter-type is 5, adaptive filtering is used when quality is greater
than 50 and the image does not have a color map, otherwise no filtering
is used.


If filter-type is 6 or more, adaptive filtering with \fIminimum-sum-of-absolute-values\fP
is used.


The default is quality is 75. Which means nearly the best compression with
adaptive filtering.


For further information, see the PNG
specification.

.TP
.B "-raise \fI<width>x<height>\fP
\fRlighten or darken image edges

This will create a 3-D effect. See \fIX(1)\fP for
details about the geometry specification.


Use \fB-raise\fP to create a raised effect, otherwise use \fB+raise\fP.

.TP
.B "-remote"
\fRperform a remote operation

The only command recognized at this time is the name of
an image file to load.

.TP
.B "-roll \fI{+-}<x offset>{+-}<y offset>\fP
\fRroll an image vertically or horizontally

See \fIX(1)\fP for details about
the geometry specification.


A negative \fIx offset\fP rolls the image left-to-right. A negative \fIy
offset\fP rolls the image top-to-bottom.

.TP
.B "-rotate \fIdegrees{<}{>}\fP
\fRapply Paeth image rotation to the image

Use > to rotate the image only if its width exceeds the height.
< rotates the image \fIonly\fP if its width is less than the
height. For example, if you specify -90> and the image size is
480x640, the image is not rotated by the specified angle. However, if the
image is 640x480, it is rotated by -90 degrees.


Empty triangles left over from rotating the image are filled with the color
defined as \fBbackground\fP (class \fBbackgroundColor\fP). See \fIX(1)\fP
for details.

.TP
.B "-sample \fIgeometry\fP
\fRscale image with pixel sampling

See \fB-geometry\fP for details about
the geometry specification.

.TP
.B "-scene \fIvalue{-value}\fP
\fRimage scene number or range

Use this option to specify an image sequence with a single filename. See
the discussion of \fIfile\fP below for details.
.TP
.B "-segment \fI<cluster threshold>x<smoothing threshold>\fP
\fRsegment an image

Segment an image by analyzing the histograms of the color components and
identifying units that are homogeneous with the fuzzy c-means technique.


Specify \fIcluster threshold\fP as the number of pixels in each cluster
must exceed the the cluster threshold to be considered valid. \fISmoothing
threshold\fP eliminates noise in the second derivative of the histogram.
As the value is increased, you can expect a smoother second derivative.
The default is 1.5. See Image Segmentation for details.

.TP
.B "-shared_memory"
\fRuse shared memory

This resource specifies whether the utility should attempt use shared memory
for pixmaps.  ImageMagick must be compiled with shared memory support,
and the display must support the \fIMIT-SHM\fP extension.  Otherwise, this
resource is ignored.  The default is \fBTrue\fP.

.TP
.B "-sharpen \fI<radius>x<sigma>\fP
\fRsharpen the image

Use a gaussian operator of the given radius and
standard deviation (sigma). 

.TP
.B "-size \fI<width>x<height>{+offset}\fP
\fRwidth and height of the image

Use this option to specify the width and height of raw images whose dimensions
are unknown such as \fBGRAY\fP,
\fBRGB\fP, or \fBCMYK\fP. In addition
to width and height, use
\fB-size\fP with an offset to skip any header information in
the image or tell the number of colors in a \fBMAP\fP image
file, (e.g. -size 640x512+256).


For Photo CD images, choose from these sizes:

     192x128
     384x256
     768x512
     1536x1024
     3072x2048

Finally, use this option to choose a particular resolution layer of a JBIG
or JPEG image (e.g. -size 1024x768).

.TP
.B "-text_font \fIname\fP
\fRfont for writing fixed-width text

Specifies the name of the preferred font to use in fixed (typewriter style)
formatted text.  The default is 14 point \fICourier\fP.


You can tag a font to specify whether it is a Postscript, Truetype, or
OPTION1 font.  For example, Courier.ttf is a Truetype font
and x:fixed is OPTION1. 

.TP
.B "-texture \fIfilename\fP
\fRname of texture to tile onto the image background
.TP
.B "-title \fI\"string\"\fP
\fRassign a title to the displayed image

Use this option to assign a specific title to the image. This is assigned
to the image window and is typically displayed in the window title bar.
Optionally you can include the image filename, type, width, height, or
other image attribute by embedding special format characters:

     %b file size
     %c comment
     %d directory
     %e filename extention
     %f filename
     %h height
     %i input filename
     %k number of unique colors
     %l label
     %m magick
     %n number of scenes
     %o output filename
     %p page number
     %q quantum depth
     %s scene number
     %t top of filename
     %u unique temporary filename
     %w width
     %x x resolution
     %y y resolution
     \\n newline
     \\r carriage return

For example,


     -title "%m:%f %wx%h"

produces an image title of MIFF:bird.miff 512x480 for an image
titled bird.miff and whose width is 512 and height is 480.

.TP
.B "-treedepth \fIvalue\fP
\fRtree depth for the color reduction algorithm

Normally, this integer value is zero or one. A zero or one tells display
to choose an optimal tree depth for the color reduction algorithm

An optimal depth generally allows the best representation of the source
image with the fastest computational speed and the least amount of memory.
However, the default depth is inappropriate for some images. To assure
the best representation, try values between 2 and 8 for this parameter.
Refer to
quantize for more details.


The \fB-colors\fP or \fB-monochrome\fP option is required for this option
to take effect.

.TP
.B "-update \fIseconds\fP
\fR
detect when image file is modified and redisplay.

Suppose that while you are displaying an image the file that is currently
displayed is over-written.
\fBdisplay\fP will automatically detect that
the input file has been changed and update the displayed image accordingly.

.TP
.B "-use_pixmap"
\fRuse the pixmap
.TP
.B "-verbose"
\fRprint detailed information about the image

This information is printed: image scene number; image name; image size;
the image class (\fIDirectClass\fP or \fIPseudoClass\fP); the total number
of unique colors; and the number of seconds to read and transform the image.
Refer to miff for a description of the image class.


If \fB-colors\fP is also specified, the total unique colors in the image
and color reduction error values are printed. Refer to quantize
for a description of these values.

.TP
.B "-visual \fItype\fP
\fRanimate images using this X visual type

Choose from these visual classes:


     StaticGray
     GrayScale
     StaticColor
     PseudoColor
     TrueColor
     DirectColor
     default
     visual id

The X server must support the visual you choose, otherwise an error occurs.
If a visual is not specified, the visual class that can display the most
simultaneous colors on the default screen is chosen.

.TP
.B "-window \fIid\fP
\fRmake image the background of a window

\fIid\fP can be a window id or name.  Specify \fBroot\fP to
select X's root window as the target window.


By default the image is tiled onto the background of the target
window.   If \fBbackdrop\fP or \fB-geometry\fP are
specified, the image is surrounded by the background color.  Refer to
\fBX RESOURCES\fP for details.


The image will not display on the root window if the image has more
unique colors than the target window colormap allows.  Use
\fB-colors\fP to reduce the number of colors.

.TP
.B "-window_group"
\fRspecify the window group
.TP
.B "-write"
\fRwrite the image to a file

If \fIfile\fP already exists, you will be prompted as to whether it should
be overwritten.

By default, the image is written in the format that it was read in as.
To specify a particular image format, prefix \fIfile\fP with the image
type and a colon (i.e. ps:image) or specify the image type as the filename
suffix (i.e. image.ps). See convert(1) for a list of valid image formats.
Specify file as - for standard output. If file has the
extension \fB.Z\fP or
\fB.gz\fP, the file size is \fBcompressed\fP using with compress or
\fBgzip\fP
respectively. Precede the image file name with | to pipe to a system command.
If \fIfile\fP already exists, you will be prompted as to whether it should
be overwritten.
Use \fB-compress\fP to specify the type of image compression.

The equivalent X resource for this option is
\fBwriteFilename\fP (class \fBWriteFilename\fP).
See X Resources for details.
.SH COPYRIGHT
Copyright (C) 2002 ImageMagick Studio, a non-profit organization dedicated
to making software imaging solutions freely available.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the
ImageMagick is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of ImageMagick.

The software is provided "as is", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.  In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out of
or in connection with ImageMagick or the use or other dealings in
ImageMagick.

Except as contained in this notice, the name of the ImageMagick Studio
shall not be used in advertising or otherwise to promote the sale, use or
other dealings in ImageMagick without prior written authorization from the
ImageMagick Studio.
.SH AUTHORS
John Cristy, ImageMagick Studio LLC

