.TH identify 1 "Date: 2002/01/01 01:00:00" "ImageMagick"
.SH NAME
identify - describe an image or image sequence.
.SH SYNOPSIS

\fBidentify\fP \fIfile\fP [ \fIfile\fP ... ]

.SH DESCRIPTION

\fBIdentify\fP describes the format and characteristics of one or more
image files. It will also report if an image is incomplete or corrupt.
The information displayed includes the scene number, the file name, the
width and height of the image, whether the image is colormapped or not,
the number of colors in the image, the number of bytes in the image, the
format of the image (JPEG, PNM, etc.), and finally the number of seconds
it took to read and process the image. An example line output
from \fBidentify\fP follows:

    images/aquarium.miff 640x480 PseudoClass 256c 308135b MIFF 1s

If -verbose is set, expect additional output including any image
comment:


    Image: images/aquarium.miff
    class: PseudoClass
    colors: 256
    signature: eb5dca81dd93ae7e6ffae99a527eb5dca81dd93ae7e6ffae99a5275a53e
    matte: False
    geometry: 640x480
       depth: 8
    bytes: 308135
    format: MIFF
    comments:
    Imported from MTV raster image: aquarium.mtv
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect until it is explicitly changed by specifying
the option again with a different effect.
.SH SEE ALSO

display(1), animate(1), montage(1), mogrify(1),  convert(1),
composite(1)

