.TH ImageMagick 1 "Date: 2002/02/15 01:00:00" "ImageMagick"
.TP
.in 15
.in 15
.in 20
.SH NAME

ImageMagick - commandline utilities to create, edit, or convert images

.SH SYNOPSIS

\fBanimate\fP \fB[\fP \fIoptions ...\fP \fB]\fP \fIfile\fP \fB[ [\fP
\fIoptions ...\fP \fB]\fP \fIfile ...\fP \fB]\fP


\fBcomposite\fP \fB[\fP \fIoptions ...\fP \fB]\fP \fIimage composite\fP
\fB[\fP \fImask\fP \fB]\fP \fIcomposited\fP


\fBconjure\fP \fB[\fP \fIoptions ...\fP \fB]\fP \fIscript.msl\fP
\fIimagefiles\fP


\fBconvert\fP \fB[ [\fP \fIoptions ...\fP \fB] [\fP \fIinput_file ...\fP
\fB]\fP \fI...\fP \fB[\fP \fIoutput_file\fP \fB] ]\fP


\fBdisplay\fP \fB[\fP \fIoptions ...\fP \fB]\fP \fIfile ...\fP
\fB[ [\fP\fIoptions ...\fP \fB]\fP\fIfile ...\fP \fB]\fP


\fBidentify\fP \fIfile\fP \fB[\fP \fIfile ...\fP \fB]\fP


\fBimport\fP \fB[\fP \fIoptions ...\fP \fB]\fP \fIfile\fP


\fBmogrify\fP \fB[\fP \fIoptions ...\fP \fB]\fP \fIfile ...\fP


\fBmontage\fP \fB[\fP \fIoptions ...\fP \fB]\fP \fIfile\fP \fB[ [\fP
\fIoptions ...\fP \fB]\fP \fIfile ...\fP \fB]\fP \fIoutput_file\fP

.SH DESCRIPTION

\fBImageMagick\fP provides a suite of commandline utilities for creating,
converting, editing, and displaying images:

\fBDisplay\fP
is a machine architecture independent
image processing and display program. It can display an image on any workstation
display running an \fIX\fP server.

\fBImport\fP
reads an image from any visible window
on an \fIX\fP server and outputs it as an image file. You can capture
a single window, the entire screen, or any rectangular portion of the screen.

\fBMontage\fP
creates a composite by combining several
separate images. The images are tiled on the composite image with the name
of the image optionally appearing just below the individual tile.

\fBConvert\fP
converts an input file using one image
format to an output file with a differing image format.

\fBMogrify\fP
transforms an image or a sequence of
images. These transforms include \fBimage scaling\fP, \fBimage rotation\fP,
\fBcolor
reduction\fP, and others. The transmogrified image
\fBoverwrites\fP the
original image.

\fBIdentify\fP
describes the format and characteristics
of one or more image files. It will also report if an image is incomplete
or corrupt.

\fBComposite\fP
composites images to create new images.

\fBConjure\fP
interprets and executes scripts in
the Magick Scripting Language (MSL).

The \fBImageMagick\fP utilities recognize the following image formats:


\fBName\fP   \fBMode\fP \fBDescription\fP
 o  8BIM      *rw- Photoshop resource format
 o  AFM       *r-- TrueType font
 o  APP1      *rw- Photoshop resource format
 o  ART       *r-- PF1: 1st Publisher
 o  AVI       *r-- Audio/Visual Interleaved
 o  AVS       *rw+ AVS X image
 o  BIE       *rw- Joint Bi-level Image experts Group
                   interchange format
 o  BMP       *rw+ Microsoft Windows bitmap image
 o  CAPTION   *r+  Caption (requires separate size info)
 o  CMYK      *rw- Raw cyan, magenta, yellow, and black
                   samples (8 or 16 bits, depending on
                   the image depth)
 o  CMYKA     *rw- Raw cyan, magenta, yellow, black, and
                   matte samples (8 or 16 bits, depending
                   on the image depth)
 o  CUT       *r-- DR Hallo
 o  DCM       *r-- Digital Imaging and Communications in
                    Medicine image
 o  DCX       *rw+ ZSoft IBM PC multi-page Paintbrush
 o  DIB       *rw+ Microsoft Windows bitmap image
 o  DPS       *r-- Display Postscript
 o  DPX       *r-- Digital Moving Picture Exchange
 o  EPDF      *rw- Encapsulated Portable Document Format
 o  EPI       *rw- Adobe Encapsulated PostScript
                   Interchange format
 o  EPS       *rw- Adobe Encapsulated PostScript
 o  EPS2      *-w- Adobe Level II Encapsulated PostScript
 o  EPS3      *-w- Adobe Level III Encapsulated PostScript
 o  EPSF      *rw- Adobe Encapsulated PostScript
 o  EPSI      *rw- Adobe Encapsulated PostScript
                   Interchange format
 o  EPT       *rw- Adobe Encapsulated PostScript with TIFF
                   preview
 o  FAX       *rw+ Group 3 FAX
 o  FILE      *r-- Uniform Resource Locator
 o  FITS      *rw- Flexible Image Transport System
 o  FPX       *rw- FlashPix Format
 o  FTP       *r-- Uniform Resource Locator
 o  G3        *rw- Group 3 FAX
 o  GIF       *rw+ CompuServe graphics interchange format
 o  GIF87     *rw- CompuServe graphics interchange format
                   (version 87a)
 o  GRADIENT  *r-- Gradual passing from one shade to
                   another
 o  GRANITE   *r-- Granite texture
 o  GRAY      *rw+ Raw gray samples (8 or 16 bits,
                   depending on the image depth)
 o  H         *rw- Internal format
 o  HDF       -rw+ Hierarchical Data Format
 o  HISTOGRAM *-w- Histogram of the image
 o  HTM       *-w- Hypertext Markup Language and a
                   client-side image map
 o  HTML      *-w- Hypertext Markup Language and a
                   client-side image map
 o  HTTP      *r-- Uniform Resource Locator
 o  ICB       *rw+ Truevision Targa image
 o  ICM       *rw- ICC Color Profile
 o  ICO       *r-- Microsoft icon
 o  ICON      *r-- Microsoft icon
 o  IMPLICIT  *--- 
 o  IPTC      *rw- IPTC Newsphoto
 o  JBG       *rw+ Joint Bi-level Image experts Group
                   interchange format
 o  JBIG      *rw+ Joint Bi-level Image experts Group
                   interchange format
 o  JP2       *rw- JPEG-2000 JP2 File Format Syntax
 o  JPC       *rw- JPEG-2000 Code Stream Syntax
 o  JPEG      *rw- Joint Photographic Experts Group
                   JFIF format
 o  JPG       *rw- Joint Photographic Experts Group
                   JFIF format
 o  LABEL     *r-- Text image format
 o  LOGO      *rw- ImageMagick Logo
 o  M2V       *rw+ MPEG-2 Video Stream
 o  MAP       *rw- Colormap intensities (8 or 16 bits,
                   depending on the image depth) and
                   indices (8 or 16 bits, depending
                   on whether colors exceeds 256).
 o  MAT       *-w+ MATLAB image format
 o  MATTE     *-w+ MATTE format
 o  MIFF      *rw+ Magick image format
 o  MNG       *rw+ Multiple-image Network Graphics
 o  MONO      *rw- Bi-level bitmap in least-significant-
                   -byte-first order
 o  MPC       -rw- Magick Persistent Cache image format
 o  MPEG      *rw+ MPEG-1 Video Stream
 o  MPG       *rw+ MPEG-1 Video Stream
 o  MPR       *r-- Magick Persistent Registry
 o  MSL       *r-- Magick Scripting Language
 o  MTV       *rw+ MTV Raytracing image format
 o  MVG       *rw- Magick Vector Graphics
 o  NETSCAPE  *r-- Netscape 216 color cube
 o  NULL      *r-- Constant image of uniform color
 o  OTB       *rw- On-the-air bitmap
 o  P7        *rw+ Xv thumbnail format
 o  PAL       *rw- 16bit/pixel interleaved YUV
 o  PALM      *rw- Palm Pixmap format
 o  PBM       *rw+ Portable bitmap format (black and white)
 o  PCD       *rw- Photo CD
 o  PCDS      *rw- Photo CD
 o  PCL       *-w- Page Control Language
 o  PCT       *rw- Apple Macintosh QuickDraw/PICT
 o  PCX       *rw- ZSoft IBM PC Paintbrush
 o  PDB       *r-- Pilot Image Format
 o  PDF       *rw+ Portable Document Format
 o  PFA       *r-- TrueType font
 o  PFB       *r-- TrueType font
 o  PFM       *r-- TrueType font
 o  PGM       *rw+ Portable graymap format (gray scale)
 o  PICON     *rw- Personal Icon
 o  PICT      *rw- Apple Macintosh QuickDraw/PICT
 o  PIX       *r-- Alias/Wavefront RLE image format
 o  PLASMA    *r-- Plasma fractal image
 o  PM        *rw- X Windows system pixmap (color)
 o  PNG       *rw- Portable Network Graphics
 o  PNM       *rw+ Portable anymap
 o  PPM       *rw+ Portable pixmap format (color)
 o  PREVIEW   *-w- Show a preview an image enhancement,
                   effect, or f/x
 o  PS        *rw+ Adobe PostScript
 o  PS2       *-w+ Adobe Level II PostScript
 o  PS3       *-w+ Adobe Level III PostScript
 o  PSD       *rw- Adobe Photoshop bitmap
 o  PTIF      *rw- Pyramid encoded TIFF
 o  PWP       *r-- Seattle Film Works
 o  RAS       *rw+ SUN Rasterfile
 o  RGB       *rw+ Raw red, green, and blue samples (8 or
                   16 bits, depending on the image depth)
 o  RGBA      *rw+ Raw red, green, blue, and matte samples
                   (8 or 16 bits, depending on the image
                   depth)
 o  RLA       *r-- Alias/Wavefront image
 o  RLE       *r-- Utah Run length encoded image
 o  ROSE      *rw- 70x46 Truecolor test image
 o  SCT       *r-- Scitex HandShake
 o  SFW       *r-- Seattle Film Works
 o  SGI       *rw+ Irix RGB image
 o  SHTML     *-w- Hypertext Markup Language and a
                   client-side image map
 o  STEGANO   *r-- Steganographic image
 o  SUN       *rw+ SUN Rasterfile
 o  SVG       *rw+ Scalable Vector Gaphics
 o  TEXT      *rw+ Raw text
 o  TGA       *rw+ Truevision Targa image
 o  TIF       *rw+ Tagged Image File Format
 o  TIFF      *rw+ Tagged Image File Format
 o  TILE      *r-- Tile image with a texture
 o  TIM       *r-- PSX TIM
 o  TTF       *r-- TrueType font
 o  TXT       *rw+ Raw text
 o  UIL       *-w- X-Motif UIL table
 o  UYVY      *rw- 16bit/pixel interleaved YUV
 o  VDA       *rw+ Truevision Targa image
 o  VICAR     *rw- VICAR rasterfile format
 o  VID       *rw+ Visual Image Directory
 o  VIFF      *rw+ Khoros Visualization image
 o  VST       *rw+ Truevision Targa image
 o  WBMP      *rw- Wireless Bitmap (level 0) image
 o  WMF       *r-- Windows Metafile
 o  WPG       *r-- Word Perfect Graphics
 o  X         *rw- X Image
 o  XBM       *rw- X Windows system bitmap (black
                   and white)
 o  XC        *r-- Constant image uniform color
 o  XCF       *r-- GIMP image
 o  XML       *r-- Scalable Vector Gaphics
 o  XPM       *rw- X Windows system pixmap (color)
 o  XV        *rw+ Khoros Visualization image
 o  XWD       *rw- X Windows system window dump (color)
 o  YUV       *rw- CCIR 601 4:1:1
                   
    Modes:         
              *    Native blob support
              r    Read
              w    Write
              +    Multi-image


\fISupport for some of these formats require additional programs or libraries.
README
tells where to find this software\fP.

Note, a format delineated with + means that if more than one
image is specified, it is composited into a single multi-image file. Use
\fB+adjoin\fP
if you want a single image produced for each frame.

Your installation might not support all of the formats in the list.  To get
an up-to-date listing of the formats supported by your particular
configuration, run "convert -list format".

Raw images are expected to have one byte per pixel unless \fBImageMagick\fP
is compiled in 16-bit mode. Here, the raw data is expected to be stored
two bytes per pixel in most-significant-byte-first order.
You can tell if \fBImageMagick\fP was compiled in 16-bit mode by typing
"convert" without any options, and looking for "Q:16" in the first line of
output.
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect for the set of images that follows,
until the set is terminated by the appearance of any option or \fB-noop\fP.
Some options only affect the decoding of images and others only the encoding.
The latter can appear after the final group of input images.

This is a combined list of the commandline options used by the ImageMagick
utilities (\fIanimate, composite, convert, display, identify,
import, mogrify\fP and \fImontage\fP).


In this document, angle brackets ("<>") enclose variables, and curly
brackets ("{}") enclose optional parameters. For example,
\fB"-fuzz <distance>{%}"\fP means you could use the option "-fuzz 2%".

.TP
.B "-adjoin"
\fRjoin images into a single multi-image file

By default, all images of an image sequence are stored in the same
file. However, some formats (e.g. JPEG) do not support more than one image
and are saved to separate files. Use \fB+adjoin\fP to force this
behavior.

.TP
.B "-affine \fI<matrix>"\fP
\fRdrawing transform matrix
.TP
.B "-antialias"
\fRremove pixel aliasing
.TP
.B "-append"
\fRappend a set of images

This option creates a single image where the images in the original set
are stacked top-to-bottom.  If they are not of the same width,
any narrow images will be expanded to fit using the background color.
Use \fB+append\fP to stack images left-to-right.  The set of images
is terminated by the appearance of any option.
If the \fB-append\fP
option appears after all of the input images, all images are appended.

.TP
.B "-average"
\fRaverage a set of images

The set of images
is terminated by the appearance of any option.
If the \fB-average\fP
option appears after all of the input images, all images are averaged.
.TP
.B "-backdrop \fI<color>"\fP
\fRdisplay the image centered on a backdrop.

This backdrop covers the entire workstation screen and is useful for hiding
other X window activity while viewing the image. The color of the backdrop
is specified as the background color.
The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.
Refer to
"X Resources", below,
for details.

.TP
.B "-background \fI<color>"\fP
\fRthe background color

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.
.TP
.B "-blur \fI<radius>x<sigma>"\fP
\fRblur the image with a gaussian operator

Blur with the given radius and
standard deviation (sigma).

.TP
.B "-border \fI<width>x<height>"\fP
\fRsurround the image with a border of color

See \fB-geometry\fP for details
about the geometry specification.

.TP
.B "-bordercolor \fI<color>"\fP
\fRthe border color

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.
.TP
.B "-borderwidth \fI<geometry>"\fP
\fRthe border width
.TP
.B "-box \fI<color>"\fP
\fRset the color of the annotation bounding box

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.

See \fB-draw\fP for further
details.

.TP
.B "-cache \fI<threshold>"\fP
\fRmegabytes of memory available to the pixel cache

Image pixels are stored in memory until 80 megabytes of memory have been
consumed. Subsequent pixel operations are cached on disk. Operations to
memory are significantly faster but if your computer does not have a sufficient
amount of free memory you may want to adjust this threshold value.

.TP
.B "-channel \fI<type>"\fP
\fRthe type of channel

Choose from: \fBRed\fP, \fBGreen\fP, \fBBlue\fP, \fBOpacity\fP,
\fBCyan\fP, \fBMagenta\fP, \fBYellow\fP, or \fBBlack\fP.


Use this option to extract a particular \fIchannel\fP from the image.
\fBMatte\fP,
for example, is useful for extracting the opacity values from an image.

.TP
.B "-charcoal \fI<factor>"\fP
\fRsimulate a charcoal drawing
.TP
.B "-chop \fI<width>x<height>{+-}<x>{+-}<y>{%}"\fP
\fRremove pixels from the interior of an image

\fIWidth\fP and \fIheight\fP give the number of columns and rows to remove,
and \fIx\fP and \fIy\fP are offsets that give the location of the
leftmost column and topmost row to remove.


The \fIx\fP offset normally specifies the leftmost column to remove.
If the \fB-gravity\fP option is present with \fINorthEast, East,\fP
or \fISouthEast\fP
gravity, it gives the distance leftward from the right edge
of the image to the rightmost column to remove.  Similarly, the \fIy\fP offset
normally specifies the topmost row to remove, but if
the \fB-gravity\fP option is present with \fISouthWest, South,\fP
or \fISouthEast\fP
gravity, it specifies the distance upward from the bottom edge of the
image to the bottom row to remove.

The \fB-chop\fP option removes entire rows and columns,
and moves the remaining corner blocks leftward and upward to close the gaps.

.TP
.B "-clip"
\fRapply the clipping path, if one is present

If a clipping path is present, it will be applied to subsequent operations.

For example, if you type the following command:

     convert -clip -negate cockatoo.tif negated.tif

only the pixels within the clipping path are negated.

The \fB-clip\fP feature requires the XML library.  If the XML library
is not present, the option is ignored.
.TP
.B "-coalesce"
\fRmerge a sequence of images

The set of images
is terminated by the appearance of any option.
If the \fB-coalesce\fP
option appears after all of the input images, all images are coalesced.
.TP
.B "-colorize \fI<value>"\fP
\fRcolorize the image with the pen color

Specify the amount of colorization as a percentage. You can apply separate
colorization values to the red, green, and blue channels of the image with
a colorization value list delineated with slashes (e.g. 0/0/50).

.TP
.B "-colormap \fI<type>"\fP
\fRdefine the colormap type

Choose between \fBshared\fP or \fBprivate\fP.


This option only applies when the default X server visual is \fIPseudoColor\fP
or \fIGRAYScale\fP. Refer to \fB-visual\fP for more details. By default,
a shared colormap is allocated. The image shares colors with other X clients.
Some image colors could be approximated, therefore your image may look
very different than intended. Choose \fBPrivate\fP and the image colors
appear exactly as they are defined. However, other clients may
go \fItechnicolor\fP when the image colormap is installed.
.TP
.B "-colors \fI<value>"\fP
\fRpreferred number of colors in the image

The actual number of colors in the image may be less than your request,
but never more. Note, this is a color reduction option. Images with less
unique colors than specified with this option will have any duplicate or
unused colors removed. Refer to quantize for
more details.


Note, options \fB-dither\fP, \fB-colorspace\fP, and \fB-treedepth\fP
affect the color reduction algorithm.

.TP
.B "-colorspace \fI<value>"\fP
\fRthe type of colorspace

Choices are: \fBGRAY\fP, \fBOHTA\fP, \fBRGB\fP,
\fBTransparent\fP,
\fBXYZ\fP,
\fBYCbCr\fP, \fBYIQ\fP, \fBYPbPr\fP,
\fBYUV\fP, or \fBCMYK\fP.


Color reduction, by default, takes place in the RGB color space. Empirical
evidence suggests that distances in color spaces such as YUV or YIQ correspond
to perceptual color differences more closely than do distances in RGB space.
These color spaces may give better results when color reducing an image.
Refer to quantize for more details.


The \fBTransparent\fP color space behaves uniquely in that it preserves
the matte channel of the image if it exists.


The \fB-colors\fP or \fB-monochrome\fP option is required for this
option to take effect.

.TP
.B "-comment \fI<string>"\fP
\fRannotate an image with a comment

Use this option to assign a specific comment to the image. You can include the
image filename, type, width, height, or other image attribute by embedding
special format characters:


     %b   file size
     %c   comment
     %d   directory
     %e   filename extention
     %f   filename
     %h   height
     %i   input filename
     %k   number of unique colors
     %l   label
     %m   magick
     %n   number of scenes
     %o   output filename
     %p   page number
     %q   quantum depth
     %s   scene number
     %t   top of filename
     %u   unique temporary filename
     %w   width
     %x   x resolution
     %y   y resolution
     %#   signature
     \\n   newline
     \\r   carriage return

For example,


     -comment "%m:%f %wx%h"

produces an image comment of \fBMIFF:bird.miff 512x480\fP for an image
titled \fBbird.miff\fP and whose width is 512 and height is 480.


If the first character of \fIstring\fP is \fI@\fP, the image comment
is read from a file titled by the remaining characters in the string.

.TP
.B "-compose \fI<operator>"\fP
\fRthe type of image composition

[This option is not used by \fIconvert\fP but this section
is included because it describes the composite operators that are used
by the \fI-draw\fP option of \fIconvert\fP.]


By default, each of the composite image pixels are replaced by the
corresponding image tile pixel. You can choose an alternate composite
operation:


     Over
     In
     Out
     Atop
     Xor
     Plus
     Minus
     Add
     Subtract
     Difference
     Multiply
     Bumpmap
     Copy
     CopyRed
     CopyGreen
     CopyBlue
     CopyOpacity

How each operator behaves is described below.

.in 15

.in 15
.B "Over"
.in 20
 \fR
.in 20

The result will be the union of the two image shapes, with opaque areas of
\fIcomposite image\fP obscuring \fIimage\fP in the region of overlap.

.in 15
.in 15
.B "In"
.in 20
 \fR
.in 20

The result is simply \fIcomposite image\fP cut by the shape
of \fIimage\fP.
None of the image data of \fIimage\fP will be in the result.

.in 15
.in 15
.B "Out"
.in 20
 \fR
.in 20

The resulting image is \fIcomposite image\fP with the shape
of \fIimage\fP cut out.

.in 15
.in 15
.B "Atop"
.in 20
 \fR
.in 20

The result is the same shape as image \fIimage\fP,
with \fIcomposite image\fP
obscuring \fIimage\fP where the image shapes overlap.  Note this differs
from \fBover\fP because the portion of \fIcomposite image\fP outside
\fIimage\fP's shape does not appear in the result.

.in 15
.in 15
.B "Xor"
.in 20
 \fR
.in 20

The result is the image data from both \fIcomposite image\fP and
\fIimage\fP
that is outside the overlap region.  The overlap region will be blank.

.in 15
.in 15
.B "Plus"
.in 20
 \fR
.in 20

The result is just the sum of the image data.  Output values are
cropped to 255 (no overflow).  This operation is independent of the
matte channels.

.in 15
.in 15
.B "Minus"
.in 20
 \fR
.in 20

The result of \fIcomposite image\fP - \fIimage\fP, with underflow
cropped to
zero.  The matte channel is ignored (set to 255, full coverage).

.in 15
.in 15
.B "Add"
.in 20
 \fR
.in 20

The result of \fIcomposite image\fP + \fIimage\fP, with overflow wrapping
around (\fImod\fP 256).

.in 15
.in 15
.B "Subtract"
.in 20
 \fR
.in 20

The result of \fIcomposite image\fP - \fIimage\fP, with underflow wrapping
around (\fImod\fP 256).  The \fBadd\fP and \fBsubtract\fP operators can be
used to perform reversible transformations.

.in 15
.in 15
.B "Difference"
.in 20
 \fR
.in 20

The result of abs(\fIcomposite image\fP - \fIimage\fP).  This is useful
for comparing two very similar images.

.in 15
.in 15
.B "Multiply"
.in 20
 \fR
.in 20

The result of \fIcomposite image\fP * \fIimage\fP.  This is useful for
the creation of drop-shadows.

.in 15
.in 15
.B "Bumpmap"
.in 20
 \fR
.in 20

The result \fIimage\fP shaded by \fIcomposite image\fP.

.in 15
.in 15
.B "Copy"
.in 20
 \fR
.in 20

The resulting image is \fIimage\fP replaced with \fIcomposite image\fP.
Here the matte information is ignored.

.in 15
.in 15
.B "CopyRed"
.in 20
 \fR
.in 20

The resulting image is the red layer in \fIimage\fP replaced with the red
layer in \fIcomposite image\fP.  The other layers are copied untouched.

.in 15
.in 15
.B "CopyGreen"
.in 20
 \fR
.in 20

The resulting image is the green layer in \fIimage\fP replaced with the green
layer in \fIcomposite image\fP.  The other layers are copied untouched.

.in 15
.in 15
.B "CopyBlue"
.in 20
 \fR
.in 20

The resulting image is the blue layer in \fIimage\fP replaced with the blue
layer in \fIcomposite image\fP.  The other layers are copied untouched.

.in 15
.in 15
.B "CopyOpacity"
.in 20
 \fR
.in 20

The resulting image is the matte layer in \fIimage\fP replaced with the matte
layer in \fIcomposite image\fP.  The other layers are copied untouched.

.in 15


The image compositor requires a matte, or alpha channel in the image
for some operations.  This extra channel usually defines a mask which
represents a sort of a cookie-cutter for the image.  This is the case
when matte is 255 (full coverage) for pixels inside the shape, zero
outside, and between zero and 255 on the boundary.  For certain
operations, if \fIimage\fP does not have a matte channel, it is initialized
with 0 for any pixel matching in color to pixel location (0,0), otherwise
255 (to work properly \fBborderwidth\fP must be 0).

.TP
.B "-compress \fI<type>"\fP
\fRthe type of image compression

Choices are: \fINone\fP, \fIBZip\fP, \fIFax\fP,
\fIGroup4\fP,
\fIJPEG\fP, \fILossless\fP,
\fILZW\fP, \fIRLE\fP or \fIZip\fP.


Specify \fB+compress\fP to store the binary image in an uncompressed format.
The default is the compression type of the specified image file.


If \fILZW\fP compression is specified but LZW compression has not been enabled,
the image data will be written
in an uncompressed LZW format that can be read by LZW decoders.  This
may result in larger-than-expected GIF files.

\fI"Lossless"\fP refers to lossless JPEG, which is only available if
the JPEG library has been patched to support it.
.TP
.B "-contrast"
\fRenhance or reduce the image contrast

This option enhances the intensity differences between the lighter and
darker elements of the image. Use \fB-contrast\fP to enhance
the image
or \fB+contrast\fP to reduce the image contrast.

.TP
.B "-crop \fI<width>x<height>{+-}<x>{+-}<y>{%}"\fP
\fRpreferred size and location of the cropped image

See \fB-geometry\fP for details
about the geometry specification.


The width and height give the size of the image that remains after cropping,
and \fIx\fP and \fIy\fP are offsets that give the location of the top left
corner of the cropped
image with respect to the original image.  To specify the amount to be
removed, use \fB-shave\fP instead.


To specify a percentage width or height to be removed instead, append
\fB%\fP. For example
to crop the image by ten percent (five percent on each side of the image),
use \fB-crop 10%\fP.


The \fIx\fP and \fIy\fP offsets specify the location of the upper left corner of
the cropping region measured downward and rightward with respect to the
upper left corner of the image.
If the \fB-gravity\fP option is present with \fINorthEast, East,\fP
or \fISouthEast\fP
gravity, it gives the distance leftward from the right edge
of the image to the right edge of the cropping region.  Similarly, if
the \fB-gravity\fP option is present with \fISouthWest, South,\fP
or \fISouthEast\fP
gravity, the distance is measured upward between the bottom
edges.

Omit the \fIx\fP and \fIy\fP offsets to generate one or more subimages
of a uniform
size.

.TP
.B "-cycle \fI<amount>"\fP
\fRdisplace image colormap by amount

\fIAmount\fP defines the number of positions each colormap entry is
shifted.

.TP
.B "-debug"
\fRenable debug printout
.TP
.B "-deconstruct"
\fRbreak down an image sequence into constituent parts

The sequence of images
is terminated by the appearance of any option.
If the \fB-deconstruct\fP
option appears after all of the input images, all images are deconstructed.
.TP
.B "-delay \fI<1/100ths of a second>"\fP
\fRdisplay the next image after pausing

This option is useful for regulating the animation of image sequences
\fIDelay/100\fP seconds must expire before the display
of the next image. The default is no delay between each showing of the
image sequence. The maximum delay is 65535.


You can specify a delay range (e.g. \fI-delay 10-500\fP) which sets the
minimum and maximum delay.

.TP
.B "-density \fI<width>x<height>"\fP
\fRvertical and horizontal resolution in pixels of the image

This option specifies an image density when decoding a \fIPostScript\fP
or Portable Document page. The default is 72 dots per inch in the horizontal
and vertical direction. This option is used in concert with \fB-page\fP.

.TP
.B "-depth \fI<value>"\fP
\fRdepth of the image

This is the number of bits in a color sample within a pixel. The only
acceptable values are 8 or 16.  Use this option to specify the depth of
raw images whose depth is unknown such as GRAY, RGB, or CMYK, or to change
the depth of any image after it has been read.

.TP
.B "-descend"
\fRobtain image by descending window hierarchy
.TP
.B "-despeckle"
\fRreduce the speckles within an image
.TP
.B "-displace \fI<horizontal scale>x<vertical scale>"\fP
\fRshift image pixels as defined by a displacement map

With this option, \fIcomposite image\fP is used as a displacement map.  Black,
within the displacement map, is a maximum positive displacement.  White is a
maximum negative displacement and middle gray is neutral.  The displacement
is scaled to determine the pixel shift.  By default, the displacement applies
in both the horizontal and vertical directions.  However, if you specify
\fImask\fP, \fIcomposite image\fP is the horizontal X displacement and
\fImask\fP the vertical Y displacement.

.TP
.B "-display \fI<host:display[.screen]>"\fP
\fRspecifies the X server to contact

This option is used with convert for
obtaining image or font from this X server.  See \fIX(1)\fP.

.TP
.B "-dispose \fI<method>"\fP
\fRGIF disposal method

Here are the valid methods:


     0     No disposal specified.
     1     Do not dispose between frames.      
     2     Overwrite frame with background color
           from header.
     3     Overwrite with previous frame.
.TP
.B "-dissolve \fI<percent>"\fP
\fRdissolve an image into another by the given percent

The opacity of the composite image is multiplied by the given percent,
then it is composited over the main image.
.TP
.B "-dither"
\fRapply Floyd/Steinberg error diffusion to the image

The basic strategy of dithering is to trade intensity resolution for spatial
resolution by averaging the intensities of several neighboring pixels.
Images which suffer from severe contouring when reducing colors can be
improved with this option.


The \fB-colors\fP or \fB-monochrome\fP option is required for this option
to take effect.


Use \fB+dither\fP to turn off dithering and to render Postscript without
text or graphic aliasing.

.TP
.B "-draw \fI<string>"\fP
\fRannotate an image with one or more graphic primitives

Use this option to annotate an image with one or more graphic primitives.
The primitives include


     point           x,y
     line            x0,y0 x1,y1
     rectangle       x0,y0 x1,y1
     roundRectangle  x0,y0  w,h  wc,hc
     arc             x0,y0 x1,y1 a0,a1
     ellipse         x0,y0 rx,ry a0,a1
     circle          x0,y0 x1,y1
     polyline        x0,y0  ...  xn,yn
     polygon         x0,y0  ...  xn,yn
     bezier          x0,y0  ...  xn,yn
     path            path specification
     color           x0,y0 method
     matte           x0,y0 method
     text            x0,y0 string
     image           operator x0,y0 w,h filename

\fBPoint\fP requires a single coordinate.
\fBLine\fP requires a start and end coordinate, while
\fBrectangle\fP
expects an upper left and lower right coordinate.
\fBroundRectangle\fP has a center coordinate, a width and
height, and the width and height of the corners.
\fBCircle\fP has a center coordinate and a coordinate for
the outer edge.  Use \fBArc\fP to circumscribe an arc within
a rectangle.  Arcs require a start and end point as well as the degree
of rotation (e.g. 130,30 200,100 45,90).
Use \fBEllipse\fP to draw a partial ellipse
centered at the given point with the x-axis and y-axis radius
and start and end of arc in degrees (e.g. 100,100 100,150 0,360).
Finally, \fBpolyline\fP and \fBpolygon\fP require
three or more coordinates to define its boundaries.
Coordinates are integers separated by an optional comma.  For example,
to define a circle centered at 100,100
that extends to 150,150 use:


     -draw 'circle 100,100 150,150'

See Paths.
Paths
represent an outline of an object which is defined in terms of
moveto (set a new current point), lineto (draw a straight line),
curveto (draw a curve using a cubic bezier), arc (elliptical or
circular arc) and closepath (close the current shape by drawing a line
to the last moveto) elements. Compound paths (i.e., a path with
subpaths, each consisting of a single moveto followed by one or more
line or curve operations) are possible to allow effects such as
"donut holes" in objects.


Use \fBcolor\fP to change the color of a pixel to the fill color (see
\fB-fill\fP. Follow the pixel coordinate
with a method:


     point
     replace
     floodfill
     filltoborder
     reset

Consider the target pixel as that specified by your coordinate. The
\fBpoint\fP
method recolors the target pixel. The \fBreplace\fP method recolors any
pixel that matches the color of the target pixel.
\fBFloodfill\fP recolors
any pixel that matches the color of the target pixel and is a neighbor,
whereas \fBfilltoborder\fP recolors any neighbor pixel that is not the
border color. Finally, \fBreset\fP recolors all pixels.


Use \fBmatte\fP to the change the pixel matte value to transparent. Follow
the pixel coordinate with a method (see the \fBcolor\fP primitive for
a description of methods). The \fBpoint\fP method changes the matte value
of the target pixel. The \fBreplace\fP method changes the matte value
of any pixel that matches the color of the target pixel. \fBFloodfill\fP
changes the matte value of any pixel that matches the color of the target
pixel and is a neighbor, whereas
\fBfilltoborder\fP changes the matte
value of any neighbor pixel that is not the border color (\fB-bordercolor\fP).
Finally \fBreset\fP changes the matte value of all pixels.


Use \fBtext\fP to annotate an image with text. Follow the text coordinates
with a string. If the string has embedded spaces, enclose it in double
quotes. Optionally you can include the image filename, type, width, height,
or other image attribute by embedding special format character.
See \fB-comment\fP for details.


For example,


     -draw 'text 100,100 "%m:%f %wx%h"'

annotates the image with MIFF:bird.miff 512x480 for an image titled
bird.miff
and whose width is 512 and height is 480.


Use \fBimage\fP to composite an image with another image. Follow the
image keyword with the composite operator, image location, image size,
and filename:


     -draw 'image Over 100,100 225,225 image.jpg'

See \fB-compose\fP for a description of the composite operators.


If the first character of \fIstring\fP is \fI@\fP, the text is read from
a file titled by the remaining characters in the string.


You can set the primitive color, font, and font bounding box
color with
\fB-fill\fP, \fB-font\fP, and \fB-box\fP respectively. Options
are processed in command line order so be sure to use these
options \fIbefore\fP the \fB-draw\fP option.

.TP
.B "-edge \fI<radius>"\fP
\fRdetect edges within an image
.TP
.B "-emboss"
\fRemboss an image
.TP
.B "-endian \fI<type>"\fP
\fRspecify endianness (MSB or LSB) of output image

Use \fB+endian\fP to revert to unspecified endianness.
.TP
.B "-enhance"
\fRapply a digital filter to enhance a noisy image
.TP
.B "-equalize"
\fRperform histogram equalization to the image
.TP
.B "-fill \fI<color>"\fP
\fRcolor to use when filling a graphic primitive

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.

See \fB-draw\fP for further
details.

.TP
.B "-filter \fI<type>"\fP
\fRuse this type of filter when resizing an image

Use this option to affect the resizing operation of an image (see
\fB-geometry\fP).
Choose from these filters:


     Point
     Box
     Triangle
     Hermite
     Hanning
     Hamming
     Blackman
     Gaussian
     Quadratic
     Cubic
     Catrom
     Mitchell
     Lanczos
     Bessel
     Sinc

The default filter is \fBLanczos\fP

.TP
.B "-flatten"
\fRflatten a sequence of images

The sequence of images
is terminated by the appearance of any option.
If the \fB-flatten\fP
option appears after all of the input images, all images are flattened.
.TP
.B "-flip"
\fRcreate a "mirror image"

reflect the scanlines in the vertical direction.

.TP
.B "-flop"
\fRcreate a "mirror image"

reflect the scanlines in the horizontal direction.

.TP
.B "-font \fI<name>"\fP
\fRuse this font when annotating the image with text

You can tag a font to specify whether it is a Postscript, Truetype, or OPTION1
font.  For example, Arial.ttf is a Truetype font, ps:helvetica
is Postscript, and x:fixed is OPTION1. 

.TP
.B "-foreground \fI<color>"\fP
\fRdefine the foreground color

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.
.TP
.B "-format \fI<type>"\fP
\fRthe image format type

This option will convert any image to the image format you specify.
See \fBconvert(1)\fP for a list of image format types supported by
\fBImageMagick\fP.


By default the file is written to its original name.  However, if the
filename extension matches a supported format, the extension is replaced
with the image format type specified with \fB-format\fP.  For example,
if you specify \fItiff\fP as the format type and the input image
filename is \fIimage.gif\fP, the output image filename becomes
\fIimage.tiff\fP.

.TP
.B "-format \fI<string>"\fP
\fRoutput formatted image characteristics

Use this option to print information about the image in a format of your
choosing.  You can include the image filename, type, width, height,
or other image attributes by embedding special format characters:

     %b   file size
     %c   comment
     %d   directory
     %e   filename extention
     %f   filename
     %h   height
     %i   input filename
     %k   number of unique colors
     %l   label
     %m   magick
     %n   number of scenes
     %o   output filename
     %p   page number
     %q   quantum depth
     %s   scene number
     %t   top of filename
     %u   unique temporary filename
     %w   width
     %x   x resolution
     %y   y resolution
     %#   signature
     \\n   newline
     \\r   carriage return

For example,

     -format "%m:%f %wx%h"

displays \fBMIFF:bird.miff 512x480\fP for an image
titled \fBbird.miff\fP and whose width is 512 and height is 480.

If the first character of \fIstring\fP is \fB@\fP, the format
is read from a file titled by the remaining characters in the string.
.TP
.B "-frame \fI<width>x<height>+<outer bevel width>+<inner bevel width>"\fP
\fRsurround the image with an ornamental border

See \fB-geometry\fP for details
about the geometry specification.
The \fB-frame\fP option is not affected by the \fB-gravity\fP option.


The color of the border is specified with the
\fB-mattecolor\fP command
line option.

.TP
.B "-frame"
\fRinclude the X window frame in the imported image
.TP
.B "-fuzz \fI<distance>{%}"\fP
\fRcolors within this distance are considered equal

A number of algorithms search for a target color. By default the color
must be exact. Use this option to match colors that are close to the target
color in RGB space. For example, if you want to automatically trim the
edges of an image with \fI-trim\fP but the image was scanned and the
target background color may differ by a small amount. This option can account
for these differences.


The \fIdistance\fP can be in absolute intensity units or, by appending
\fI"%"\fP, as a percentage of the maximum possible intensity (255 or 65535).

.TP
.B "-gamma \fI<value>"\fP
\fRlevel of gamma correction

The same color image displayed on two different workstations may look different
due to differences in the display monitor. Use gamma correction to adjust
for this color difference. Reasonable values extend from \fB0.8\fP to
\fB2.3\fP.


You can apply separate gamma values to the red, green, and blue channels
of the image with a gamma value list delineated with slashes
(e.g., \fB1.7\fP/\fB2.3\fP/\fB1.2\fP).


Use \fB+gamma\fP \fIvalue\fP
to set the image gamma level without actually adjusting
the image pixels. This option is useful if the image is of a known gamma
but not set as an image attribute (e.g. PNG images).

.TP
.B "-gaussian \fI<radius>x<sigma>"\fP
\fRblur the image with a gaussian operator

Use the given radius and standard deviation (sigma). 

.TP
.B "-geometry \fI<width>x<height>{+-}<x>{+-}<y>{%}{@} {!}{<}{>}"\fP
\fRpreferred size and location of the Image window.

By default, the window size is the image
size and the location is chosen by you when it is mapped.


By default, the width and height are maximum values. That is, the image
is expanded or contracted to fit the width and height value while maintaining
the aspect ratio of the image. \fIAppend an exclamation point to the geometry
to force the image size to exactly the size you specify\fP. For example,
if you specify 640x480! the image width is set to 640 pixels and
height to 480.


If only the width is specified, the width assumes the
value and the height is chosen to maintain the aspect ratio of the image.
Similarly, if only the height is specified (e.g., -geometry x256),
the width is chosen to maintain the aspect ratio. 


To specify a percentage width or height instead, append %. The image size
is multiplied by the width and height percentages to obtain the final image
dimensions. To increase the size of an image, use a value greater than
100 (e.g. 125%). To decrease an image's size, use a percentage less than
100.


Use @ to specify the maximum area in pixels of an image.


Use > to change the dimensions of the image \fIonly\fP if
its width or height exceeds the geometry specification. < resizes
the image \fIonly\fP if both of its dimensions are less than the geometry
specification. For example,
if you specify '640x480>' and the image size is 256x256, the image
size does not change. However, if the image is 512x512 or 1024x1024, it is
resized to 480x480.  Enclose the geometry specification in quotation marks to
prevent the < or > from being interpreted by your shell
as a file redirection.


When used with \fIanimate\fP and \fIdisplay\fP, offsets are handled in
the same manner as in \fIX(1)\fP and the \fB-gravity\fP option is not used.
If the \fIx\fP is negative, the offset is measured leftward
from the right edge of the
screen to the right edge of the image being displayed.
Similarly, negative \fIy\fP is measured between the bottom edges.  The
offsets are not affected by "%"; they are always measured in pixels.

When used as a \fIcomposite\fP option, \fB-geometry\fP
gives the dimensions of the image and its location with respect
to the composite image.  If the \fB-gravity\fP option is present
with \fINorthEast, East,\fP or \fISouthEast\fP gravity, the \fIx\fP 
represents the distance from the right edge of the image to the right edge of
the composite image.  Similarly, if the \fB-gravity\fP option is present
with \fISouthWest, South,\fP or \fISouthEast\fP gravity, \fIy\fP
is measured between the bottom edges. Accordingly, a positive offset will
never point in the direction outside of the image.  The
offsets are not affected by "%"; they are always measured in pixels.

When used as a \fIconvert\fP, \fIimport\fP or \fImogrify\fP option,
\fB-geometry\fP
specifies the size of the output image.  The offsets, if present, are ignored.


When used as a \fImontage\fP option, \fB-geometry\fP specifies the image
size and border size for each tile; default is 256x256+0+0.  Negative
offsets (border dimensions) are meaningless.  The \fB-gravity\fP
option affects the placement of the image within the tile; the default
gravity for this purpose is \fICenter\fP.  If the "%" sign appears in
the geometry specification, the tile size is the specified percentage of
the original dimensions of the first tile.

.TP
.B "-gravity \fI<type>"\fP
\fRdirection primitive  gravitates to when annotating the image.

Choices are: NorthWest, North,
NorthEast, West, Center, East, SouthWest, South, SouthEast.


The direction you choose specifies where to position the text or other
graphic primitive when annotating
the image. For example \fICenter\fP gravity forces the text to be centered
within the image. By default, the image gravity is \fINorthWest\fP.
See \fB-draw\fP for more details about graphic primitives.


The \fB-gravity\fP option is also used in concert with the \fB-geometry\fP
option and other options that take \fB<geometry>\fP as a parameter, such
as the \fB-crop\fP option.  See \fB-geometry\fP for details of how the
\fB-gravity\fP option interacts with the 
\fB<x>\fP and \fB<y>\fP parameters of a geometry
specification.

When used as an option to \fIcomposite\fP, \fB-gravity\fP
gives the direction that the image gravitates within the composite.


When used as an option to \fImontage\fP, \fB-gravity\fP gives the direction
that an image gravitates within a tile.  The default gravity is \fICenter\fP
for this purpose.

.TP
.B "-help"
\fRprint usage instructions
.TP
.B "-iconGeometry \fI<geometry>"\fP
\fRspecify the icon geometry

Offsets, if present in the geometry specification, are handled in
the same manner as the \fB-geometry\fP option, using X11 style to handle
negative offsets.
.TP
.B "-iconic"
\fRiconic animation
.TP
.B "-immutable"
\fRmake image immutable
.TP
.B "-implode \fI<factor>"\fP
\fRimplode image pixels about the center
.TP
.B "-intent \fI<type>"\fP
\fRuse this type of rendering intent when managing the image color

Use this option to affect the the color management operation of an image (see
\fB-profile\fP).
Choose from these intents:
\fBAbsolute, Perceptual, Relative, Saturation\fP 


The default intent is undefined.

.TP
.B "-interlace \fI<type>"\fP
\fRthe type of interlacing scheme

Choices are: \fBNone, Line, Plane,\fP
or \fBPartition\fP. The default is \fBNone\fP.


This option is used to specify the type of interlacing scheme for raw image
formats such as \fBRGB\fP or \fBYUV\fP.

\fBNone\fP means do not interlace
(RGBRGBRGBRGBRGBRGB...),

\fBLine\fP uses scanline interlacing
(RRR...GGG...BBB...RRR...GGG...BBB...),
and

\fBPlane\fP uses plane interlacing (RRRRRR...GGGGGG...BBBBBB...).

\fBPartition\fP
is like plane except the different planes are saved to individual files
(e.g. image.R, image.G, and image.B).


Use \fBLine\fP or \fBPlane\fP to create an
\fBinterlaced PNG\fP or \fB GIF\fP or
\fBprogressive JPEG\fP image.

.TP
.B "-label \fI<name>"\fP
\fRassign a label to an image

Use this option to assign a specific label to the image. Optionally you
can include the image filename, type, width, height, or other image attribute
by embedding special format character. See \fB-comment\fP for details.


For example,


     -label "%m:%f %wx%h"

produces an image label of \fBMIFF:bird.miff 512x480\fP for an image titled
\fBbird.miff\fP
and whose width is 512 and height is 480.


If the first character of \fIstring\fP is \fI@\fP, the image label is
read from a file titled by the remaining characters in the string.


When converting to \fIPostScript\fP, use this option to specify a header
string to print above the image. Specify the label font with
\fB-font\fP.

.TP
.B "-level \fI<value>"\fP
\fRadjust the level of image contrast

Give three point values delineated with commas: black, mid, and white
(e.g. 10,1.0,65000).  The white and black points range from 0 to MaxRGB
and mid ranges from 0 to 10.

.TP
.B "-linewidth"
\fRthe line width for subsequent draw operations
.TP
.B "-list \fI<type>"\fP
\fRthe type of list

Choices are: \fBDelegate\fP, \fBFormat\fP, \fBMagic\fP,
\fBModule\fP, or \fBType\fP.


This option lists entries from the ImageMagick configuration files.

.TP
.B "-loop \fI<iterations>"\fP
\fRadd Netscape loop extension to your GIF animation

A value other than zero forces the animation to repeat itself up to
\fIiterations\fP
times.

.TP
.B "-magnify \fI<factor>"\fP
\fRmagnify the image
.TP
.B "-map \fI<filename>"\fP
\fRchoose a particular set of colors from this image

[\fIconvert\fP or \fImogrify\fP]

By default, color reduction chooses an optimal set of colors that best
represent the original image. Alternatively, you can choose a particular
set of colors from an image file with this option.

Use
\fB+map\fP to reduce
all images in the image sequence that follows to a single optimal set of colors
that best represent all the images.  The sequence of images
is terminated by the appearance of any option.
If the \fB+map\fP
option appears after all of the input images, all images are mapped.
.TP
.B "-map \fI<type>"\fP
\fR
display image using this type.

[\fIanimate\fP or \fIdisplay\fP]

Choose from these \fIStandard Colormap\fP types:

     best
     default
     gray
     red
     green
     blue

The \fIX server\fP must support the \fIStandard Colormap\fP you choose,
otherwise an error occurs. Use \fBlist\fP as the type and \fBdisplay\fP
searches the list of colormap types in \fBtop-to-bottom\fP order until
one is located. See \fIxstdcmap(1)\fP for one way of creating Standard
Colormaps.
.TP
.B "-mask \fI<filename>"\fP
\fRSpecify a clipping mask

The image read from the file is used as a clipping mask.  It must have
the same dimensions as the image being masked.

If the mask image contains an opacity channel, the opacity of each pixel is
used to define the mask.  Otherwise, the intensity (gray level) of each
pixel is used.

Use \fB+mask\fP to remove the clipping mask.

It is not necessary to use \fB-clip\fP to activate the mask; \fB-clip\fP
is implied by \fB-mask\fP.
.TP
.B "-matte"
\fRstore matte channel if the image has one

If the image does not have a matte channel, create an opaque one.


Use \fB+matte\fP to ignore the matte channel and to avoid writing a
matte channel in the output file.
.TP
.B "-mattecolor \fI<color>"\fP
\fRspecify the matte color

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.
.TP
.B "-median \fI<radius>"\fP
\fRapply a median filter to the image
.TP
.B "-mode \fI<value>"\fP
\fRmode of operation
.TP
.B "-modulate \fI<value>"\fP
\fRvary the brightness, saturation, and hue of an image

Specify the percent change in brightness, the color saturation, and the
hue separated by commas. For example, to increase the color brightness
by 20% and decrease the color saturation by 10% and leave the hue unchanged,
use: \fB-modulate 120,90\fP.

.TP
.B "-monochrome"
\fRtransform the image to black and white
.TP
.B "-morph \fI<frames>"\fP
\fRmorphs an image sequence

Both the image pixels and size are linearly interpolated to give the appearance
of a meta-morphosis from one image to the next.


The sequence of images
is terminated by the appearance of any option.
If the \fB-morph\fP
option appears after all of the input images, all images are morphed.
.TP
.B "-mosaic"
\fRcreate a mosaic from an image sequence

The \fB-page\fP option is used to locate the images within the mosaic.

The sequence of images
is terminated by the appearance of any option.
If the \fB-mosaic\fP
option appears after all of the input images, all images are included
in the mosaic.
.TP
.B "-name"
\fRname an image
.TP
.B "-negate"
\fRreplace every pixel with its complementary color

The red, green, and blue intensities of an image are negated.
White becomes black,
yellow becomes blue, etc.
Use \fB+negate\fP
to only negate the grayscale pixels of the image.

.TP
.B "-noise \fI<radius|type>"\fP
\fRadd or reduce noise in an image

The principal function of noise peak elimination filter is to smooth the
objects within an image without losing edge information and without creating
undesired structures. The central idea of the algorithm is to replace a
pixel with its next neighbor in value within a pixel window, if this pixel
has been found to be noise. A pixel is defined as noise if and only if
this pixel is a maximum or minimum within the pixel window.


Use \fBradius\fP to specify the width of the neighborhood.


Use \fB+noise\fP followed by a noise type to add noise to an image. Choose
from these noise types:


     Uniform
     Gaussian
     Multiplicative
     Impulse
     Laplacian
     Poisson
.TP
.B "-noop"
\fRNOOP (no option)

The \fB-noop\fP option can be used to terminate a group of images
and reset all options to their default values, when no other option is
desired.
.TP
.B "-normalize"
\fRtransform image to span the full range of color values

This is a contrast enhancement technique.

.TP
.B "-opaque \fI<color>"\fP
\fRchange this color to the pen color within the image

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.

See \fB-fill\fP for more details.

.TP
.B "-page \fI<width>x<height>{+-}<x>{+-}<y>{%}{!}{<}{>}"\fP
\fRsize and location of an image canvas

Use this option to specify the dimensions of the
\fIPostScript\fP page
in dots per inch or a TEXT page in pixels. The choices for a Postscript
page are:


     11x17         792  1224 
     Ledger       1224   792    
     Legal         612  1008
     Letter        612   792
     LetterSmall   612   792
     ArchE        2592  3456
     ArchD        1728  2592
     ArchC        1296  1728
     ArchB         864  1296
     ArchA         648   864
     A0           2380  3368
     A1           1684  2380
     A2           1190  1684
     A3            842  1190
     A4            595   842
     A4Small       595   842
     A5            421   595
     A6            297   421
     A7            210   297
     A8            148   210
     A9            105   148
     A10            74   105
     B0           2836  4008
     B1           2004  2836
     B2           1418  2004
     B3           1002  1418
     B4            709  1002
     B5            501   709
     C0           2600  3677
     C1           1837  2600
     C2           1298  1837
     C3            918  1298
     C4            649   918
     C5            459   649
     C6            323   459
     Flsa          612   936 
     Flse          612   936
     HalfLetter    396   612

For convenience you can specify the page size by media (e.g. A4, Ledger,
etc.). Otherwise, \fB-page\fP behaves much like
\fB-geometry\fP (e.g.  -page letter+43+43>).


To position a GIF image, use \fB-page\fP\fI{+-}<x>{+-}<y>\fP
(e.g. -page +100+200).


For a Postscript page, the image is sized as in \fB-geometry\fP and positioned
relative to the lower left hand corner of the page by
{+-}<\fBx\fP\fIoffset\fP>{+-}<\fBy\fP
\fIoffset>\fP. Use
-page 612x792>, for example, to center the
image within the page. If the image size exceeds the Postscript page, it
is reduced to fit the page.
The default gravity for the \fB-page\fP
option is \fINorthWest\fP, i.e., positive \fBx\fP and
\fBy\fP \fIoffset\fP are measured rightward and downward from the top
left corner of the page, unless the \fB-gravity\fP option is present with
a value other than \fINorthWest\fP.


The default page dimensions for a TEXT image is 612x792.


This option is used in concert with \fB-density\fP.

.TP
.B "-paint \fI<radius>"\fP
\fRsimulate an oil painting

Each pixel is replaced by the most frequent color in a circular neighborhood
whose width is specified with \fIradius\fP.

.TP
.B "-pause \fI<seconds>"\fP
\fRpause between animation loops [animate]

Pause for the specified number of seconds before repeating the
animation.
.TP
.B "-pause \fI<seconds>"\fP
\fRpause between snapshots [import]

Pause for the specified number of seconds before taking the next
snapshot.
.TP
.B "-pen \fI<color>"\fP
\fRspecify the pen color for drawing operations

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.
.TP
.B "-ping"
\fRefficiently determine image characteristics
.TP
.B "-pointsize \fI<value>"\fP
\fRpointsize of the Postscript, OPTION1, or TrueType font
.TP
.B "-preview \fI<type>"\fP
\fRimage preview type

Use this option to affect the preview operation of an image (e.g.
convert
-preview Gamma Preview:gamma.png). Choose from these previews:


     Rotate
     Shear
     Roll
     Hue
     Saturation
     Brightness
     Gamma
     Spiff
     Dull
     Grayscale
     Quantize
     Despeckle
     ReduceNoise
     Add Noise
     Sharpen
     Blur
     Threshold
     EdgeDetect
     Spread
     Shade
     Raise
     Segment
     Solarize
     Swirl
     Implode
     Wave
     OilPaint
     CharcoalDrawing
     JPEG

The default preview is \fBJPEG\fP.

.TP
.B "-process \fI<command>"\fP
\fRprocess a sequence of images

The sequence of images
is terminated by the appearance of any option.
If the \fB-process\fP
option appears after all of the input images, all images are processed.
.TP
.B "-profile \fI<filename>"\fP
\fRadd ICM, IPTC, or generic profile  to image

-profile filename adds an ICM (ICC color management), IPTC
(newswire information), or a generic profile to the image.

Use +profile icm, +profile iptc,
or +profile profile_name to remove the respective
profile.  Use identify -verbose to find out what profiles are in the
image file.  Use +profile "*" to remove all profiles.

.TP
.B "-quality \fI<value>"\fP
\fRJPEG/MIFF/PNG compression level

For the JPEG image format, quality is 0 (lowest image quality and highest
compression) to 100 (best quality but least effective compression). The default
quality is 75.  If the quality is an odd number, 2x2 chroma downsampling is
used.  If it is even, 1x1 chroma sampling is used.


For the MIFF image format, quality is the zlib compression level, which
is 0 (worst but fastest compression) to 9 (best but slowest).  It has no
effect on the image appearance, since the compression is always lossless.

For the MNG and PNG image format, the quality value sets the zlib compression
level (quality / 10) and filter-type (quality % 10). Compression levels
range from 0 (fastest compression) to 100 (best but slowest). For compression
level 0, the Huffman-only strategy is used, which is fastest but not
necessarily the worst compression.

If
filter-type is 4 or less, the specified filter-type is used for all scanlines:


     0: none
     1: sub
     2: up
     3: average
     4: Paeth

If filter-type is 5, adaptive filtering is used when quality is greater
than 50 and the image does not have a color map, otherwise no filtering
is used.


If filter-type is 6, adaptive filtering
with \fIminimum-sum-of-absolute-values\fP
is used.


Only if the output is MNG, if filter-type is 7, the LOCO color transformation
and adaptive filtering with \fIminimum-sum-of-absolute-values\fP
are used.


The default is quality is 75, which means nearly the best compression with
adaptive filtering.  The quality setting has no effect on the appearance
of PNG and MNG images, since the compression is always lossless.


For further information, see the PNG
specification.

.TP
.B "-raise \fI<width>x<height>"\fP
\fRlighten or darken image edges

This will create a 3-D effect.
See \fB-geometry\fP for details
details about the geometry specification.
Offsets are not used.


Use \fB-raise\fP to create a raised effect, otherwise use \fB+raise\fP.

.TP
.B "-region \fI<width>x<height>{+-}<x>{+-}<y>"\fP
\fRapply options to a portion of the image

The \fIx\fP and \fIy\fP offsets are treated in the same manner as in \fB-crop\fP.
.TP
.B "-remote"
\fRperform a remote operation

The only command recognized at this time is the name of
an image file to load.

.TP
.B "-resize \fI<width>x<height>{+-}<x>{+-}<y>{%}{@}{!}{<}{>}"\fP
\fRresize and locate an image

This is an alias for the \fB-geometry\fP option and it behaves in the
same manner. If the \fB-filter\fP option precedes the \fB-resize\fP
option, the specified filter is used.

There are some exceptions:

When used as a \fIcomposite\fP option, \fB-resize\fP conveys the preferred
size and location of the output image, while \fB-geometry\fP conveys
the size and placement of the \fIcomposite image\fP within the main
image.

When used as a \fImontage\fP option, \fB-resize\fP conveys the preferred
size and location of the montage, while \fB-geometry\fP conveys
information about the tiles.
.TP
.B "-roll \fI{+-}<x>{+-}<y>"\fP
\fRroll an image vertically or horizontally

See \fB-geometry\fP for details
the geometry specification.
The \fIx\fP and \fIy\fP offsets are not affected
by the \fB-gravity\fP option.


A negative \fIx\fP  offset rolls the image left-to-right. A negative \fIy\fP
offset rolls the image top-to-bottom.

.TP
.B "-rotate \fI<degrees{<}{>}>"\fP
\fRapply Paeth image rotation to the image

Use > to rotate the image only if its width exceeds the height.
< rotates the image \fIonly\fP if its width is less than the
height. For example, if you specify -rotate "-90>" and the image
size is 480x640, the image is not rotated.  However, if the
image is 640x480, it is rotated by -90 degrees.  If you use > or
<, enclose it in quotation marks to prevent it from being
misinterpreted as a file redirection.


Empty triangles left over from rotating the image are filled with the color
defined as \fBbackground\fP (class \fBbackgroundColor\fP). See \fIX(1)\fP
for details.

.TP
.B "-sample \fI<geometry>"\fP
\fRscale image with pixel sampling

See \fB-geometry\fP for details about
the geometry specification.
\fB-sample\fP ignores the \fB-filter\fP selection if the \fB-filter\fP option
is present.  Offsets, if present in the geometry string, are ignored, and
the \fB-gravity\fP option has no effect.

.TP
.B "-scale \fI<geometry>"\fP
\fRscale the image.

See \fB-geometry\fP for details about
the geometry specification.  \fB-scale\fP uses a simpler, faster algorithm,
and it ignores the \fB-filter\fP selection if the \fB-filter\fP option
is present.  Offsets, if present in the geometry string, are ignored, and
the \fB-gravity\fP option has no effect.

.TP
.B "-scene \fI<value>"\fP
\fRset scene number

This option sets the scene number of an image or the first image in
an image sequence.
.TP
.B "-scenes \fI<value-value>"\fP
\fRrange of image scene numbers to read

Each image in the range is read
with the filename followed by a period (\fB.\fP) and the decimal scene
number.  You
can change this behavior by embedding a \fB%0Nd, %0No, or %0Nx printf\fP
format specification in the file name. For example,

    montage -scenes 5-7 image.miff

makes a montage of files image.miff.5, image.miff.6, and image.miff.7, and 

    animate -scenes 0-12 image%02d.miff

animates files image00.miff, image01.miff, through image12.miff. 
.TP
.B "-snaps \fI<value>"\fP
\fRnumber of screen snapshots

Use this option
to grab more than one image from the X server screen, to create
an animation sequence.
.TP
.B "-screen"
\fRspecify the screen to capture

This option indicates that the GetImage request used to obtain the image
should be done on the root window, rather than directly on the specified
window.  In this way, you can obtain pieces of other windows that overlap
the specified window, and more importantly, you can capture menus or other
popups that are independent windows but appear over the specified window.
.TP
.B "-seed \fI<value>"\fP
\fRpseudo-random number generator seed value
.TP
.B "-segment \fI<cluster threshold>x<smoothing threshold>"\fP
\fRsegment an image

Segment an image by analyzing the histograms of the color components and
identifying units that are homogeneous with the fuzzy c-means technique.


Specify \fIcluster threshold\fP as the number of pixels in each cluster
must exceed the the cluster threshold to be considered valid. \fISmoothing
threshold\fP eliminates noise in the second derivative of the histogram.
As the value is increased, you can expect a smoother second derivative.
The default is 1.5. See
"Image Segmentation", below,
for details.

.TP
.B "-shade \fI<azimuth>x<elevation>"\fP
\fRshade the image using a distant light source

Specify \fIazimuth\fP and \fIelevation\fP as the position of the light
source. Use \fB+shade\fP to return the shading results as a grayscale
image.

.TP
.B "-shadow \fI<radius>x<sigma>"\fP
\fRshadow the montage
.TP
.B "-shared_memory"
\fRuse shared memory

This option specifies whether the utility should attempt use shared memory
for pixmaps.  ImageMagick must be compiled with shared memory support,
and the display must support the \fIMIT-SHM\fP extension.  Otherwise, this
option is ignored.  The default is \fBTrue\fP.

.TP
.B "-sharpen \fI<radius>x<sigma>"\fP
\fRsharpen the image

Use a gaussian operator of the given radius and
standard deviation (sigma). 

.TP
.B "-shave \fI<width>x<height>"\fP
\fRshave pixels from the image edges

Specify the width of the region to be removed from both
sides of the image and the height of the regions to be removed from
top and bottom.

.TP
.B "-shear \fI<x degrees>x<y degrees>"\fP
\fRshear the image along the X or Y axis

Use the specified positive or negative shear angle.


Shearing slides one edge of an image along the X or Y axis, creating a
parallelogram. An X direction shear slides an edge along the X axis, while
a Y direction shear slides an edge along the Y axis. The amount of the
shear is controlled by a shear angle. For X direction shears, \fIx degrees\fP
is measured relative to the Y axis, and similarly, for Y direction shears
\fIy
degrees\fP is measured relative to the X axis.


Empty triangles left over from shearing the image are filled with the color
defined as \fBbackground\fP (class \fBbackgroundColor\fP). See \fIX(1)\fP
for details.

.TP
.B "-silent"
\fRoperate silently
.TP
.B "-size \fI<width>x<height>{+offset}"\fP
\fRwidth and height of the image

Use this option to specify the width and height of raw images whose dimensions
are unknown such as \fBGRAY\fP,
\fBRGB\fP, or \fBCMYK\fP. In addition
to width and height, use
\fB-size\fP with an offset to skip any header information in
the image or tell the number of colors in a \fBMAP\fP image
file, (e.g. -size 640x512+256).


For Photo CD images, choose from these sizes:

     192x128
     384x256
     768x512
     1536x1024
     3072x2048

Finally, use this option to choose a particular resolution layer of a JBIG
or JPEG image (e.g. -size 1024x768).

.TP
.B "-solarize \fI<factor>"\fP
\fRnegate all pixels above the threshold level

Specify \fIfactor\fP as the
percent threshold of the intensity (0 - 99.9%).


This option produces a \fIsolarization\fP effect seen when exposing a
photographic film to light during the development process.

.TP
.B "-spread \fI<amount>"\fP
\fRdisplace image pixels by a random amount

\fIAmount\fP defines the size of the neighborhood around each pixel to
choose a candidate pixel to swap.

.TP
.B "-stegano \fI<offset>"\fP
\fRhide watermark within an image

Use an offset to start the image hiding some number of pixels from the
beginning of the image.  Note this offset and the image size.  You will
need this information to recover the steganographic image
(e.g. display -size 320x256+35 stegano:image.png).

.TP
.B "-stereo"
\fRcomposite two images to create a stereo anaglyph

The left side of the stereo pair is saved as the red channel of the output
image.  The right side is saved as the green channel.  Red-green stereo
glasses are required to properly view the stereo image.

.TP
.B "-stroke \fI<color>"\fP
\fRcolor to use when stroking a graphic primitive

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.

See \fB-draw\fP for further
details.

.TP
.B "-strokewidth \fI<value>"\fP
\fRset the stroke width

See \fB-draw\fP for further details.

.TP
.B "-swirl \fI<degrees>"\fP
\fRswirl image pixels about the center

\fIDegrees\fP defines the tightness of the swirl.

.TP
.B "-text_font \fI<name>"\fP
\fRfont for writing fixed-width text

Specifies the name of the preferred font to use in fixed (typewriter style)
formatted text.  The default is 14 point \fICourier\fP.


You can tag a font to specify whether it is a Postscript, Truetype, or
OPTION1 font.  For example, Courier.ttf is a Truetype font
and x:fixed is OPTION1. 

.TP
.B "-texture \fI<filename>"\fP
\fRname of texture to tile onto the image background
.TP
.B "-threshold \fI<value>"\fP
\fRthreshold the image

Create a bi-level image such that any pixel intensity that is equal or
exceeds the threshold is reassigned the maximum intensity otherwise the
minimum intensity.

.TP
.B "-tile \fI<filename>"\fP
\fRtile image when filling a graphic primitive
.TP
.B "-tile \fI<geometry>"\fP
\fRlayout of images
.TP
.B "-title \fI<string>"\fP
\fRassign a title to the displayed image

Use this option to assign a specific title to the image. This is assigned
to the image window and is typically displayed in the window title bar.
Optionally you can include the image filename, type, width, height, or
other image attribute by embedding special format characters:

     %b   file size
     %c   comment
     %d   directory
     %e   filename extention
     %f   filename
     %h   height
     %i   input filename
     %k   number of unique colors
     %l   label
     %m   magick
     %n   number of scenes
     %o   output filename
     %p   page number
     %q   quantum depth
     %s   scene number
     %t   top of filename
     %u   unique temporary filename
     %w   width
     %x   x resolution
     %y   y resolution
     %#   signature
     \\n   newline
     \\r   carriage return

For example,


     -title "%m:%f %wx%h"

produces an image title of MIFF:bird.miff 512x480 for an image
titled bird.miff and whose width is 512 and height is 480.

.TP
.B "-transparent \fI<color>"\fP
\fRmake this color transparent within the image

The color is specified using the format described in the "Color Names"
section of \fIX(1)\fP.
.TP
.B "-treedepth \fI<value>"\fP
\fRtree depth for the color reduction algorithm

Normally, this integer value is zero or one. A zero or one tells display
to choose an optimal tree depth for the color reduction algorithm

An optimal depth generally allows the best representation of the source
image with the fastest computational speed and the least amount of memory.
However, the default depth is inappropriate for some images. To assure
the best representation, try values between 2 and 8 for this parameter.
Refer to
quantize for more details.


The \fB-colors\fP or \fB-monochrome\fP option is required for this option
to take effect.

.TP
.B "-trim"
\fRtrim an image

This option removes any edges that are exactly the same color as the
corner pixels.  Use \fB-fuzz\fP to make \fB-trim\fP remove edges that
are nearly the same color as the corner pixels.
.TP
.B "-type \fI<type>"\fP
\fRthe image type

Choose from:
\fBBilevel\fP, \fBGrayscale\fP, \fBPalette\fP,
\fBPaletteMatte\fP, \fBTrueColor\fP, \fBTrueColorMatte\fP,
\fBColorSeparation\fP, \fBColorSeparationMatte\fP, or \fBOptimize\fP.

.TP
.B "-update \fI<seconds>"\fP
\fR
detect when image file is modified and redisplay.

Suppose that while you are displaying an image the file that is currently
displayed is over-written.
\fBdisplay\fP will automatically detect that
the input file has been changed and update the displayed image accordingly.

.TP
.B "-units \fI<type>"\fP
\fRthe type of image resolution

Choose from: \fBUndefined\fP, \fBPixelsPerInch\fP, or
\fBPixelsPerCentimeter\fP.

.TP
.B "-unsharp \fI<radius>x<sigma>"\fP
\fRsharpen the image with an unsharp mask operator

Use the given radius and standard deviation (sigma).

.TP
.B "-use_pixmap"
\fRuse the pixmap
.TP
.B "-verbose"
\fRprint detailed information about the image

This information is printed: image scene number; image name; image size;
the image class (\fIDirectClass\fP or \fIPseudoClass\fP); the total number
of unique colors; and the number of seconds to read and transform the image.
Refer to miff for a description of the image class.


If \fB-colors\fP is also specified, the total unique colors in the image
and color reduction error values are printed. Refer to quantize
for a description of these values.

.TP
.B "-view \fI<string>"\fP
\fRFlashPix viewing parameters
.TP
.B "-visual \fI<type>"\fP
\fRanimate images using this X visual type

Choose from these visual classes:


     StaticGray
     GrayScale
     StaticColor
     PseudoColor
     TrueColor
     DirectColor
     default
     visual id

The X server must support the visual you choose, otherwise an error occurs.
If a visual is not specified, the visual class that can display the most
simultaneous colors on the default screen is chosen.

.TP
.B "-watermark \fI<brightness>x<saturation>"\fP
\fRpercent brightness and saturation of a watermark
.TP
.B "-wave \fI<amplitude>x<wavelength>"\fP
\fRalter an image along a sine wave

Specify \fIamplitude\fP and \fIwavelength\fP to effect the characteristics
of the wave.

.TP
.B "-window \fI<id>"\fP
\fRmake image the background of a window

\fIid\fP can be a window id or name.  Specify \fBroot\fP to
select X's root window as the target window.


By default the image is tiled onto the background of the target
window.   If \fBbackdrop\fP or \fB-geometry\fP are
specified, the image is surrounded by the background color.  Refer to
\fBX RESOURCES\fP for details.


The image will not display on the root window if the image has more
unique colors than the target window colormap allows.  Use
\fB-colors\fP to reduce the number of colors.

.TP
.B "-window_group"
\fRspecify the window group
.TP
.B "-write \fI<filename>"\fP
\fRwrite  an image sequence [\fIconvert, composite\fP]

The image sequence following the \fB-write\fP \fIfilename\fPoption is 
written out, and then processing continues with the
same image in its current state if there are additional options.  To
restore the image to its original state after writing it, use
the \fB+write\fP \fIfilename\fP option.
.TP
.B "-write"
\fRwrite the image to a file [\fIdisplay\fP]

If \fIfile\fP already exists, you will be prompted as to whether it should
be overwritten.

By default, the image is written in the format that it was read in as.
To specify a particular image format, prefix \fIfile\fP with the image
type and a colon (e.g., ps:image) or specify the image type as the filename
suffix (e.g., image.ps). See convert(1) for a list of valid image formats.
Specify file as - for standard output. If file has the
extension \fB.Z\fP or
\fB.gz\fP, the file size is \fBcompressed\fP using with compress or
\fBgzip\fP
respectively. Precede the image file name with | to pipe to a system command.
If \fIfile\fP already exists, you will be prompted as to whether it should
be overwritten.

Use \fB-compress\fP to specify the type of image compression.

The equivalent X resource for this option is
\fBwriteFilename\fP (class \fBWriteFilename\fP).
See
"X Resources", below,
for details.
.SH FILES AND FORMATS</A>

By default, the image format is determined by its magic number, i.e., the
first few bytes of the file. To specify
a particular image format, precede the filename with an image format name
and a colon (\fIi.e.\fP\fBps:image\fP) or specify the image type as the
filename suffix.
The magic number takes precedence over the filename suffix
and the prefix takes precedence over the magic number and the suffix
in input files.
The prefix takes precedence over the filename
suffix in output files.  To read the "built-in" formats (GRANITE, H, LOGO,
NETSCAPE, PLASMA, and ROSE) use a prefix (including the colon) without a
filename or suffix.  To read the XC format, follow the colon with a color
specification.  To read the CAPTION format, follow the colon with a text
string or with a filename prefixed with the at symbol (\fB@\fP).


When you specify \fBX\fP as your image type, the filename has special
meaning. It specifies an X window by \fBid, name\fP, or
\fBroot\fP. If
no filename is specified, the window is selected by clicking the mouse
in the desired window.

Specify \fIinput_file\fP as \fB-\fP for standard input,
\fIoutput_file\fP
as \fB-\fP for standard output. If \fIinput_file\fP has the extension
\fB.Z\fP or
\fB.gz\fP, the file is uncompressed with \fBuncompress\fP or \fBgunzip\fP
respectively. If \fIoutput_file\fP has the extension \fB.Z\fP or
\fB.gz\fP,
the file is compressed using with \fIcompress\fP or \fIgzip\fP
respectively.

Finally, when running on platforms that allow it, precede the image file name
with \fB|\fP to pipe to or from a system command (this feature is not
available on VMS, Win32 and Macintosh platforms).

Use an optional index enclosed in brackets after an input file name to specify
a desired subimage of a multi-resolution image format like Photo CD
(e.g. img0001.pcd[4]) or a range for MPEG images
(e.g. video.mpg[50-75]). A subimage
specification can be disjoint (e.g. image.tiff[2,7,4]). For raw images,
specify a subimage with a geometry
(e.g. -size 640x512 image.rgb[320x256+50+50]).
Single images are written with the filename you specify. However, multi-part
images (e.g., a multi-page PostScript document with \fB+adjoin\fP specified)
are written
with the filename followed by a period (\fB.\fP) and the scene number.  You
can change this behavior by embedding a %0Nd, %0No,
or %0Nx \fIprintf\fP
format specification in the file name. For example,

    image%02d.miff

writes files \fIimage00.miff, image01.miff,\fP etc.

When running a commandline utility, you can
prepend an at sign @ to a filename to read a list of image
filenames from that file. This is convenient in the event you have too
many image filenames to fit on the command line.
.SH ENVIRONMENT
.TP
.B "DISPLAY"
\fRTo get the default host, display number, and screen.
.SH SEE ALSO

animate(1), display(1), animate(1), display(1), identify(1), import(1),
montage(1), mogrify(1), composite(1)

.SH COPYRIGHT

\fBCopyright (C) 2002 ImageMagick Studio\fP

\fBPermission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the ImageMagick
is furnished to do so, subject to the following conditions:\fP

\fBThe above copyright notice and this permission notice shall be included
in all copies or substantial portions of ImageMagick.\fP

\fBThe software is provided "as is", without warranty of any kind, express
or implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out
of or in connection with ImageMagick or the use or other dealings in
ImageMagick.\fP

\fBExcept as contained in this notice, the name of the
ImageMagick Studio LLC shall not be used in advertising or otherwise to
promote the sale, use or other dealings in ImageMagick without prior written
authorization from the ImageMagick Studio.\fP
.SH AUTHORS

\fIJohn Cristy, ImageMagick Studio LLC\fP.

