.TH import 1 "Date: 2002/02/15 01:00:00" "ImageMagick"
.SH NAME
import - capture some or all of an X server screen and save the image to
a file.
.SH SYNOPSIS

\fBimport\fP \fB[\fP \fIoptions\fP \fB... ]\fP \fIfile\fP
.SH DESCRIPTION

\fBImport\fP reads an image from any visible window on an X server and
outputs it as an image file. You can capture a single window, the entire
screen, or any rectangular portion of the screen.
Use \fIdisplay\fP
for redisplay, printing, editing, formatting, archiving, image processing,
etc. of the captured image.

The target window can be specified by id, name, or may be selected
by clicking the mouse in the desired window. If you press a button and
then drag, a rectangle will form which expands and contracts as the mouse
moves. To save the portion of the screen defined by the rectangle, just
release the button. The keyboard bell is rung once at the beginning of
the screen capture and twice when it completes.
.SH EXAMPLES

To select an X window or an area of the screen with the mouse and save it
in the MIFF image format to a file entitled window.miff, use:

    import window.miff

To select an X window or an area of the screen with the mouse and save it
in the Encapsulated Postscript format to include in another document, use:

    import figure.eps

To capture the entire X server screen in the JPEG image format in a file
entitled root.jpeg, without using the mouse, use:

    import -window root root.jpeg

To capture the 512x256 area at the upper right corner of the X server
screen in the PNG image format in a well-compressed file entitled corner.png,
without using the mouse,  use:

    import -window root -crop 512x256-0+0 -quality 90
           corner.png
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect until it is explicitly changed by specifying
the option again with a different effect.

\fBImport\fP options can appear on the command line or in your
X resources file. See \fIX(1)\fP. Options on the command line supersede
values specified in your X resources file.

For a more detailed description of each option, see
\fIImageMagick(1)\fP.

.TP
.B "-bordercolor \fI<color>"\fP
\fRthe border color
.TP
.B "-cache \fI<threshold>"\fP
\fRmegabytes of memory available to the pixel cache
.TP
.B "-colors \fI<value>"\fP
\fRpreferred number of colors in the image
.TP
.B "-colorspace \fI<value>"\fP
\fRthe type of colorspace
.TP
.B "-comment \fI<string>"\fP
\fRannotate an image with a comment
.TP
.B "-crop \fI<width>x<height>{+-}<x>{+-}<y>{%}"\fP
\fRpreferred size and location of the cropped image
.TP
.B "-debug"
\fRenable debug printout
.TP
.B "-delay \fI<1/100ths of a second>"\fP
\fRdisplay the next image after pausing
.TP
.B "-density \fI<width>x<height>"\fP
\fRvertical and horizontal resolution in pixels of the image
.TP
.B "-depth \fI<value>"\fP
\fRdepth of the image
.TP
.B "-descend"
\fRobtain image by descending window hierarchy
.TP
.B "-display \fI<host:display[.screen]>"\fP
\fRspecifies the X server to contact
.TP
.B "-dispose \fI<method>"\fP
\fRGIF disposal method
.TP
.B "-dither"
\fRapply Floyd/Steinberg error diffusion to the image
.TP
.B "-endian \fI<type>"\fP
\fRspecify endianness (MSB or LSB) of output image
.TP
.B "-frame"
\fRinclude the X window frame in the imported image
.TP
.B "-geometry \fI<width>x<height>{+-}<x>{+-}<y>{%}{@} {!}{<}{>}"\fP
\fRpreferred size and location of the Image window.
.TP
.B "-help"
\fRprint usage instructions
.TP
.B "-interlace \fI<type>"\fP
\fRthe type of interlacing scheme
.TP
.B "-label \fI<name>"\fP
\fRassign a label to an image
.TP
.B "-monochrome"
\fRtransform the image to black and white
.TP
.B "-negate"
\fRreplace every pixel with its complementary color
.TP
.B "-page \fI<width>x<height>{+-}<x>{+-}<y>{%}{!}{<}{>}"\fP
\fRsize and location of an image canvas
.TP
.B "-pause \fI<seconds>"\fP
\fRpause between snapshots [import]
.TP
.B "-ping"
\fRefficiently determine image characteristics
.TP
.B "-pointsize \fI<value>"\fP
\fRpointsize of the Postscript, OPTION1, or TrueType font
.TP
.B "-quality \fI<value>"\fP
\fRJPEG/MIFF/PNG compression level
.TP
.B "-resize \fI<width>x<height>{+-}<x>{+-}<y>{%}{@}{!}{<}{>}"\fP
\fRresize and locate an image
.TP
.B "-rotate \fI<degrees{<}{>}>"\fP
\fRapply Paeth image rotation to the image
.TP
.B "-scene \fI<value>"\fP
\fRset scene number
.TP
.B "-screen"
\fRspecify the screen to capture
.TP
.B "-silent"
\fRoperate silently
.TP
.B "-snaps \fI<value>"\fP
\fRnumber of screen snapshots
.TP
.B "-transparent \fI<color>"\fP
\fRmake this color transparent within the image
.TP
.B "-trim"
\fRtrim an image
.TP
.B "-verbose"
\fRprint detailed information about the image
.SH ENVIRONMENT
.TP
.B "DISPLAY"
.SH SEE ALSO

animate(1), display(1), composite(1), conjure(1), convert(1), identify(1),
mogrify(1), montage(1)

.SH COPYRIGHT

\fBCopyright (C) 2002 ImageMagick Studio\fP

\fBPermission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the ImageMagick
is furnished to do so, subject to the following conditions:\fP

\fBThe above copyright notice and this permission notice shall be included
in all copies or substantial portions of ImageMagick.\fP

\fBThe software is provided "as is", without warranty of any kind, express
or implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out
of or in connection with ImageMagick or the use or other dealings in
ImageMagick.\fP

\fBExcept as contained in this notice, the name of the
ImageMagick Studio LLC shall not be used in advertising or otherwise to
promote the sale, use or other dealings in ImageMagick without prior written
authorization from the ImageMagick Studio.\fP
.SH AUTHORS

\fIJohn Cristy, ImageMagick Studio LLC\fP.

