.TH import 1 "Date: 2002/01/01 01:00:00" "ImageMagick"
.SH NAME
import - capture some or all of an X server screen and save the image to
a file.
.SH SYNOPSIS

\fBimport\fP \fB[\fP \fIoptions\fP \fB... ]\fP \fIfile\fP
.SH DESCRIPTION

\fBImport\fP reads an image from any visible window on an X server and
outputs it as an image file. You can capture a single window, the entire
screen, or any rectangular portion of the screen.
Use \fIdisplay\fP
for redisplay, printing, editing, formatting, archiving, image processing,
etc. of the captured image.

The target window can be specified by id, name, or may be selected
by clicking the mouse in the desired window. If you press a button and
then drag, a rectangle will form which expands and contracts as the mouse
moves. To save the portion of the screen defined by the rectangle, just
release the button. The keyboard bell is rung once at the beginning of
the screen capture and twice when it completes.
.SH EXAMPLES

To select an X window or an area of the screen with the mouse and save it
in the MIFF image format to a file entitled window.miff, use:

    import window.miff

To select an X window or an area of the screen with the mouse and save it
in the Encapsulated Postscript format to include in another document, use:

    import figure.eps

To capture the entire X server screen in the JPEG image format in a file
entitled root.jpeg, without using the mouse, use:

    import -window root root.jpeg

To capture the 512x256 area at the upper right corner of the X server
screen in the PNG image format in a well-compressed file entitled corner.png,
without using the mouse,  use:

    import -window root -crop 512x256-0+0 -quality 90 corner.png
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect until it is explicitly changed by specifying
the option again with a different effect.

\fBImport\fP options can appear on the command line or in your
X resources file. See \fIX(1)\fP. Options on the command line supersede
values specified in your X resources file.
.TP
.B "-border \fI<width>x<height>"\fP
\fRsurround the image with a border of color

See \fB-geometry\fP for details
about the geometry specification.

.TP
.B "-bordercolor \fI<color>"\fP
\fRthe border color
.TP
.B "-cache \fI<threshold>"\fP
\fRmegabytes of memory available to the pixel cache

Image pixels are stored in memory until 80 megabytes of memory have been
consumed. Subsequent pixel operations are cached on disk. Operations to
memory are significantly faster but if your computer does not have a sufficient
amount of free memory you may want to adjust this threshold value.

.TP
.B "-colors \fI<value>"\fP
\fRpreferred number of colors in the image

The actual number of colors in the image may be less than your request,
but never more. Note, this is a color reduction option. Images with less
unique colors than specified with this option will have any duplicate or
unused colors removed. Refer to quantize for
more details.


Note, options \fB-dither\fP, \fB-colorspace\fP, and \fB-treedepth\fP
affect the color reduction algorithm.

.TP
.B "-colorspace \fI<value>"\fP
\fRthe type of colorspace

Choices are: \fBGRAY\fP, \fBOHTA\fP, \fBRGB\fP,
\fBTransparent\fP,
\fBXYZ\fP,
\fBYCbCr\fP, \fBYIQ\fP, \fBYPbPr\fP,
\fBYUV\fP, or \fBCMYK\fP.


Color reduction, by default, takes place in the RGB color space. Empirical
evidence suggests that distances in color spaces such as YUV or YIQ correspond
to perceptual color differences more closely than do distances in RGB space.
These color spaces may give better results when color reducing an image.
Refer to quantize for more details.


The \fBTransparent\fP color space behaves uniquely in that it preserves
the matte channel of the image if it exists.


The \fB-colors\fP or \fB-monochrome\fP option is required for this
option to take effect.

.TP
.B "-comment \fI<string>"\fP
\fRannotate an image with a comment

Use this option to assign a specific comment to the image. You can include the
image filename, type, width, height, or other image attribute by embedding
special format characters:


     %b   file size
     %c   comment
     %d   directory
     %e   filename extention
     %f   filename
     %h   height
     %i   input filename
     %k   number of unique colors
     %l   label
     %m   magick
     %n   number of scenes
     %o   output filename
     %p   page number
     %q   quantum depth
     %s   scene number
     %t   top of filename
     %u   unique temporary filename
     %w   width
     %x   x resolution
     %y   y resolution
     \\n   newline
     \\r   carriage return

For example,


     -comment "%m:%f %wx%h"

produces an image comment of \fBMIFF:bird.miff 512x480\fP for an image
titled \fBbird.miff\fP and whose width is 512 and height is 480.


If the first character of \fIstring\fP is \fI@\fP, the image comment
is read from a file titled by the remaining characters in the string.

.TP
.B "-crop \fI<width>x<height>{+-}<x offset>{+-}<y offset>{%}"\fP
\fRpreferred size and location of the cropped image

See \fB-geometry\fP for details
about the geometry specification.


The width and height give the size of the image that remains after cropping,
and the offsets give the location of the top left corner of the cropped
image with respect to the original image.  To specify the amount to be
removed, use \fB-shave\fP instead.


To specify a percentage width or height to be removed instead, append
\fB%\fP. For example
to crop the image by ten percent (five percent on each side of the image),
use \fB-crop 10%\fP.


Use cropping to apply image processing options to, or display, a particular
area of an image.


The x and y offsets specify the location of the upper left corner of
the cropping region measured downward and rightward with respect to the
upper left corner of the image.
If the \fP-gravity\fP option is present with \fINorthEast, East,\fP
or \fISouthEast\fP
gravity, it gives the distance leftward from the right edge
of the image to the right edge of the cropping region.  Similarly, if
the \fB-gravity\fP option is present with \fISouthWest, South,\fP
or \fISouthEast\fP
gravity, the distance is measured upward between the bottom
edges.

Omit the x and y offset to generate one or more subimages of a uniform
size.

.TP
.B "-debug"
\fRenable debug printout
.TP
.B "-delay \fI<1/100ths of a second>"\fP
\fRdisplay the next image after pausing

This option is useful for regulating the animation of image sequences
\fIDelay/100\fP seconds must expire before the display
of the next image. The default is no delay between each showing of the
image sequence. The maximum delay is 65535.


You can specify a delay range (e.g. \fI-delay 10-500\fP) which sets the
minimum and maximum delay.

.TP
.B "-density \fI<width>x<height>"\fP
\fRvertical and horizontal resolution in pixels of the image

This option specifies an image density when decoding a \fIPostScript\fP
or Portable Document page. The default is 72 dots per inch in the horizontal
and vertical direction. This option is used in concert with \fB-page\fP.

.TP
.B "-depth \fI<value>"\fP
\fRdepth of the image

This is the number of bits in a color sample within a pixel. The only
acceptable values are 8 or 16.  Use this option to specify the depth of
raw images whose depth is unknown such as GRAY, RGB, or CMYK, or to change
the depth of any image after it has been read.

.TP
.B "-descend"
\fRobtain image by descending window hierarchy
.TP
.B "-display \fI<host:display[.screen]>"\fP
\fRspecifies the X server to contact
.TP
.B "-dispose \fI<method>"\fP
\fRGIF disposal method

Here are the valid methods:


     0     No disposal specified.
     1     Do not dispose between frames.      
     2     Overwrite frame with background color from header.
     3     Overwrite with previous frame.
.TP
.B "-dither"
\fRapply Floyd/Steinberg error diffusion to the image

The basic strategy of dithering is to trade intensity resolution for spatial
resolution by averaging the intensities of several neighboring pixels.
Images which suffer from severe contouring when reducing colors can be
improved with this option.


The \fB-colors\fP or \fB-monochrome\fP option is required for this option
to take effect.


Use \fB+dither\fP to turn off dithering and to render Postscript without
text or graphic aliasing.

.TP
.B "-frame"
\fRinclude the X window frame in the imported image
.TP
.B "-geometry \fI<width>x<height>{+-}<x offset>{+-}<y offset>{%}{@}{!}{<}{>}"\fP
\fRpreferred size and location of the Image window.

By default, the window size is the image
size and the location is chosen by you when it is mapped.


By default, the width and height are maximum values. That is, the image
is expanded or contracted to fit the width and height value while maintaining
the aspect ratio of the image. \fIAppend an exclamation point to the geometry
to force the image size to exactly the size you specify\fP. For example,
if you specify 640x480! the image width is set to 640 pixels and
height to 480.


If only the width is specified, the width assumes the
value and the height is chosen to maintain the aspect ratio of the image.
Similarly, if only the height is specified (e.g., -geometry x256),
the width is chosen to maintain the aspect ratio. 


To specify a percentage width or height instead, append %. The image size
is multiplied by the width and height percentages to obtain the final image
dimensions. To increase the size of an image, use a value greater than
100 (e.g. 125%). To decrease an image's size, use a percentage less than
100.


Use @ to specify the maximum area in pixels of an image.


Use > to change the dimensions of the image \fIonly\fP if
its size exceeds the geometry specification. < resizes the image
\fIonly\fP
if its dimensions is less than the geometry specification. For example,
if you specify '640x480>' and the image size is 512x512, the image
size does not change. However, if the image is 1024x1024, it is resized
to 640x480.  Enclose the geometry specification in quotation marks to
prevent the > or > from being interpreted by your shell
as a file redirection.


When used as a \fIconvert\fP, \fIimport\fP or \fImogrify\fP option,
\fB-geometry\fP
specifies the size of the output image and the offsets, if present, are ignored.

.TP
.B "-help"
\fRprint usage instructions
.TP
.B "-interlace \fI<type>"\fP
\fRthe type of interlacing scheme

Choices are: \fBNone, Line, Plane,\fP
or \fBPartition\fP. The default is \fBNone\fP.


This option is used to specify the type of interlacing scheme for raw image
formats such as \fBRGB\fP or \fBYUV\fP. \fBNone\fP means do not interlace
(RGBRGBRGBRGBRGBRGB...), \fBLine\fP uses scanline interlacing
(RRR...GGG...BBB...RRR...GGG...BBB...),
and \fBPlane\fP uses plane interlacing (RRRRRR...GGGGGG...BBBBBB...).
\fBPartition\fP
is like plane except the different planes are saved to individual files
(e.g. image.R, image.G, and image.B).


Use \fBLine\fP or \fBPlane\fP to create an
\fBinterlaced PNG\fP or \fB GIF\fP or
\fBprogressive JPEG\fP image.

.TP
.B "-label \fI<name>"\fP
\fRassign a label to an image

Use this option to assign a specific label to the image. Optionally you
can include the image filename, type, width, height, or other image attribute
by embedding special format character. See \fB-comment\fP for details.


For example,


     -label "%m:%f %wx%h"

produces an image label of \fBMIFF:bird.miff 512x480\fP for an image titled
\fBbird.miff\fP
and whose width is 512 and height is 480.


If the first character of \fIstring\fP is \fI@\fP, the image label is
read from a file titled by the remaining characters in the string.


When converting to \fIPostScript\fP, use this option to specify a header
string to print above the image. Specify the label font with
\fB-font\fP.

.TP
.B "-monochrome"
\fRtransform the image to black and white
.TP
.B "-negate"
\fRreplace every pixel with its complementary color

The red, green, and blue intensities of an image are negated.
White becomes black,
yellow becomes blue, etc.
Use \fB+negate\fP
to only negate the grayscale pixels of the image.

.TP
.B "-page \fI<width>x<height>{+-}<x offset>{+-}<y offset>{%}{!}{<}{>}"\fP
\fRsize and location of an image canvas

Use this option to specify the dimensions of the
\fIPostScript\fP page
in dots per inch or a TEXT page in pixels. The choices for a Postscript
page are:


     11x17         792  1224 
     Ledger       1224   792    
     Legal         612  1008
     Letter        612   792
     LetterSmall   612   792
     ArchE        2592  3456
     ArchD        1728  2592
     ArchC        1296  1728
     ArchB         864  1296
     ArchA         648   864
     A0           2380  3368
     A1           1684  2380
     A2           1190  1684
     A3            842  1190
     A4            595   842
     A4Small       595   842
     A5            421   595
     A6            297   421
     A7            210   297
     A8            148   210
     A9            105   148
     A10            74   105
     B0           2836  4008
     B1           2004  2836
     B2           1418  2004
     B3           1002  1418
     B4            709  1002
     B5            501   709
     C0           2600  3677
     C1           1837  2600
     C2           1298  1837
     C3            918  1298
     C4            649   918
     C5            459   649
     C6            323   459
     Flsa          612   936 
     Flse          612   936
     HalfLetter    396   612

For convenience you can specify the page size by media (e.g. A4, Ledger,
etc.). Otherwise, \fB-page\fP behaves much like
\fB-geometry\fP (e.g.  -page letter+43+43>).


To position a GIF image, use \fB-page\fP\fI{+-}<x offset>{+-}<y
offset>\fP (e.g. -page +100+200).


For a Postscript page, the image is sized as in \fB-geometry\fP and positioned
relative to the lower left hand corner of the page by
{+-}<\fBx\fP\fIoffset\fP>{+-}<\fBy\fP
\fIoffset>\fP. Use
-page 612x792>, for example, to center the
image within the page. If the image size exceeds the Postscript page, it
is reduced to fit the page.
The default gravity for the \fB-page\fP
option is \fISouthWest\fP, i.e., positive \fBx\fP and
\fBy\fP \fIoffset\fP are measured rightward and upward from the bottom
left corner of the page, unless the \fB-gravity\fP option is present with
a value other than \fISouthWest\fP.


The default page dimensions for a TEXT image is 612x792.


This option is used in concert with \fB-density\fP.

.TP
.B "-ping"
\fRefficiently determine image characteristics
.TP
.B "-pointsize \fI<value>"\fP
\fRpointsize of the Postscript, OPTION1, or TrueType font
.TP
.B "-quality \fI<value>"\fP
\fRJPEG/MIFF/PNG compression level

For the JPEG image format, quality is 0 (worst) to 100 (best). The default
quality is 75.


Quality for the MIFF and PNG image format sets the amount of image compression
(quality / 10) and filter-type (quality % 10). Compression quality values
range from 0 (worst) to 100 (best). If filter-type is 4 or less, the specified
filter-type is used for all scanlines:


     0: none
     1: sub
     2: up
     3: average
     4: Paeth

If filter-type is 5, adaptive filtering is used when quality is greater
than 50 and the image does not have a color map, otherwise no filtering
is used.


If filter-type is 6 or more, adaptive filtering with \fIminimum-sum-of-absolute-values\fP
is used.


The default is quality is 75. Which means nearly the best compression with
adaptive filtering.


For further information, see the PNG
specification.

.TP
.B "-resize \fI<width>x<height>{+-}<x offset>{+-}<y offset>{%}{@}{!}{<}{>}"\fP
\fRresize and locate an image

This is an alias for the \fB-geometry\fP option and it behaves in the
same manner. If the \fB-filter\fP option precedes the \fB-resize\fP
option, the specified filter is used.
.TP
.B "-rotate \fI<degrees{<}{>}>"\fP
\fRapply Paeth image rotation to the image

Use > to rotate the image only if its width exceeds the height.
< rotates the image \fIonly\fP if its width is less than the
height. For example, if you specify -rotate "-90>" and the image
size is 480x640, the image is not rotated.  However, if the
image is 640x480, it is rotated by -90 degrees.  If you use > or
<, enclose it in quotation marks to prevent it from being
misinterpreted as a file redirection.


Empty triangles left over from rotating the image are filled with the color
defined as \fBbackground\fP (class \fBbackgroundColor\fP). See \fIX(1)\fP
for details.

to specify an image sequence with a single filename. See
the discussion of \fIfile\fP below for details.
.TP
.B "-scene \fI<value>"\fP
\fRnumber of screen snapshots

Use this option
to grab more than one image from the X server screen, to create
an animation sequence.
.TP
.B "-screen"
\fRspecify the screen to capture

This option indicates that the GetImage request used to obtain the image
should be done on the root window, rather than directly on the specified
window.  In this way, you can obtain pieces of other windows that overlap
the specified window, and more importantly, you can capture menus or other
popups that are independent windows but appear over the specified window.
.TP
.B "-silent"
\fRoperate silently
.TP
.B "-transparent \fI<color>"\fP
\fRmake this color transparent within the image
.TP
.B "-trim"
\fRtrim an image

This option removes any edges that are exactly the same color as the
corner pixels.  Use \fB-fuzz\fP to make \fB-trim\fP remove edges that
are nearly the same color as the corner pixels.
.TP
.B "-verbose"
\fRprint detailed information about the image
.SH ENVIRONMENT
.TP
.B "DISPLAY"
.SH SEE ALSO

animate(1), display(1), composite(1), conjure(1), convert(1), identify(1),
mogrify(1), montage(1)

.SH COPYRIGHT

\fBCopyright (C) 2002 ImageMagick Studio\fP

\fBPermission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the ImageMagick
is furnished to do so, subject to the following conditions:\fP

\fBThe above copyright notice and this permission notice shall be included
in all copies or substantial portions of ImageMagick.\fP

\fBThe software is provided "as is", without warranty of any kind, express
or implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out
of or in connection with ImageMagick or the use or other dealings in
ImageMagick.\fP

\fBExcept as contained in this notice, the name of the
ImageMagick Studio LLC shall not be used in advertising or otherwise to
promote the sale, use or other dealings in ImageMagick without prior written
authorization from the ImageMagick Studio.\fP
.SH AUTHORS

\fIJohn Cristy, ImageMagick Studio LLC\fP.

