.ad l
.nh
.TH iptcutil 1 "1 October 2001" "ImageMagick"
.SH NAME
iptcutil - convert between IPTC binary and a "special" IPTC text file format.
.SH SYNOPSIS
.B "iptcutil"
-t | -b [-i file] [-o file] <input >output
.SH DESCRIPTION
\fBiptcutil\fP supports the creation of the IPTC binary file format
from a text file format. It also supports the conversion of the IPTC
binary file format into the equivalent text file format.
.SH OPTIONS
.TP
.B "-t
Input file is a text file.
.TP
.B "-b"
Input file is a binary IPTC file.
.TP
.B "-i \fBfile\fP"
Input file to use.  If this option is not specified input is taken
from the standard input.
.TP
.B "-o \fBfile\fP"
Output file to use.  If this option is not specified then output is
sent to the standard output.
.TP

.B IPTC Field Names

The following field tag numbers and names are supported:

.nf

    5    Image Name
    7    Edit Status
    10   Priority
    15   Category
    20   Supplemental Category
    22   Fixture Identifier
    25   Keyword
    30   Release Date
    35   Release Time
    40   Special Instructions
    45   Reference Service
    47   Reference Date
    50   Reference Number
    55   Created Date
    60   Created Time
    65   Originating Program
    70   Program Version
    75   Object Cycle
    80   Byline
    85   Byline Title
    90   City
    95   Province State
    100  Country Code
    101  Country
    103  Original Transmission Reference
    105  Headline
    110  Credit
    115  Source
    116  Copyright String
    120  Caption
    121  Local Caption
    122  Caption Writer
    200  Custom Field 1
    201  Custom Field 2
    202  Custom Field 3
    203  Custom Field 4
    204  Custom Field 5
    205  Custom Field 6
    206  Custom Field 7
    207  Custom Field 8
    208  Custom Field 9
    209  Custom Field 10
    210  Custom Field 11
    211  Custom Field 12
    212  Custom Field 13
    213  Custom Field 14
    214  Custom Field 15
    215  Custom Field 16
    216  Custom Field 17
    217  Custom Field 18
    218  Custom Field 19
    219  Custom Field 20

.fi


.SH SEE ALSO
.B
display(1), animate(1), montage(1), mogrify(1), convert(1), combine(1), xtp(1)
.SH COPYRIGHT
Copyright (C) 2001 ImageMagick Studio, a non-profit organization dedicated
to making software imaging solutions freely available.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the
ImageMagick is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of ImageMagick.

The software is provided "as is", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.  In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out of
or in connection with ImageMagick or the use or other dealings in
ImageMagick.

Except as contained in this notice, the name of the ImageMagick Studio
shall not be used in advertising or otherwise to promote the sale, use or
other dealings in ImageMagick without prior written authorization from the
ImageMagick Studio.
.SH AUTHORS
William T. Radcliffe, Corbis, billr@corbis.com
