.TH mogrify 1 "Date: 2002/02/15 01:00:00" "ImageMagick"
.SH NAME
mogrify - mogrify an image
.SH SYNOPSIS

\fBmogrify\fP \fB[\fP \fIoptions\fP \fB... ]\fP \fIfile ...\fP

.SH DESCRIPTION

\fBMogrify\fP transforms an image or a sequence of images. These transforms
include image scaling, image rotation, color reduction, and others. The
transmogrified image overwrites the original image. 

The graphics formats supported by \fBmogrify\fP are listed in
\fIImageMagick(1)\fP.
.SH EXAMPLES

To convert all the TIFF files in a particular directory to JPEG, use:

    mogrify -format jpeg *.tiff

To scale an image of a cockatoo to exactly 640 pixels in width and 480
pixels in height, use: 

    mogrify -geometry 640x480! cockatoo.miff
.SH OPTIONS

Options are processed in command line order. Any option you specify on
the command line remains in effect for the set of images that follows,
until the set is terminated by the appearance of any option or \fB-noop\fP.

For a more detailed description of each option, see
\fIImageMagick(1)\fP.

.TP
.B "-affine \fI<matrix>"\fP
\fRdrawing transform matrix
.TP
.B "-antialias"
\fRremove pixel aliasing
.TP
.B "-background \fI<color>"\fP
\fRthe background color
.TP
.B "-blur \fI<radius>x<sigma>"\fP
\fRblur the image with a gaussian operator
.TP
.B "-border \fI<width>x<height>"\fP
\fRsurround the image with a border of color
.TP
.B "-bordercolor \fI<color>"\fP
\fRthe border color
.TP
.B "-cache \fI<threshold>"\fP
\fRmegabytes of memory available to the pixel cache
.TP
.B "-channel \fI<type>"\fP
\fRthe type of channel
.TP
.B "-charcoal \fI<factor>"\fP
\fRsimulate a charcoal drawing
.TP
.B "-colorize \fI<value>"\fP
\fRcolorize the image with the pen color
.TP
.B "-colors \fI<value>"\fP
\fRpreferred number of colors in the image
.TP
.B "-colorspace \fI<value>"\fP
\fRthe type of colorspace
.TP
.B "-comment \fI<string>"\fP
\fRannotate an image with a comment
.TP
.B "-compress \fI<type>"\fP
\fRthe type of image compression
.TP
.B "-contrast"
\fRenhance or reduce the image contrast
.TP
.B "-crop \fI<width>x<height>{+-}<x>{+-}<y>{%}"\fP
\fRpreferred size and location of the cropped image
.TP
.B "-cycle \fI<amount>"\fP
\fRdisplace image colormap by amount
.TP
.B "-debug"
\fRenable debug printout
.TP
.B "-delay \fI<1/100ths of a second>"\fP
\fRdisplay the next image after pausing
.TP
.B "-density \fI<width>x<height>"\fP
\fRvertical and horizontal resolution in pixels of the image
.TP
.B "-depth \fI<value>"\fP
\fRdepth of the image
.TP
.B "-despeckle"
\fRreduce the speckles within an image
.TP
.B "-display \fI<host:display[.screen]>"\fP
\fRspecifies the X server to contact
.TP
.B "-dispose \fI<method>"\fP
\fRGIF disposal method
.TP
.B "-dither"
\fRapply Floyd/Steinberg error diffusion to the image
.TP
.B "-draw \fI<string>"\fP
\fRannotate an image with one or more graphic primitives
.TP
.B "-edge \fI<radius>"\fP
\fRdetect edges within an image
.TP
.B "-emboss"
\fRemboss an image
.TP
.B "-enhance"
\fRapply a digital filter to enhance a noisy image
.TP
.B "-equalize"
\fRperform histogram equalization to the image
.TP
.B "-fill \fI<color>"\fP
\fRcolor to use when filling a graphic primitive
.TP
.B "-filter \fI<type>"\fP
\fRuse this type of filter when resizing an image
.TP
.B "-flip"
\fRcreate a "mirror image"
.TP
.B "-flop"
\fRcreate a "mirror image"
.TP
.B "-font \fI<name>"\fP
\fRuse this font when annotating the image with text
.TP
.B "-format \fI<type>"\fP
\fRthe image format type
.TP
.B "-frame \fI<width>x<height>+<outer bevel width>+<inner bevel width>"\fP
\fRsurround the image with an ornamental border
.TP
.B "-fuzz \fI<distance>{%}"\fP
\fRcolors within this distance are considered equal
.TP
.B "-gamma \fI<value>"\fP
\fRlevel of gamma correction
.TP
.B "-gaussian \fI<radius>x<sigma>"\fP
\fRblur the image with a gaussian operator
.TP
.B "-geometry \fI<width>x<height>{+-}<x>{+-}<y>{%}{@} {!}{<}{>}"\fP
\fRpreferred size and location of the Image window.
.TP
.B "-gravity \fI<type>"\fP
\fRdirection primitive  gravitates to when annotating the image.
.TP
.B "-help"
\fRprint usage instructions
.TP
.B "-implode \fI<factor>"\fP
\fRimplode image pixels about the center
.TP
.B "-interlace \fI<type>"\fP
\fRthe type of interlacing scheme
.TP
.B "-label \fI<name>"\fP
\fRassign a label to an image
.TP
.B "-level \fI<value>"\fP
\fRadjust the level of image contrast
.TP
.B "-linewidth"
\fRthe line width for subsequent draw operations
.TP
.B "-list \fI<type>"\fP
\fRthe type of list
.TP
.B "-loop \fI<iterations>"\fP
\fRadd Netscape loop extension to your GIF animation
.TP
.B "-map \fI<filename>"\fP
\fRchoose a particular set of colors from this image
.TP
.B "-mask \fI<filename>"\fP
\fRSpecify a clipping mask
.TP
.B "-matte"
\fRstore matte channel if the image has one
.TP
.B "-mattecolor \fI<color>"\fP
\fRspecify the matte color
.TP
.B "-median \fI<radius>"\fP
\fRapply a median filter to the image
.TP
.B "-modulate \fI<value>"\fP
\fRvary the brightness, saturation, and hue of an image
.TP
.B "-monochrome"
\fRtransform the image to black and white
.TP
.B "-negate"
\fRreplace every pixel with its complementary color
.TP
.B "-noise \fI<radius|type>"\fP
\fRadd or reduce noise in an image
.TP
.B "-noop"
\fRNOOP (no option)
.TP
.B "-normalize"
\fRtransform image to span the full range of color values
.TP
.B "-opaque \fI<color>"\fP
\fRchange this color to the pen color within the image
.TP
.B "-page \fI<width>x<height>{+-}<x>{+-}<y>{%}{!}{<}{>}"\fP
\fRsize and location of an image canvas
.TP
.B "-paint \fI<radius>"\fP
\fRsimulate an oil painting
.TP
.B "-pen \fI<color>"\fP
\fRspecify the pen color for drawing operations
.TP
.B "-pointsize \fI<value>"\fP
\fRpointsize of the Postscript, OPTION1, or TrueType font
.TP
.B "-profile \fI<filename>"\fP
\fRadd ICM, IPTC, or generic profile  to image
.TP
.B "-quality \fI<value>"\fP
\fRJPEG/MIFF/PNG compression level
.TP
.B "-raise \fI<width>x<height>"\fP
\fRlighten or darken image edges
.TP
.B "-region \fI<width>x<height>{+-}<x>{+-}<y>"\fP
\fRapply options to a portion of the image
.TP
.B "-resize \fI<width>x<height>{+-}<x>{+-}<y>{%}{@}{!}{<}{>}"\fP
\fRresize and locate an image
.TP
.B "-roll \fI{+-}<x>{+-}<y>"\fP
\fRroll an image vertically or horizontally
.TP
.B "-rotate \fI<degrees{<}{>}>"\fP
\fRapply Paeth image rotation to the image
.TP
.B "-sample \fI<geometry>"\fP
\fRscale image with pixel sampling
.TP
.B "-scale \fI<geometry>"\fP
\fRscale the image.
.TP
.B "-scene \fI<value>"\fP
\fRset scene number
.TP
.B "-seed \fI<value>"\fP
\fRpseudo-random number generator seed value
.TP
.B "-segment \fI<cluster threshold>x<smoothing threshold>"\fP
\fRsegment an image
.TP
.B "-shade \fI<azimuth>x<elevation>"\fP
\fRshade the image using a distant light source
.TP
.B "-sharpen \fI<radius>x<sigma>"\fP
\fRsharpen the image
.TP
.B "-shave \fI<width>x<height>"\fP
\fRshave pixels from the image edges
.TP
.B "-shear \fI<x degrees>x<y degrees>"\fP
\fRshear the image along the X or Y axis
.TP
.B "-size \fI<width>x<height>{+offset}"\fP
\fRwidth and height of the image
.TP
.B "-solarize \fI<factor>"\fP
\fRnegate all pixels above the threshold level
.TP
.B "-spread \fI<amount>"\fP
\fRdisplace image pixels by a random amount
.TP
.B "-stroke \fI<color>"\fP
\fRcolor to use when stroking a graphic primitive
.TP
.B "-strokewidth \fI<value>"\fP
\fRset the stroke width
.TP
.B "-swirl \fI<degrees>"\fP
\fRswirl image pixels about the center
.TP
.B "-texture \fI<filename>"\fP
\fRname of texture to tile onto the image background
.TP
.B "-threshold \fI<value>"\fP
\fRthreshold the image
.TP
.B "-tile \fI<filename>"\fP
\fRtile image when filling a graphic primitive
.TP
.B "-transparent \fI<color>"\fP
\fRmake this color transparent within the image
.TP
.B "-treedepth \fI<value>"\fP
\fRtree depth for the color reduction algorithm
.TP
.B "-trim"
\fRtrim an image
.TP
.B "-type \fI<type>"\fP
\fRthe image type
.TP
.B "-units \fI<type>"\fP
\fRthe type of image resolution
.TP
.B "-unsharp \fI<radius>x<sigma>"\fP
\fRsharpen the image with an unsharp mask operator
.TP
.B "-verbose"
\fRprint detailed information about the image
.TP
.B "-view \fI<string>"\fP
\fRFlashPix viewing parameters
.TP
.B "-wave \fI<amplitude>x<wavelength>"\fP
\fRalter an image along a sine wave
.SH IMAGE SEGMENTATION

Use \fB-segment\fP to segment an image by analyzing the histograms of
the color components and identifying units that are homogeneous with the
fuzzy c-means technique. The scale-space filter analyzes the histograms
of the three color components of the image and identifies a set of classes.
The extents of each class is used to coarsely segment the image with thresholding.
The color associated with each class is determined by the mean color of
all pixels within the extents of a particular class. Finally, any unclassified
pixels are assigned to the closest class with the fuzzy c-means technique.

The fuzzy c-Means algorithm can be summarized as follows:

    
Build a histogram, one for each color component of the image.
    
For each histogram, successively apply the scale-space filter and build
an interval tree of zero crossings in the second derivative at each scale.
Analyze this scale-space "fingerprint" to determine which peaks or valleys
in the histogram are most predominant.
    
The fingerprint defines intervals on the axis of the histogram. Each interval
contains either a minima or a maxima in the original signal. If each color
component lies within the maxima interval, that pixel is considered "classified"
and is assigned an unique class number.
    
Any pixel that fails to be classified in the above thresholding pass is
classified using the fuzzy c-Means technique. It is assigned to one of
the classes discovered in the histogram analysis phase.


The fuzzy c-Means technique attempts to cluster a pixel by finding the
local minima of the generalized within group sum of squared error objective
function. A pixel is assigned to the closest class of which the fuzzy membership
has a maximum value.

For additional information see:
<bq>\fIYoung Won Lim, Sang Uk Lee\fP, ``\fBOn The Color Image Segmentation
Algorithm Based on the Thresholding and the Fuzzy c-Means Techniques\fP'',
Pattern Recognition, Volume 23, Number 9, pages 935-952, 1990.</bq>
.SH ENVIRONMENT
.TP
.B "DISPLAY"
\fRTo get the default host, display number, and screen.
.SH SEE ALSO

display(1), animate(1), identify(1), montage(1), convert(1),
composite(1)

.SH COPYRIGHT

\fBCopyright (C) 2002 ImageMagick Studio\fP

\fBPermission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the ImageMagick
is furnished to do so, subject to the following conditions:\fP

\fBThe above copyright notice and this permission notice shall be included
in all copies or substantial portions of ImageMagick.\fP

\fBThe software is provided "as is", without warranty of any kind, express
or implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.In no event shall
ImageMagick Studio be liable for any claim, damages or other liability,
whether in an action of contract, tort or otherwise, arising from, out
of or in connection with ImageMagick or the use or other dealings in
ImageMagick.\fP

\fBExcept as contained in this notice, the name of the
ImageMagick Studio LLC shall not be used in advertising or otherwise to
promote the sale, use or other dealings in ImageMagick without prior written
authorization from the ImageMagick Studio.\fP
.SH AUTHORS

\fIJohn Cristy, ImageMagick Studio LLC\fP.

