@echo off
@echo button ...
..\..\VisualMagick\bin\button
@echo
@echo demo ...
..\..\VisualMagick\bin\demo
@echo
@echo flip ...
..\..\VisualMagick\bin\flip
@echo
@echo shapes ...
..\..\VisualMagick\bin\shapes
