@echo off
set exedir=..\bin\
set srcdir=..\..\tests\
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff RGB 
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff rgb 
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff rgba 
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff cmy 
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff cmyk 
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff bGr 
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff Gbr 
%exedir%constitute -storagetype char %srcdir%input_truecolor.miff i 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff RGB 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff rgb 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff rgba 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff cmy 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff cmyk 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff bGr 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff Gbr 
%exedir%constitute -storagetype short %srcdir%input_truecolor.miff i 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff RGB 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff rgb 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff rgba 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff cmy 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff cmyk 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff bGr 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff Gbr 
%exedir%constitute -storagetype integer %srcdir%input_truecolor.miff i 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff RGB 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff rgb 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff rgba 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff cmy 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff cmyk 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff bGr 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff Gbr 
%exedir%constitute -storagetype long %srcdir%input_truecolor.miff i 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff RGB 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff rgb 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff rgba 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff cmy 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff cmyk 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff bGr 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff Gbr 
%exedir%constitute -storagetype float %srcdir%input_truecolor.miff i 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff RGB 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff rgb 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff rgba 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff cmy 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff cmyk 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff bGr 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff Gbr 
%exedir%constitute -storagetype double %srcdir%input_truecolor.miff i
