@echo off
..\bin\rwblob LOGO: AVS
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm AVS
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm AVS
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm AVS
..\bin\rwblob LOGO: BMP
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm BMP
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm BMP
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm BMP
..\bin\rwblob LOGO: CMYK
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm CMYK
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm CMYK
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm CMYK
..\bin\rwblob LOGO: DIB
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm DIB
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm DIB
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm DIB
..\bin\rwblob LOGO: FAX
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm FAX
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm FAX
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm FAX
..\bin\rwblob LOGO: FITS
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm FITS
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm FITS
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm FITS
..\bin\rwblob LOGO: GIF
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm GIF
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm GIF
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm GIF
..\bin\rwblob LOGO: GRAY
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm GRAY
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm GRAY
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm GRAY
: ..\bin\rwblob LOGO: HDF
: ..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm HDF
: ..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm HDF
: ..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm HDF
..\bin\rwblob LOGO: ICB
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm ICB
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm ICB
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm ICB
..\bin\rwblob LOGO: JBIG
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm JBIG
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm JBIG
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm JBIG
..\bin\rwblob LOGO: JPEG
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm JPEG
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm JPEG
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm JPEG
..\bin\rwblob LOGO: MIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm MIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm MIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm MIFF
..\bin\rwblob LOGO: MNG
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm MNG
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm MNG
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm MNG
..\bin\rwblob LOGO: MONO
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm MONO
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm MONO
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm MONO
..\bin\rwblob LOGO: MTV
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm MTV
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm MTV
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm MTV
..\bin\rwblob LOGO: P7
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm P7
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm P7
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm P7
..\bin\rwblob LOGO: PBM
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PBM
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PBM
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PBM
..\bin\rwblob LOGO: PCD
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PCD
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PCD
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PCD
..\bin\rwblob LOGO: PCDS
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PCDS
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PCDS
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PCDS
..\bin\rwblob LOGO: PCX
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PCX
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PCX
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PCX
..\bin\rwblob LOGO: PGM
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PGM
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PGM
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PGM
..\bin\rwblob LOGO: PICT
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PICT
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PICT
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PICT
..\bin\rwblob LOGO: PNG
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PNG
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PNG
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PNG
..\bin\rwblob LOGO: PNM
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PNM
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PNM
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PNM
..\bin\rwblob LOGO: PPM
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PPM
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PPM
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PPM
..\bin\rwblob LOGO: PSD
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PSD
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PSD
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PSD
..\bin\rwblob LOGO: PTIF
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm PTIF
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm PTIF
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm PTIF
..\bin\rwblob LOGO: RAS
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm RAS
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm RAS
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm RAS
..\bin\rwblob LOGO: RGB
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm RGB
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm RGB
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm RGB
..\bin\rwblob LOGO: RGBA
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm RGBA
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm RGBA
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm RGBA
..\bin\rwblob LOGO: SGI
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm SGI
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm SGI
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm SGI
..\bin\rwblob LOGO: SUN
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm SUN
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm SUN
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm SUN
..\bin\rwblob LOGO: TGA
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm TGA
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm TGA
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm TGA
..\bin\rwblob LOGO: TIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm TIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm TIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm TIFF
..\bin\rwblob LOGO: UYVY
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm UYVY
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm UYVY
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm UYVY
..\bin\rwblob LOGO: VDA
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm VDA
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm VDA
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm VDA
..\bin\rwblob LOGO: VICAR
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm VICAR
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm VICAR
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm VICAR
..\bin\rwblob LOGO: VIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm VIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm VIFF
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm VIFF
..\bin\rwblob LOGO: VST
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm VST
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm VST
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm VST
..\bin\rwblob LOGO: XBM
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm XBM
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm XBM
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm XBM
..\bin\rwblob LOGO: XPM
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm XPM
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm XPM
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm XPM
: ..\bin\rwblob LOGO: XWD
: ..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm XWD
: ..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm XWD
: ..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm XWD
..\bin\rwblob LOGO: YUV
..\bin\rwblob ..\..\PerlMagick\t\input_p4.pbm YUV
..\bin\rwblob ..\..\PerlMagick\t\input_p5.pgm YUV
..\bin\rwblob ..\..\PerlMagick\t\input_p6.ppm YUV
