@echo off
set srcdir=..\..\..\Magick++\tests
echo appendImages ...
..\..\bin\appendImages
echo attributes ...
..\..\bin\attributes
echo averageImages ...
..\..\bin\averageImages
echo coaleseImages ...
..\..\bin\coalesceImages
echo coderInfo ...
..\..\bin\coderInfo
echo color ...
..\..\bin\color
echo montageImages ...
..\..\bin\montageImages
echo morphImages ...
..\..\bin\morphImages
echo readWriteBlob ...
..\..\bin\readWriteBlob
echo readWriteImages ...
..\..\bin\readWriteImages
