@echo off
set srcdir=..\..\..\Magick++\demo
echo button ...
..\..\bin\button
echo demo ...
..\..\bin\demo
echo flip ...
..\..\bin\flip
echo gravity ...
..\..\bin\gravity
echo piddle ...
..\..\bin\piddle
echo shapes ...
..\..\bin\shapes
echo zoom point ...
..\..\bin\zoom point 600x600 %srcdir%\model.miff zoom_point_out.miff
echo zoom box ...
..\..\bin\zoom box 600x600 %srcdir%\model.miff zoom_box_out.miff
echo zoom triangle ...
..\..\bin\zoom triangle 600x600 %srcdir%\model.miff zoom_triangle_out.miff
echo zoom hermite ...
..\..\bin\zoom hermite 600x600 %srcdir%\model.miff zoom_hermite_out.miff
echo zoom hanning ...
..\..\bin\zoom hanning 600x600 %srcdir%\model.miff zoom_hanning_out.miff
echo zoom hamming ...
..\..\bin\zoom hamming 600x600 %srcdir%\model.miff zoom_hamming_out.miff
echo zoom blackman ...
..\..\bin\zoom blackman 600x600 %srcdir%\model.miff zoom_blackman_out.miff
echo zoom gaussian ...
..\..\bin\zoom gaussian 600x600 %srcdir%\model.miff zoom_gaussian_out.miff
echo zoom quadratic ...
..\..\bin\zoom quadratic 600x600 %srcdir%\model.miff zoom_quadratic_out.miff
echo zoom cubic ...
..\..\bin\zoom cubic 600x600 %srcdir%\model.miff zoom_cubic_out.miff
echo zoom catrm ...
..\..\bin\zoom catrm 600x600 %srcdir%\model.miff zoom_catrm_out.miff
echo zoom mitchell ...
..\..\bin\zoom mitchell 600x600 %srcdir%\model.miff zoom_mitchell_out.miff
echo zoom lanczos ...
..\..\bin\zoom lanczos 600x600 %srcdir%\model.miff zoom_lanczos_out.miff
echo zoom bessel ...
..\..\bin\zoom bessel 600x600 %srcdir%\model.miff zoom_bessel_out.miff
echo zoom sinc ...
..\..\bin\zoom sinc 600x600 %srcdir%\model.miff zoom_sinc_out.miff

