use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    'NAME'      => 'Image::Magick',
    'VERSION_FROM' => 'Magick.pm', # finds $VERSION
    'LIBS'      => ['-Le:\DevStudio\VC\lib -L..\magick -lIMagick.dll -L..\xlib\lib -lX11'],
    'DEFINE'    => '-D_VISUALC_ -D_WINDOWS',     # e.g., '-DHAVE_SOMETHING' 
    'INC'       => '-I..\magick -I..\xlib\include',
);
