rem file: ren_sstg.bat  date: 11/14/96
rem renames Structured Storage files to lower case
rem Must be run from the .BAT directory

ren ..\Source\CHANGES                                     changes
ren ..\Source\H                                           h
ren ..\Source\PROPS                                       props
ren ..\Source\TEST                                        test
ren ..\Source\UNIX                                        unix
ren ..\Source\ASCII.CXX                                   ascii.cxx
ren ..\Source\ASCII.HXX                                   ascii.hxx
ren ..\Source\BYTEORDR.HXX                                byteordr.hxx
ren ..\Source\CDOCFILE.CXX                                cdocfile.cxx
ren ..\Source\CHINST.CXX                                  chinst.cxx
ren ..\Source\COMMK.GCC                                   commk.gcc
ren ..\Source\COMMK.MSC                                   commk.msc
ren ..\Source\DBG.HXX                                     dbg.hxx
ren ..\Source\DEPEND.GCC                                  depend.gcc
ren ..\Source\DEPEND.MSC                                  depend.msc
ren ..\Source\DFBASIS.HXX                                 dfbasis.hxx
ren ..\Source\DFFUNCS.CXX                                 dffuncs.cxx
ren ..\Source\DFHEAD.CXX                                  dfhead.cxx
ren ..\Source\DFITER.CXX                                  dfiter.cxx
ren ..\Source\DFSTREAM.CXX                                dfstream.cxx
ren ..\Source\DIFAT.CXX                                   difat.cxx
ren ..\Source\DIR.CXX                                     dir.cxx
ren ..\Source\DIRP.CXX                                    dirp.cxx
ren ..\Source\DOCFILE.CXX                                 docfile.cxx
ren ..\Source\ENTRY.CXX                                   entry.cxx
ren ..\Source\EXPDF.CXX                                   expdf.cxx
ren ..\Source\EXPDF.HXX                                   expdf.hxx
ren ..\Source\EXPHEAD.CXX                                 exphead.cxx
ren ..\Source\EXPITER.CXX                                 expiter.cxx
ren ..\Source\EXPITER.HXX                                 expiter.hxx
ren ..\Source\EXPST.CXX                                   expst.cxx
ren ..\Source\EXPST.HXX                                   expst.hxx
ren ..\Source\FAT.CXX                                     fat.cxx
ren ..\Source\FUNCS.CXX                                   funcs.cxx
ren ..\Source\HEADER.CXX                                  header.cxx
ren ..\Source\ITER.CXX                                    iter.cxx
ren ..\Source\ITER.HXX                                    iter.hxx
ren ..\Source\LOGFILE.HXX                                 logfile.hxx
ren ..\Source\MAKEFILE                                    makefile
ren ..\Source\MAKEFILE.GCC                                makefile.gcc
ren ..\Source\MAKEFILE.MSC                                makefile.msc
ren ..\Source\MEM.CXX                                     mem.cxx
ren ..\Source\MREAD.HXX                                   mread.hxx
ren ..\Source\MSF.CXX                                     msf.cxx
ren ..\Source\MSFHEAD.CXX                                 msfhead.cxx
ren ..\Source\MSFITER.CXX                                 msfiter.cxx
ren ..\Source\MSTREAM.CXX                                 mstream.cxx
ren ..\Source\PAGE.CXX                                    page.cxx
ren ..\Source\REFILB.CXX                                  refilb.cxx
ren ..\Source\REFPROP.DEF                                 refprop.def
ren ..\Source\REFSTG.DEF                                  refstg.def
ren ..\Source\REXPDF.CXX                                  rexpdf.cxx
ren ..\Source\SSTREAM.CXX                                 sstream.cxx
ren ..\Source\STORAGE.CXX                                 storage.cxx
ren ..\Source\TAGS                                        tags
ren ..\Source\TIME.CXX                                    time.cxx
ren ..\Source\TIME.HXX                                    time.hxx
ren ..\Source\VECT.CXX                                    vect.cxx
ren ..\Source\WCHAR.C                                     wchar.c
ren ..\Source\H\CDOCFILE.HXX                              cdocfile.hxx
ren ..\Source\H\CHINST.HXX                                chinst.hxx
ren ..\Source\H\DBG.HXX                                   dbg.hxx
ren ..\Source\H\DFEXCEPT.HXX                              dfexcept.hxx
ren ..\Source\H\DFFUNCS.HXX                               dffuncs.hxx
ren ..\Source\H\DFMSP.HXX                                 dfmsp.hxx
ren ..\Source\H\DFVER.H                                   dfver.h
ren ..\Source\H\DIFAT.HXX                                 difat.hxx
ren ..\Source\H\DIR.HXX                                   dir.hxx
ren ..\Source\H\DIRFUNC.HXX                               dirfunc.hxx
ren ..\Source\H\DOCFILE.HXX                               docfile.hxx
ren ..\Source\H\DOCFILEP.HXX                              docfilep.hxx
ren ..\Source\H\ENTRY.HXX                                 entry.hxx
ren ..\Source\H\ERROR.HXX                                 error.hxx
ren ..\Source\H\FAT.HXX                                   fat.hxx
ren ..\Source\H\FUNCS.HXX                                 funcs.hxx
ren ..\Source\H\HANDLE.HXX                                handle.hxx
ren ..\Source\H\HEADER.HXX                                header.hxx
ren ..\Source\H\MEM.HXX                                   mem.hxx
ren ..\Source\H\MSF.HXX                                   msf.hxx
ren ..\Source\H\MSFFUNC.HXX                               msffunc.hxx
ren ..\Source\H\MSFITER.HXX                               msfiter.hxx
ren ..\Source\H\OLE.HXX                                   ole.hxx
ren ..\Source\H\PAGE.HXX                                  page.hxx
ren ..\Source\H\PITER.HXX                                 piter.hxx
ren ..\Source\H\PROPS.H                                   props.h
ren ..\Source\H\PROPSTM.HXX                               propstm.hxx
ren ..\Source\H\REF.HXX                                   ref.hxx
ren ..\Source\H\REFILB.HXX                                refilb.hxx
ren ..\Source\H\REVERT.HXX                                revert.hxx
ren ..\Source\H\REXPDF.HXX                                rexpdf.hxx
ren ..\Source\H\SSTREAM.HXX                               sstream.hxx
ren ..\Source\H\STORAGE.H                                 storage.h
ren ..\Source\H\STORAGEP.H                                storagep.h
ren ..\Source\H\TCHAR.H                                   tchar.h
ren ..\Source\H\VECT.HXX                                  vect.hxx
ren ..\Source\H\VECTFUNC.HXX                              vectfunc.hxx
ren ..\Source\H\WCHAR.H                                   wchar.h
ren ..\Source\PROPS\H                                     h
ren ..\Source\PROPS\CHRESULT.HXX                          chresult.hxx
ren ..\Source\PROPS\DEBTRACE.HXX                          debtrace.hxx
ren ..\Source\PROPS\DEPEND.GCC                            depend.gcc
ren ..\Source\PROPS\DEPEND.MSC                            depend.msc
ren ..\Source\PROPS\MAKEFILE                              makefile
ren ..\Source\PROPS\MAKEFILE.GCC                          makefile.gcc
ren ..\Source\PROPS\MAKEFILE.MSC                          makefile.msc
ren ..\Source\PROPS\NTPROP.CXX                            ntprop.cxx
ren ..\Source\PROPS\NTPROPB.CXX                           ntpropb.cxx
ren ..\Source\PROPS\OLECHAR.H                             olechar.h
ren ..\Source\PROPS\PCH.CXX                               pch.cxx
ren ..\Source\PROPS\PROPDBG.HXX                           propdbg.hxx
ren ..\Source\PROPS\PROPHDR.HXX                           prophdr.hxx
ren ..\Source\PROPS\PROPSTG.CXX                           propstg.cxx
ren ..\Source\PROPS\PROPSTG.HXX                           propstg.hxx
ren ..\Source\PROPS\PROPSTM.CXX                           propstm.cxx
ren ..\Source\PROPS\PROPVAR.CXX                           propvar.cxx
ren ..\Source\PROPS\PSETSTG.CXX                           psetstg.cxx
ren ..\Source\PROPS\PSETSTG.HXX                           psetstg.hxx
ren ..\Source\PROPS\QSORT.C                               qsort.c
ren ..\Source\PROPS\QSORT.H                               qsort.h
ren ..\Source\PROPS\STGVARB.CXX                           stgvarb.cxx
ren ..\Source\PROPS\TAGS                                  tags
ren ..\Source\PROPS\UTILS.CXX                             utils.cxx
ren ..\Source\PROPS\UTILS.HXX                             utils.hxx
ren ..\Source\PROPS\H\MAKEFILE                            makefile
ren ..\Source\PROPS\H\NTSTATUS.H                          ntstatus.h
ren ..\Source\PROPS\H\PROPAPI.H                           propapi.h
ren ..\Source\PROPS\H\PROPMAC.HXX                         propmac.hxx
ren ..\Source\PROPS\H\PROPSET.HXX                         propset.hxx
ren ..\Source\PROPS\H\PROPVAR.HXX                         propvar.hxx
ren ..\Source\PROPS\H\STGPROPS.HXX                        stgprops.hxx
ren ..\Source\PROPS\H\WINDEF.H                            windef.h
ren ..\Source\TEST\PROPTEST                               proptest
ren ..\Source\TEST\REFTEST                                reftest
ren ..\Source\TEST\STGDRT                                 stgdrt
ren ..\Source\TEST\PROPTEST\CHRESULT.HXX                  chresult.hxx
ren ..\Source\TEST\PROPTEST\CPROPVAR.CXX                  cpropvar.cxx
ren ..\Source\TEST\PROPTEST\CPROPVAR.HXX                  cpropvar.hxx
ren ..\Source\TEST\PROPTEST\DEPEND.GCC                    depend.gcc
ren ..\Source\TEST\PROPTEST\MAKEFILE                      makefile
ren ..\Source\TEST\PROPTEST\MAKEFILE.GCC                  makefile.gcc
ren ..\Source\TEST\PROPTEST\MAKEFILE.MSC                  makefile.msc
ren ..\Source\TEST\PROPTEST\PROPTEST.CXX                  proptest.cxx
ren ..\Source\TEST\PROPTEST\PROPTEST.HXX                  proptest.hxx
ren ..\Source\TEST\PROPTEST\README.TXT                    readme.txt
ren ..\Source\TEST\PROPTEST\TESTDOC.CXX                   testdoc.cxx
ren ..\Source\TEST\REFTEST\MAKEFILE                       makefile
ren ..\Source\TEST\REFTEST\MAKEFILE.GCC                   makefile.gcc
ren ..\Source\TEST\REFTEST\MAKEFILE.MSC                   makefile.msc
ren ..\Source\TEST\REFTEST\README.TXT                     readme.txt
ren ..\Source\TEST\REFTEST\REFILB.CXX                     refilb.cxx
ren ..\Source\TEST\REFTEST\REFILB.HXX                     refilb.hxx
ren ..\Source\TEST\REFTEST\REFTEST.CXX                    reftest.cxx
ren ..\Source\TEST\REFTEST\TIME.CXX                       time.cxx
ren ..\Source\TEST\REFTEST\TIME.HXX                       time.hxx
ren ..\Source\TEST\STGDRT\DEPEND.GCC                      depend.gcc
ren ..\Source\TEST\STGDRT\DEPEND.MSC                      depend.msc
ren ..\Source\TEST\STGDRT\DRT.CXX                         drt.cxx
ren ..\Source\TEST\STGDRT\DRT.HXX                         drt.hxx
ren ..\Source\TEST\STGDRT\HEADERS.CXX                     headers.cxx
ren ..\Source\TEST\STGDRT\ILB.CXX                         ilb.cxx
ren ..\Source\TEST\STGDRT\ILB.HXX                         ilb.hxx
ren ..\Source\TEST\STGDRT\ILLEG.CXX                       illeg.cxx
ren ..\Source\TEST\STGDRT\ILLEG.HXX                       illeg.hxx
ren ..\Source\TEST\STGDRT\MAKEFILE                        makefile
ren ..\Source\TEST\STGDRT\MAKEFILE.GCC                    makefile.gcc
ren ..\Source\TEST\STGDRT\MAKEFILE.MSC                    makefile.msc
ren ..\Source\TEST\STGDRT\README.TXT                      readme.txt
ren ..\Source\TEST\STGDRT\STRLIST.CXX                     strlist.cxx
ren ..\Source\TEST\STGDRT\STRLIST.HXX                     strlist.hxx
ren ..\Source\TEST\STGDRT\TESTS.CXX                       tests.cxx
ren ..\Source\TEST\STGDRT\TESTS.HXX                       tests.hxx
ren ..\Source\TEST\STGDRT\UTIL.CXX                        util.cxx
ren ..\Source\TEST\STGDRT\UTIL.HXX                        util.hxx
ren ..\Source\TEST\STGDRT\WCHAR.C                         wchar.c
ren ..\Source\TEST\STGDRT\WINIO.HXX                       winio.hxx
ren ..\Source\TEST\STGDRT\WINTYPE.HXX                     wintype.hxx
ren ..\Source\TEST\STGDRT\WRAP.CXX                        wrap.cxx
ren ..\Source\TEST\STGDRT\WRAP.HXX                        wrap.hxx
ren ..\Source\CHANGES\PROPS                               props
ren ..\Source\CHANGES\TEST                                test
ren ..\Source\CHANGES\MAKEFILE                            makefile
ren ..\Source\CHANGES\PROPS\MAKEFILE                      makefile
ren ..\Source\CHANGES\TEST\PROPTEST                       proptest
ren ..\Source\CHANGES\TEST\REFTEST                        reftest
ren ..\Source\CHANGES\TEST\STGDRT                         stgdrt
ren ..\Source\CHANGES\TEST\PROPTEST\MAKEFILE              makefile
ren ..\Source\CHANGES\TEST\REFTEST\MAKEFILE               makefile
ren ..\Source\CHANGES\TEST\REFTEST\MAKEFILE.GCC           makefile.gcc
ren ..\Source\CHANGES\TEST\STGDRT\DEPEND.GCC              depend.gcc
ren ..\Source\CHANGES\TEST\STGDRT\MAKEFILE                makefile
ren ..\Source\CHANGES\TEST\STGDRT\MAKEFILE.GCC            makefile.gcc
ren ..\Source\UNIX\SS.TAR                                 ss.tar
